### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AccessDenied
  commentId: T:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AccessDenied
  id: CreateSharedLinkWithSettingsError.AccessDenied
  parent: Dropbox.Api.Sharing
  children:
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AccessDenied.Instance
  langs:
  - csharp
  - vb
  name: CreateSharedLinkWithSettingsError.AccessDenied
  nameWithType: CreateSharedLinkWithSettingsError.AccessDenied
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AccessDenied
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsError.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: AccessDenied
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsError.cs
    startLine: 618
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>The user is not allowed to create a shared link to the specified file. For\nexample, this can occur if the file is restricted or if the user&apos;s links are  <a href=\"https://help.dropbox.com/files-folders/share/banned-links\">banned</a>.</p>\n"
  example: []
  syntax:
    content: 'public sealed class AccessDenied : CreateSharedLinkWithSettingsError'
    content.vb: >-
      Public NotInheritable Class AccessDenied
          Inherits CreateSharedLinkWithSettingsError
  inheritance:
  - System.Object
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  inheritedMembers:
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsPath
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsPath
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsEmailNotVerified
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsEmailNotVerified
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSharedLinkAlreadyExists
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSharedLinkAlreadyExists
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSettingsError
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSettingsError
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsAccessDenied
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsAccessDenied
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AccessDenied.Instance
  commentId: F:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AccessDenied.Instance
  id: Instance
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AccessDenied
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: CreateSharedLinkWithSettingsError.AccessDenied.Instance
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AccessDenied.Instance
  type: Field
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsError.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: Instance
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsError.cs
    startLine: 643
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>A singleton instance of AccessDenied</p>\n"
  example: []
  syntax:
    content: public static readonly CreateSharedLinkWithSettingsError.AccessDenied Instance
    return:
      type: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AccessDenied
    content.vb: Public Shared ReadOnly Instance As CreateSharedLinkWithSettingsError.AccessDenied
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: Dropbox.Api.Sharing
  commentId: N:Dropbox.Api.Sharing
  name: Dropbox.Api.Sharing
  nameWithType: Dropbox.Api.Sharing
  fullName: Dropbox.Api.Sharing
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  commentId: T:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  parent: Dropbox.Api.Sharing
  name: CreateSharedLinkWithSettingsError
  nameWithType: CreateSharedLinkWithSettingsError
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsPath
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsPath
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: IsPath
  nameWithType: CreateSharedLinkWithSettingsError.IsPath
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsPath
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsPath
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsPath
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: AsPath
  nameWithType: CreateSharedLinkWithSettingsError.AsPath
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsPath
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsEmailNotVerified
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsEmailNotVerified
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: IsEmailNotVerified
  nameWithType: CreateSharedLinkWithSettingsError.IsEmailNotVerified
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsEmailNotVerified
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsEmailNotVerified
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsEmailNotVerified
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: AsEmailNotVerified
  nameWithType: CreateSharedLinkWithSettingsError.AsEmailNotVerified
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsEmailNotVerified
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSharedLinkAlreadyExists
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSharedLinkAlreadyExists
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: IsSharedLinkAlreadyExists
  nameWithType: CreateSharedLinkWithSettingsError.IsSharedLinkAlreadyExists
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSharedLinkAlreadyExists
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSharedLinkAlreadyExists
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSharedLinkAlreadyExists
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: AsSharedLinkAlreadyExists
  nameWithType: CreateSharedLinkWithSettingsError.AsSharedLinkAlreadyExists
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSharedLinkAlreadyExists
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSettingsError
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSettingsError
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: IsSettingsError
  nameWithType: CreateSharedLinkWithSettingsError.IsSettingsError
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSettingsError
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSettingsError
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSettingsError
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: AsSettingsError
  nameWithType: CreateSharedLinkWithSettingsError.AsSettingsError
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSettingsError
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsAccessDenied
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsAccessDenied
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: IsAccessDenied
  nameWithType: CreateSharedLinkWithSettingsError.IsAccessDenied
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsAccessDenied
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsAccessDenied
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsAccessDenied
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: AsAccessDenied
  nameWithType: CreateSharedLinkWithSettingsError.AsAccessDenied
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsAccessDenied
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AccessDenied
  commentId: T:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AccessDenied
  parent: Dropbox.Api.Sharing
  name: CreateSharedLinkWithSettingsError.AccessDenied
  nameWithType: CreateSharedLinkWithSettingsError.AccessDenied
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AccessDenied
