### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings
  commentId: T:Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings
  id: SharedLinkSettingsError.InvalidSettings
  parent: Dropbox.Api.Sharing
  children:
  - Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings.Instance
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsError.InvalidSettings
  nameWithType: SharedLinkSettingsError.InvalidSettings
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/SharedLinkSettingsError.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: InvalidSettings
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/SharedLinkSettingsError.cs
    startLine: 160
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>The given settings are invalid (for example, all attributes of the <xref href=\"Dropbox.Api.Sharing.SharedLinkSettings\" data-throw-if-not-resolved=\"false\"></xref> are empty, the requested visibility is <xref href=\"Dropbox.Api.Sharing.RequestedVisibility.Password\" data-throw-if-not-resolved=\"false\"></xref> but the <xref href=\"Dropbox.Api.Sharing.SharedLinkSettings.LinkPassword\" data-throw-if-not-resolved=\"false\"></xref> is missing, <xref href=\"Dropbox.Api.Sharing.SharedLinkSettings.Expires\" data-throw-if-not-resolved=\"false\"></xref> is set to the past,\netc.).</p>\n"
  example: []
  syntax:
    content: 'public sealed class InvalidSettings : SharedLinkSettingsError'
    content.vb: >-
      Public NotInheritable Class InvalidSettings
          Inherits SharedLinkSettingsError
  inheritance:
  - System.Object
  - Dropbox.Api.Sharing.SharedLinkSettingsError
  inheritedMembers:
  - Dropbox.Api.Sharing.SharedLinkSettingsError.IsInvalidSettings
  - Dropbox.Api.Sharing.SharedLinkSettingsError.AsInvalidSettings
  - Dropbox.Api.Sharing.SharedLinkSettingsError.IsNotAuthorized
  - Dropbox.Api.Sharing.SharedLinkSettingsError.AsNotAuthorized
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings.Instance
  commentId: F:Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings.Instance
  id: Instance
  parent: Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: SharedLinkSettingsError.InvalidSettings.Instance
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings.Instance
  type: Field
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/SharedLinkSettingsError.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: Instance
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/SharedLinkSettingsError.cs
    startLine: 185
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>A singleton instance of InvalidSettings</p>\n"
  example: []
  syntax:
    content: public static readonly SharedLinkSettingsError.InvalidSettings Instance
    return:
      type: Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings
    content.vb: Public Shared ReadOnly Instance As SharedLinkSettingsError.InvalidSettings
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: Dropbox.Api.Sharing.SharedLinkSettings
  commentId: T:Dropbox.Api.Sharing.SharedLinkSettings
  parent: Dropbox.Api.Sharing
  name: SharedLinkSettings
  nameWithType: SharedLinkSettings
  fullName: Dropbox.Api.Sharing.SharedLinkSettings
- uid: Dropbox.Api.Sharing.RequestedVisibility.Password
  commentId: T:Dropbox.Api.Sharing.RequestedVisibility.Password
  parent: Dropbox.Api.Sharing
  name: RequestedVisibility.Password
  nameWithType: RequestedVisibility.Password
  fullName: Dropbox.Api.Sharing.RequestedVisibility.Password
- uid: Dropbox.Api.Sharing.SharedLinkSettings.LinkPassword
  commentId: P:Dropbox.Api.Sharing.SharedLinkSettings.LinkPassword
  isExternal: true
- uid: Dropbox.Api.Sharing.SharedLinkSettings.Expires
  commentId: P:Dropbox.Api.Sharing.SharedLinkSettings.Expires
  isExternal: true
- uid: Dropbox.Api.Sharing
  commentId: N:Dropbox.Api.Sharing
  name: Dropbox.Api.Sharing
  nameWithType: Dropbox.Api.Sharing
  fullName: Dropbox.Api.Sharing
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError
  commentId: T:Dropbox.Api.Sharing.SharedLinkSettingsError
  parent: Dropbox.Api.Sharing
  name: SharedLinkSettingsError
  nameWithType: SharedLinkSettingsError
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.IsInvalidSettings
  commentId: P:Dropbox.Api.Sharing.SharedLinkSettingsError.IsInvalidSettings
  parent: Dropbox.Api.Sharing.SharedLinkSettingsError
  name: IsInvalidSettings
  nameWithType: SharedLinkSettingsError.IsInvalidSettings
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.IsInvalidSettings
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.AsInvalidSettings
  commentId: P:Dropbox.Api.Sharing.SharedLinkSettingsError.AsInvalidSettings
  parent: Dropbox.Api.Sharing.SharedLinkSettingsError
  name: AsInvalidSettings
  nameWithType: SharedLinkSettingsError.AsInvalidSettings
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.AsInvalidSettings
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.IsNotAuthorized
  commentId: P:Dropbox.Api.Sharing.SharedLinkSettingsError.IsNotAuthorized
  parent: Dropbox.Api.Sharing.SharedLinkSettingsError
  name: IsNotAuthorized
  nameWithType: SharedLinkSettingsError.IsNotAuthorized
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.IsNotAuthorized
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.AsNotAuthorized
  commentId: P:Dropbox.Api.Sharing.SharedLinkSettingsError.AsNotAuthorized
  parent: Dropbox.Api.Sharing.SharedLinkSettingsError
  name: AsNotAuthorized
  nameWithType: SharedLinkSettingsError.AsNotAuthorized
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.AsNotAuthorized
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings
  commentId: T:Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings
  parent: Dropbox.Api.Sharing
  name: SharedLinkSettingsError.InvalidSettings
  nameWithType: SharedLinkSettingsError.InvalidSettings
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings
