### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.TeamLog.TfaConfiguration.Authenticator
  commentId: T:Dropbox.Api.TeamLog.TfaConfiguration.Authenticator
  id: TfaConfiguration.Authenticator
  parent: Dropbox.Api.TeamLog
  children:
  - Dropbox.Api.TeamLog.TfaConfiguration.Authenticator.Instance
  langs:
  - csharp
  - vb
  name: TfaConfiguration.Authenticator
  nameWithType: TfaConfiguration.Authenticator
  fullName: Dropbox.Api.TeamLog.TfaConfiguration.Authenticator
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TfaConfiguration.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: Authenticator
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TfaConfiguration.cs
    startLine: 243
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>The authenticator object</p>\n"
  example: []
  syntax:
    content: 'public sealed class Authenticator : TfaConfiguration'
    content.vb: >-
      Public NotInheritable Class Authenticator
          Inherits TfaConfiguration
  inheritance:
  - System.Object
  - Dropbox.Api.TeamLog.TfaConfiguration
  inheritedMembers:
  - Dropbox.Api.TeamLog.TfaConfiguration.IsAuthenticator
  - Dropbox.Api.TeamLog.TfaConfiguration.AsAuthenticator
  - Dropbox.Api.TeamLog.TfaConfiguration.IsDisabled
  - Dropbox.Api.TeamLog.TfaConfiguration.AsDisabled
  - Dropbox.Api.TeamLog.TfaConfiguration.IsEnabled
  - Dropbox.Api.TeamLog.TfaConfiguration.AsEnabled
  - Dropbox.Api.TeamLog.TfaConfiguration.IsSms
  - Dropbox.Api.TeamLog.TfaConfiguration.AsSms
  - Dropbox.Api.TeamLog.TfaConfiguration.IsOther
  - Dropbox.Api.TeamLog.TfaConfiguration.AsOther
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Dropbox.Api.TeamLog.TfaConfiguration.Authenticator.Instance
  commentId: F:Dropbox.Api.TeamLog.TfaConfiguration.Authenticator.Instance
  id: Instance
  parent: Dropbox.Api.TeamLog.TfaConfiguration.Authenticator
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: TfaConfiguration.Authenticator.Instance
  fullName: Dropbox.Api.TeamLog.TfaConfiguration.Authenticator.Instance
  type: Field
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TfaConfiguration.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: Instance
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TfaConfiguration.cs
    startLine: 268
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>A singleton instance of Authenticator</p>\n"
  example: []
  syntax:
    content: public static readonly TfaConfiguration.Authenticator Instance
    return:
      type: Dropbox.Api.TeamLog.TfaConfiguration.Authenticator
    content.vb: Public Shared ReadOnly Instance As TfaConfiguration.Authenticator
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: Dropbox.Api.TeamLog
  commentId: N:Dropbox.Api.TeamLog
  name: Dropbox.Api.TeamLog
  nameWithType: Dropbox.Api.TeamLog
  fullName: Dropbox.Api.TeamLog
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.TeamLog.TfaConfiguration
  commentId: T:Dropbox.Api.TeamLog.TfaConfiguration
  parent: Dropbox.Api.TeamLog
  name: TfaConfiguration
  nameWithType: TfaConfiguration
  fullName: Dropbox.Api.TeamLog.TfaConfiguration
- uid: Dropbox.Api.TeamLog.TfaConfiguration.IsAuthenticator
  commentId: P:Dropbox.Api.TeamLog.TfaConfiguration.IsAuthenticator
  parent: Dropbox.Api.TeamLog.TfaConfiguration
  name: IsAuthenticator
  nameWithType: TfaConfiguration.IsAuthenticator
  fullName: Dropbox.Api.TeamLog.TfaConfiguration.IsAuthenticator
- uid: Dropbox.Api.TeamLog.TfaConfiguration.AsAuthenticator
  commentId: P:Dropbox.Api.TeamLog.TfaConfiguration.AsAuthenticator
  parent: Dropbox.Api.TeamLog.TfaConfiguration
  name: AsAuthenticator
  nameWithType: TfaConfiguration.AsAuthenticator
  fullName: Dropbox.Api.TeamLog.TfaConfiguration.AsAuthenticator
- uid: Dropbox.Api.TeamLog.TfaConfiguration.IsDisabled
  commentId: P:Dropbox.Api.TeamLog.TfaConfiguration.IsDisabled
  parent: Dropbox.Api.TeamLog.TfaConfiguration
  name: IsDisabled
  nameWithType: TfaConfiguration.IsDisabled
  fullName: Dropbox.Api.TeamLog.TfaConfiguration.IsDisabled
- uid: Dropbox.Api.TeamLog.TfaConfiguration.AsDisabled
  commentId: P:Dropbox.Api.TeamLog.TfaConfiguration.AsDisabled
  parent: Dropbox.Api.TeamLog.TfaConfiguration
  name: AsDisabled
  nameWithType: TfaConfiguration.AsDisabled
  fullName: Dropbox.Api.TeamLog.TfaConfiguration.AsDisabled
- uid: Dropbox.Api.TeamLog.TfaConfiguration.IsEnabled
  commentId: P:Dropbox.Api.TeamLog.TfaConfiguration.IsEnabled
  parent: Dropbox.Api.TeamLog.TfaConfiguration
  name: IsEnabled
  nameWithType: TfaConfiguration.IsEnabled
  fullName: Dropbox.Api.TeamLog.TfaConfiguration.IsEnabled
- uid: Dropbox.Api.TeamLog.TfaConfiguration.AsEnabled
  commentId: P:Dropbox.Api.TeamLog.TfaConfiguration.AsEnabled
  parent: Dropbox.Api.TeamLog.TfaConfiguration
  name: AsEnabled
  nameWithType: TfaConfiguration.AsEnabled
  fullName: Dropbox.Api.TeamLog.TfaConfiguration.AsEnabled
- uid: Dropbox.Api.TeamLog.TfaConfiguration.IsSms
  commentId: P:Dropbox.Api.TeamLog.TfaConfiguration.IsSms
  parent: Dropbox.Api.TeamLog.TfaConfiguration
  name: IsSms
  nameWithType: TfaConfiguration.IsSms
  fullName: Dropbox.Api.TeamLog.TfaConfiguration.IsSms
- uid: Dropbox.Api.TeamLog.TfaConfiguration.AsSms
  commentId: P:Dropbox.Api.TeamLog.TfaConfiguration.AsSms
  parent: Dropbox.Api.TeamLog.TfaConfiguration
  name: AsSms
  nameWithType: TfaConfiguration.AsSms
  fullName: Dropbox.Api.TeamLog.TfaConfiguration.AsSms
- uid: Dropbox.Api.TeamLog.TfaConfiguration.IsOther
  commentId: P:Dropbox.Api.TeamLog.TfaConfiguration.IsOther
  parent: Dropbox.Api.TeamLog.TfaConfiguration
  name: IsOther
  nameWithType: TfaConfiguration.IsOther
  fullName: Dropbox.Api.TeamLog.TfaConfiguration.IsOther
- uid: Dropbox.Api.TeamLog.TfaConfiguration.AsOther
  commentId: P:Dropbox.Api.TeamLog.TfaConfiguration.AsOther
  parent: Dropbox.Api.TeamLog.TfaConfiguration
  name: AsOther
  nameWithType: TfaConfiguration.AsOther
  fullName: Dropbox.Api.TeamLog.TfaConfiguration.AsOther
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Dropbox.Api.TeamLog.TfaConfiguration.Authenticator
  commentId: T:Dropbox.Api.TeamLog.TfaConfiguration.Authenticator
  parent: Dropbox.Api.TeamLog
  name: TfaConfiguration.Authenticator
  nameWithType: TfaConfiguration.Authenticator
  fullName: Dropbox.Api.TeamLog.TfaConfiguration.Authenticator
