### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Users.UserFeaturesGetValuesBatchResult
  commentId: T:Dropbox.Api.Users.UserFeaturesGetValuesBatchResult
  id: UserFeaturesGetValuesBatchResult
  parent: Dropbox.Api.Users
  children:
  - Dropbox.Api.Users.UserFeaturesGetValuesBatchResult.#ctor(System.Collections.Generic.IEnumerable{Dropbox.Api.Users.UserFeatureValue})
  - Dropbox.Api.Users.UserFeaturesGetValuesBatchResult.Values
  langs:
  - csharp
  - vb
  name: UserFeaturesGetValuesBatchResult
  nameWithType: UserFeaturesGetValuesBatchResult
  fullName: Dropbox.Api.Users.UserFeaturesGetValuesBatchResult
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Users/UserFeaturesGetValuesBatchResult.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: UserFeaturesGetValuesBatchResult
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Users/UserFeaturesGetValuesBatchResult.cs
    startLine: 15
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Users
  summary: "\n<p>The user features get values batch result object</p>\n"
  example: []
  syntax:
    content: public class UserFeaturesGetValuesBatchResult
    content.vb: Public Class UserFeaturesGetValuesBatchResult
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Dropbox.Api.Users.UserFeaturesGetValuesBatchResult.#ctor(System.Collections.Generic.IEnumerable{Dropbox.Api.Users.UserFeatureValue})
  commentId: M:Dropbox.Api.Users.UserFeaturesGetValuesBatchResult.#ctor(System.Collections.Generic.IEnumerable{Dropbox.Api.Users.UserFeatureValue})
  id: '#ctor(System.Collections.Generic.IEnumerable{Dropbox.Api.Users.UserFeatureValue})'
  parent: Dropbox.Api.Users.UserFeaturesGetValuesBatchResult
  langs:
  - csharp
  - vb
  name: UserFeaturesGetValuesBatchResult(IEnumerable<UserFeatureValue>)
  nameWithType: UserFeaturesGetValuesBatchResult.UserFeaturesGetValuesBatchResult(IEnumerable<UserFeatureValue>)
  fullName: Dropbox.Api.Users.UserFeaturesGetValuesBatchResult.UserFeaturesGetValuesBatchResult(System.Collections.Generic.IEnumerable<Dropbox.Api.Users.UserFeatureValue>)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Users/UserFeaturesGetValuesBatchResult.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Users/UserFeaturesGetValuesBatchResult.cs
    startLine: 34
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Users
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.Users.UserFeaturesGetValuesBatchResult\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  example: []
  syntax:
    content: public UserFeaturesGetValuesBatchResult(IEnumerable<UserFeatureValue> values)
    parameters:
    - id: values
      type: System.Collections.Generic.IEnumerable{Dropbox.Api.Users.UserFeatureValue}
      description: The values
    content.vb: Public Sub New(values As IEnumerable(Of UserFeatureValue))
  overload: Dropbox.Api.Users.UserFeaturesGetValuesBatchResult.#ctor*
  nameWithType.vb: UserFeaturesGetValuesBatchResult.UserFeaturesGetValuesBatchResult(IEnumerable(Of UserFeatureValue))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Dropbox.Api.Users.UserFeaturesGetValuesBatchResult.UserFeaturesGetValuesBatchResult(System.Collections.Generic.IEnumerable(Of Dropbox.Api.Users.UserFeatureValue))
  name.vb: UserFeaturesGetValuesBatchResult(IEnumerable(Of UserFeatureValue))
- uid: Dropbox.Api.Users.UserFeaturesGetValuesBatchResult.Values
  commentId: P:Dropbox.Api.Users.UserFeaturesGetValuesBatchResult.Values
  id: Values
  parent: Dropbox.Api.Users.UserFeaturesGetValuesBatchResult
  langs:
  - csharp
  - vb
  name: Values
  nameWithType: UserFeaturesGetValuesBatchResult.Values
  fullName: Dropbox.Api.Users.UserFeaturesGetValuesBatchResult.Values
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Users/UserFeaturesGetValuesBatchResult.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: Values
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Users/UserFeaturesGetValuesBatchResult.cs
    startLine: 60
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Users
  summary: "\n<p>Gets the values of the user features get values batch result</p>\n"
  example: []
  syntax:
    content: public IList<UserFeatureValue> Values { get; protected set; }
    parameters: []
    return:
      type: System.Collections.Generic.IList{Dropbox.Api.Users.UserFeatureValue}
    content.vb: Public Property Values As IList(Of UserFeatureValue)
  overload: Dropbox.Api.Users.UserFeaturesGetValuesBatchResult.Values*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
references:
- uid: Dropbox.Api.Users
  commentId: N:Dropbox.Api.Users
  name: Dropbox.Api.Users
  nameWithType: Dropbox.Api.Users
  fullName: Dropbox.Api.Users
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Dropbox.Api.Users.UserFeaturesGetValuesBatchResult
  commentId: T:Dropbox.Api.Users.UserFeaturesGetValuesBatchResult
  parent: Dropbox.Api.Users
  name: UserFeaturesGetValuesBatchResult
  nameWithType: UserFeaturesGetValuesBatchResult
  fullName: Dropbox.Api.Users.UserFeaturesGetValuesBatchResult
- uid: Dropbox.Api.Users.UserFeaturesGetValuesBatchResult.#ctor*
  commentId: Overload:Dropbox.Api.Users.UserFeaturesGetValuesBatchResult.#ctor
  name: UserFeaturesGetValuesBatchResult
  nameWithType: UserFeaturesGetValuesBatchResult.UserFeaturesGetValuesBatchResult
  fullName: Dropbox.Api.Users.UserFeaturesGetValuesBatchResult.UserFeaturesGetValuesBatchResult
- uid: System.Collections.Generic.IEnumerable{Dropbox.Api.Users.UserFeatureValue}
  commentId: T:System.Collections.Generic.IEnumerable{Dropbox.Api.Users.UserFeatureValue}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  name: IEnumerable<UserFeatureValue>
  nameWithType: IEnumerable<UserFeatureValue>
  fullName: System.Collections.Generic.IEnumerable<Dropbox.Api.Users.UserFeatureValue>
  nameWithType.vb: IEnumerable(Of UserFeatureValue)
  fullName.vb: System.Collections.Generic.IEnumerable(Of Dropbox.Api.Users.UserFeatureValue)
  name.vb: IEnumerable(Of UserFeatureValue)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Dropbox.Api.Users.UserFeatureValue
    name: UserFeatureValue
    nameWithType: UserFeatureValue
    fullName: Dropbox.Api.Users.UserFeatureValue
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Dropbox.Api.Users.UserFeatureValue
    name: UserFeatureValue
    nameWithType: UserFeatureValue
    fullName: Dropbox.Api.Users.UserFeatureValue
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: Dropbox.Api.Users.UserFeaturesGetValuesBatchResult.Values*
  commentId: Overload:Dropbox.Api.Users.UserFeaturesGetValuesBatchResult.Values
  name: Values
  nameWithType: UserFeaturesGetValuesBatchResult.Values
  fullName: Dropbox.Api.Users.UserFeaturesGetValuesBatchResult.Values
- uid: System.Collections.Generic.IList{Dropbox.Api.Users.UserFeatureValue}
  commentId: T:System.Collections.Generic.IList{Dropbox.Api.Users.UserFeatureValue}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<UserFeatureValue>
  nameWithType: IList<UserFeatureValue>
  fullName: System.Collections.Generic.IList<Dropbox.Api.Users.UserFeatureValue>
  nameWithType.vb: IList(Of UserFeatureValue)
  fullName.vb: System.Collections.Generic.IList(Of Dropbox.Api.Users.UserFeatureValue)
  name.vb: IList(Of UserFeatureValue)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Dropbox.Api.Users.UserFeatureValue
    name: UserFeatureValue
    nameWithType: UserFeatureValue
    fullName: Dropbox.Api.Users.UserFeatureValue
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Dropbox.Api.Users.UserFeatureValue
    name: UserFeatureValue
    nameWithType: UserFeatureValue
    fullName: Dropbox.Api.Users.UserFeatureValue
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  commentId: T:System.Collections.Generic.IList`1
  isExternal: true
  name: IList<T>
  nameWithType: IList<T>
  fullName: System.Collections.Generic.IList<T>
  nameWithType.vb: IList(Of T)
  fullName.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
