### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError
  commentId: T:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError
  id: CreateSharedLinkWithSettingsError.SettingsError
  parent: Dropbox.Api.Sharing
  children:
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError.#ctor(Dropbox.Api.Sharing.SharedLinkSettingsError)
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError.Value
  langs:
  - csharp
  - vb
  name: CreateSharedLinkWithSettingsError.SettingsError
  nameWithType: CreateSharedLinkWithSettingsError.SettingsError
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsError.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: SettingsError
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsError.cs
    startLine: 518
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>There is an error with the given settings.</p>\n"
  example: []
  syntax:
    content: 'public sealed class SettingsError : CreateSharedLinkWithSettingsError'
    content.vb: >-
      Public NotInheritable Class SettingsError
          Inherits CreateSharedLinkWithSettingsError
  inheritance:
  - System.Object
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  inheritedMembers:
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsPath
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsPath
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsEmailNotVerified
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsEmailNotVerified
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSharedLinkAlreadyExists
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSharedLinkAlreadyExists
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSettingsError
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSettingsError
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsAccessDenied
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsAccessDenied
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError.#ctor(Dropbox.Api.Sharing.SharedLinkSettingsError)
  commentId: M:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError.#ctor(Dropbox.Api.Sharing.SharedLinkSettingsError)
  id: '#ctor(Dropbox.Api.Sharing.SharedLinkSettingsError)'
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError
  langs:
  - csharp
  - vb
  name: SettingsError(SharedLinkSettingsError)
  nameWithType: CreateSharedLinkWithSettingsError.SettingsError.SettingsError(SharedLinkSettingsError)
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError.SettingsError(Dropbox.Api.Sharing.SharedLinkSettingsError)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsError.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsError.cs
    startLine: 537
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError\" data-throw-if-not-resolved=\"false\"></xref>\nclass.</p>\n"
  example: []
  syntax:
    content: public SettingsError(SharedLinkSettingsError value)
    parameters:
    - id: value
      type: Dropbox.Api.Sharing.SharedLinkSettingsError
      description: The value
    content.vb: Public Sub New(value As SharedLinkSettingsError)
  overload: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError.Value
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError.Value
  id: Value
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: CreateSharedLinkWithSettingsError.SettingsError.Value
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError.Value
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsError.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: Value
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsError.cs
    startLine: 552
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>Gets the value of this instance.</p>\n"
  example: []
  syntax:
    content: public SharedLinkSettingsError Value { get; }
    parameters: []
    return:
      type: Dropbox.Api.Sharing.SharedLinkSettingsError
    content.vb: Public ReadOnly Property Value As SharedLinkSettingsError
  overload: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError.Value*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Dropbox.Api.Sharing
  commentId: N:Dropbox.Api.Sharing
  name: Dropbox.Api.Sharing
  nameWithType: Dropbox.Api.Sharing
  fullName: Dropbox.Api.Sharing
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  commentId: T:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  parent: Dropbox.Api.Sharing
  name: CreateSharedLinkWithSettingsError
  nameWithType: CreateSharedLinkWithSettingsError
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsPath
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsPath
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: IsPath
  nameWithType: CreateSharedLinkWithSettingsError.IsPath
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsPath
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsPath
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsPath
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: AsPath
  nameWithType: CreateSharedLinkWithSettingsError.AsPath
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsPath
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsEmailNotVerified
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsEmailNotVerified
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: IsEmailNotVerified
  nameWithType: CreateSharedLinkWithSettingsError.IsEmailNotVerified
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsEmailNotVerified
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsEmailNotVerified
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsEmailNotVerified
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: AsEmailNotVerified
  nameWithType: CreateSharedLinkWithSettingsError.AsEmailNotVerified
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsEmailNotVerified
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSharedLinkAlreadyExists
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSharedLinkAlreadyExists
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: IsSharedLinkAlreadyExists
  nameWithType: CreateSharedLinkWithSettingsError.IsSharedLinkAlreadyExists
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSharedLinkAlreadyExists
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSharedLinkAlreadyExists
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSharedLinkAlreadyExists
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: AsSharedLinkAlreadyExists
  nameWithType: CreateSharedLinkWithSettingsError.AsSharedLinkAlreadyExists
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSharedLinkAlreadyExists
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSettingsError
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSettingsError
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: IsSettingsError
  nameWithType: CreateSharedLinkWithSettingsError.IsSettingsError
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSettingsError
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSettingsError
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSettingsError
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: AsSettingsError
  nameWithType: CreateSharedLinkWithSettingsError.AsSettingsError
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSettingsError
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsAccessDenied
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsAccessDenied
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: IsAccessDenied
  nameWithType: CreateSharedLinkWithSettingsError.IsAccessDenied
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsAccessDenied
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsAccessDenied
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsAccessDenied
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: AsAccessDenied
  nameWithType: CreateSharedLinkWithSettingsError.AsAccessDenied
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsAccessDenied
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError
  commentId: T:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError
  parent: Dropbox.Api.Sharing
  name: CreateSharedLinkWithSettingsError.SettingsError
  nameWithType: CreateSharedLinkWithSettingsError.SettingsError
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError.#ctor*
  commentId: Overload:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError.#ctor
  name: SettingsError
  nameWithType: CreateSharedLinkWithSettingsError.SettingsError.SettingsError
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError.SettingsError
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError
  commentId: T:Dropbox.Api.Sharing.SharedLinkSettingsError
  parent: Dropbox.Api.Sharing
  name: SharedLinkSettingsError
  nameWithType: SharedLinkSettingsError
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError.Value*
  commentId: Overload:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError.Value
  name: Value
  nameWithType: CreateSharedLinkWithSettingsError.SettingsError.Value
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.SettingsError.Value
