### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails
  commentId: T:Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails
  id: TeamSelectiveSyncSettingsChangedDetails
  parent: Dropbox.Api.TeamLog
  children:
  - Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.#ctor(Dropbox.Api.Files.SyncSetting,Dropbox.Api.Files.SyncSetting)
  - Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.NewValue
  - Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.PreviousValue
  langs:
  - csharp
  - vb
  name: TeamSelectiveSyncSettingsChangedDetails
  nameWithType: TeamSelectiveSyncSettingsChangedDetails
  fullName: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TeamSelectiveSyncSettingsChangedDetails.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: TeamSelectiveSyncSettingsChangedDetails
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TeamSelectiveSyncSettingsChangedDetails.cs
    startLine: 15
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Changed sync default.</p>\n"
  example: []
  syntax:
    content: public class TeamSelectiveSyncSettingsChangedDetails
    content.vb: Public Class TeamSelectiveSyncSettingsChangedDetails
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.#ctor(Dropbox.Api.Files.SyncSetting,Dropbox.Api.Files.SyncSetting)
  commentId: M:Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.#ctor(Dropbox.Api.Files.SyncSetting,Dropbox.Api.Files.SyncSetting)
  id: '#ctor(Dropbox.Api.Files.SyncSetting,Dropbox.Api.Files.SyncSetting)'
  parent: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails
  langs:
  - csharp
  - vb
  name: TeamSelectiveSyncSettingsChangedDetails(SyncSetting, SyncSetting)
  nameWithType: TeamSelectiveSyncSettingsChangedDetails.TeamSelectiveSyncSettingsChangedDetails(SyncSetting, SyncSetting)
  fullName: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.TeamSelectiveSyncSettingsChangedDetails(Dropbox.Api.Files.SyncSetting, Dropbox.Api.Files.SyncSetting)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TeamSelectiveSyncSettingsChangedDetails.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TeamSelectiveSyncSettingsChangedDetails.cs
    startLine: 35
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  example: []
  syntax:
    content: public TeamSelectiveSyncSettingsChangedDetails(SyncSetting previousValue, SyncSetting newValue)
    parameters:
    - id: previousValue
      type: Dropbox.Api.Files.SyncSetting
      description: Previous value.
    - id: newValue
      type: Dropbox.Api.Files.SyncSetting
      description: New value.
    content.vb: Public Sub New(previousValue As SyncSetting, newValue As SyncSetting)
  overload: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.PreviousValue
  commentId: P:Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.PreviousValue
  id: PreviousValue
  parent: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails
  langs:
  - csharp
  - vb
  name: PreviousValue
  nameWithType: TeamSelectiveSyncSettingsChangedDetails.PreviousValue
  fullName: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.PreviousValue
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TeamSelectiveSyncSettingsChangedDetails.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: PreviousValue
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TeamSelectiveSyncSettingsChangedDetails.cs
    startLine: 66
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Previous value.</p>\n"
  example: []
  syntax:
    content: public SyncSetting PreviousValue { get; protected set; }
    parameters: []
    return:
      type: Dropbox.Api.Files.SyncSetting
    content.vb: Public Property PreviousValue As SyncSetting
  overload: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.PreviousValue*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.NewValue
  commentId: P:Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.NewValue
  id: NewValue
  parent: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails
  langs:
  - csharp
  - vb
  name: NewValue
  nameWithType: TeamSelectiveSyncSettingsChangedDetails.NewValue
  fullName: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.NewValue
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TeamSelectiveSyncSettingsChangedDetails.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: NewValue
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TeamSelectiveSyncSettingsChangedDetails.cs
    startLine: 71
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>New value.</p>\n"
  example: []
  syntax:
    content: public SyncSetting NewValue { get; protected set; }
    parameters: []
    return:
      type: Dropbox.Api.Files.SyncSetting
    content.vb: Public Property NewValue As SyncSetting
  overload: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.NewValue*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
references:
- uid: Dropbox.Api.TeamLog
  commentId: N:Dropbox.Api.TeamLog
  name: Dropbox.Api.TeamLog
  nameWithType: Dropbox.Api.TeamLog
  fullName: Dropbox.Api.TeamLog
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails
  commentId: T:Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails
  parent: Dropbox.Api.TeamLog
  name: TeamSelectiveSyncSettingsChangedDetails
  nameWithType: TeamSelectiveSyncSettingsChangedDetails
  fullName: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails
- uid: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.#ctor*
  commentId: Overload:Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.#ctor
  name: TeamSelectiveSyncSettingsChangedDetails
  nameWithType: TeamSelectiveSyncSettingsChangedDetails.TeamSelectiveSyncSettingsChangedDetails
  fullName: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.TeamSelectiveSyncSettingsChangedDetails
- uid: Dropbox.Api.Files.SyncSetting
  commentId: T:Dropbox.Api.Files.SyncSetting
  parent: Dropbox.Api.Files
  name: SyncSetting
  nameWithType: SyncSetting
  fullName: Dropbox.Api.Files.SyncSetting
- uid: Dropbox.Api.Files
  commentId: N:Dropbox.Api.Files
  name: Dropbox.Api.Files
  nameWithType: Dropbox.Api.Files
  fullName: Dropbox.Api.Files
- uid: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.PreviousValue*
  commentId: Overload:Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.PreviousValue
  name: PreviousValue
  nameWithType: TeamSelectiveSyncSettingsChangedDetails.PreviousValue
  fullName: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.PreviousValue
- uid: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.NewValue*
  commentId: Overload:Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.NewValue
  name: NewValue
  nameWithType: TeamSelectiveSyncSettingsChangedDetails.NewValue
  fullName: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedDetails.NewValue
