### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
  commentId: T:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
  id: CreateSharedLinkWithSettingsArg
  parent: Dropbox.Api.Sharing
  children:
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.#ctor(System.String,Dropbox.Api.Sharing.SharedLinkSettings)
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Path
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Settings
  langs:
  - csharp
  - vb
  name: CreateSharedLinkWithSettingsArg
  nameWithType: CreateSharedLinkWithSettingsArg
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsArg.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: CreateSharedLinkWithSettingsArg
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsArg.cs
    startLine: 15
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>The create shared link with settings arg object</p>\n"
  example: []
  syntax:
    content: public class CreateSharedLinkWithSettingsArg
    content.vb: Public Class CreateSharedLinkWithSettingsArg
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.#ctor(System.String,Dropbox.Api.Sharing.SharedLinkSettings)
  commentId: M:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.#ctor(System.String,Dropbox.Api.Sharing.SharedLinkSettings)
  id: '#ctor(System.String,Dropbox.Api.Sharing.SharedLinkSettings)'
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
  langs:
  - csharp
  - vb
  name: CreateSharedLinkWithSettingsArg(String, SharedLinkSettings)
  nameWithType: CreateSharedLinkWithSettingsArg.CreateSharedLinkWithSettingsArg(String, SharedLinkSettings)
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.CreateSharedLinkWithSettingsArg(System.String, Dropbox.Api.Sharing.SharedLinkSettings)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsArg.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsArg.cs
    startLine: 36
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  example: []
  syntax:
    content: public CreateSharedLinkWithSettingsArg(string path, SharedLinkSettings settings = null)
    parameters:
    - id: path
      type: System.String
      description: The path to be shared by the shared link.
    - id: settings
      type: Dropbox.Api.Sharing.SharedLinkSettings
      description: >-
        The requested settings for the newly created shared

        link.
    content.vb: Public Sub New(path As String, settings As SharedLinkSettings = Nothing)
  overload: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Path
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Path
  id: Path
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
  langs:
  - csharp
  - vb
  name: Path
  nameWithType: CreateSharedLinkWithSettingsArg.Path
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Path
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsArg.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: Path
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsArg.cs
    startLine: 66
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>The path to be shared by the shared link.</p>\n"
  example: []
  syntax:
    content: public string Path { get; protected set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Path As String
  overload: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Path*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Settings
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Settings
  id: Settings
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
  langs:
  - csharp
  - vb
  name: Settings
  nameWithType: CreateSharedLinkWithSettingsArg.Settings
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Settings
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsArg.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: Settings
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsArg.cs
    startLine: 71
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>The requested settings for the newly created shared link.</p>\n"
  example: []
  syntax:
    content: public SharedLinkSettings Settings { get; protected set; }
    parameters: []
    return:
      type: Dropbox.Api.Sharing.SharedLinkSettings
    content.vb: Public Property Settings As SharedLinkSettings
  overload: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Settings*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
references:
- uid: Dropbox.Api.Sharing
  commentId: N:Dropbox.Api.Sharing
  name: Dropbox.Api.Sharing
  nameWithType: Dropbox.Api.Sharing
  fullName: Dropbox.Api.Sharing
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
  commentId: T:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
  parent: Dropbox.Api.Sharing
  name: CreateSharedLinkWithSettingsArg
  nameWithType: CreateSharedLinkWithSettingsArg
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.#ctor*
  commentId: Overload:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.#ctor
  name: CreateSharedLinkWithSettingsArg
  nameWithType: CreateSharedLinkWithSettingsArg.CreateSharedLinkWithSettingsArg
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.CreateSharedLinkWithSettingsArg
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Dropbox.Api.Sharing.SharedLinkSettings
  commentId: T:Dropbox.Api.Sharing.SharedLinkSettings
  parent: Dropbox.Api.Sharing
  name: SharedLinkSettings
  nameWithType: SharedLinkSettings
  fullName: Dropbox.Api.Sharing.SharedLinkSettings
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Path*
  commentId: Overload:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Path
  name: Path
  nameWithType: CreateSharedLinkWithSettingsArg.Path
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Path
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Settings*
  commentId: Overload:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Settings
  name: Settings
  nameWithType: CreateSharedLinkWithSettingsArg.Settings
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Settings
