### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Auth.Routes.AuthUserRoutes
  commentId: T:Dropbox.Api.Auth.Routes.AuthUserRoutes
  id: AuthUserRoutes
  parent: Dropbox.Api.Auth.Routes
  children:
  - Dropbox.Api.Auth.Routes.AuthUserRoutes.BeginTokenRevoke(System.AsyncCallback,System.Object)
  - Dropbox.Api.Auth.Routes.AuthUserRoutes.EndTokenRevoke(System.IAsyncResult)
  - Dropbox.Api.Auth.Routes.AuthUserRoutes.TokenRevokeAsync
  langs:
  - csharp
  - vb
  name: AuthUserRoutes
  nameWithType: AuthUserRoutes
  fullName: Dropbox.Api.Auth.Routes.AuthUserRoutes
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Auth/AuthUserRoutes.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: AuthUserRoutes
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Auth/AuthUserRoutes.cs
    startLine: 15
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Auth.Routes
  summary: "\n<p>The routes for the <xref href=\"Dropbox.Api.Auth\" data-throw-if-not-resolved=\"false\"></xref> namespace</p>\n"
  example: []
  syntax:
    content: public class AuthUserRoutes
    content.vb: Public Class AuthUserRoutes
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Dropbox.Api.Auth.Routes.AuthUserRoutes.TokenRevokeAsync
  commentId: M:Dropbox.Api.Auth.Routes.AuthUserRoutes.TokenRevokeAsync
  id: TokenRevokeAsync
  parent: Dropbox.Api.Auth.Routes.AuthUserRoutes
  langs:
  - csharp
  - vb
  name: TokenRevokeAsync()
  nameWithType: AuthUserRoutes.TokenRevokeAsync()
  fullName: Dropbox.Api.Auth.Routes.AuthUserRoutes.TokenRevokeAsync()
  type: Method
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Auth/AuthUserRoutes.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: TokenRevokeAsync
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Auth/AuthUserRoutes.cs
    startLine: 37
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Auth.Routes
  summary: "\n<p>Disables the access token used to authenticate the call. If there is a\ncorresponding refresh token for the access token, this disables that refresh token,\nas well as any other access tokens for that refresh token.</p>\n"
  example: []
  syntax:
    content: public Task TokenRevokeAsync()
    return:
      type: System.Threading.Tasks.Task
      description: The task that represents the asynchronous send operation.
    content.vb: Public Function TokenRevokeAsync As Task
  overload: Dropbox.Api.Auth.Routes.AuthUserRoutes.TokenRevokeAsync*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.Auth.Routes.AuthUserRoutes.BeginTokenRevoke(System.AsyncCallback,System.Object)
  commentId: M:Dropbox.Api.Auth.Routes.AuthUserRoutes.BeginTokenRevoke(System.AsyncCallback,System.Object)
  id: BeginTokenRevoke(System.AsyncCallback,System.Object)
  parent: Dropbox.Api.Auth.Routes.AuthUserRoutes
  langs:
  - csharp
  - vb
  name: BeginTokenRevoke(AsyncCallback, Object)
  nameWithType: AuthUserRoutes.BeginTokenRevoke(AsyncCallback, Object)
  fullName: Dropbox.Api.Auth.Routes.AuthUserRoutes.BeginTokenRevoke(System.AsyncCallback, System.Object)
  type: Method
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Auth/AuthUserRoutes.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: BeginTokenRevoke
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Auth/AuthUserRoutes.cs
    startLine: 50
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Auth.Routes
  summary: "\n<p>Begins an asynchronous send to the token revoke route.</p>\n"
  example: []
  syntax:
    content: public IAsyncResult BeginTokenRevoke(AsyncCallback callback, object state = null)
    parameters:
    - id: callback
      type: System.AsyncCallback
      description: >-
        The method to be called when the asynchronous send is

        completed.
    - id: state
      type: System.Object
      description: >-
        A user provided object that distinguished this send from other

        send requests.
    return:
      type: System.IAsyncResult
      description: An object that represents the asynchronous send request.
    content.vb: Public Function BeginTokenRevoke(callback As AsyncCallback, state As Object = Nothing) As IAsyncResult
  overload: Dropbox.Api.Auth.Routes.AuthUserRoutes.BeginTokenRevoke*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.Auth.Routes.AuthUserRoutes.EndTokenRevoke(System.IAsyncResult)
  commentId: M:Dropbox.Api.Auth.Routes.AuthUserRoutes.EndTokenRevoke(System.IAsyncResult)
  id: EndTokenRevoke(System.IAsyncResult)
  parent: Dropbox.Api.Auth.Routes.AuthUserRoutes
  langs:
  - csharp
  - vb
  name: EndTokenRevoke(IAsyncResult)
  nameWithType: AuthUserRoutes.EndTokenRevoke(IAsyncResult)
  fullName: Dropbox.Api.Auth.Routes.AuthUserRoutes.EndTokenRevoke(System.IAsyncResult)
  type: Method
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Auth/AuthUserRoutes.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: EndTokenRevoke
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Auth/AuthUserRoutes.cs
    startLine: 63
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Auth.Routes
  summary: "\n<p>Waits for the pending asynchronous send to the token revoke route to\ncomplete</p>\n"
  example: []
  syntax:
    content: public void EndTokenRevoke(IAsyncResult asyncResult)
    parameters:
    - id: asyncResult
      type: System.IAsyncResult
      description: >-
        The reference to the pending asynchronous send

        request
    content.vb: Public Sub EndTokenRevoke(asyncResult As IAsyncResult)
  overload: Dropbox.Api.Auth.Routes.AuthUserRoutes.EndTokenRevoke*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Dropbox.Api.Auth
  commentId: N:Dropbox.Api.Auth
  name: Dropbox.Api.Auth
  nameWithType: Dropbox.Api.Auth
  fullName: Dropbox.Api.Auth
- uid: Dropbox.Api.Auth.Routes
  commentId: N:Dropbox.Api.Auth.Routes
  name: Dropbox.Api.Auth.Routes
  nameWithType: Dropbox.Api.Auth.Routes
  fullName: Dropbox.Api.Auth.Routes
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Dropbox.Api.Auth.Routes.AuthUserRoutes.TokenRevokeAsync*
  commentId: Overload:Dropbox.Api.Auth.Routes.AuthUserRoutes.TokenRevokeAsync
  name: TokenRevokeAsync
  nameWithType: AuthUserRoutes.TokenRevokeAsync
  fullName: Dropbox.Api.Auth.Routes.AuthUserRoutes.TokenRevokeAsync
- uid: System.Threading.Tasks.Task
  commentId: T:System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
- uid: Dropbox.Api.Auth.Routes.AuthUserRoutes.BeginTokenRevoke*
  commentId: Overload:Dropbox.Api.Auth.Routes.AuthUserRoutes.BeginTokenRevoke
  name: BeginTokenRevoke
  nameWithType: AuthUserRoutes.BeginTokenRevoke
  fullName: Dropbox.Api.Auth.Routes.AuthUserRoutes.BeginTokenRevoke
- uid: System.AsyncCallback
  commentId: T:System.AsyncCallback
  parent: System
  isExternal: true
  name: AsyncCallback
  nameWithType: AsyncCallback
  fullName: System.AsyncCallback
- uid: System.IAsyncResult
  commentId: T:System.IAsyncResult
  parent: System
  isExternal: true
  name: IAsyncResult
  nameWithType: IAsyncResult
  fullName: System.IAsyncResult
- uid: Dropbox.Api.Auth.Routes.AuthUserRoutes.EndTokenRevoke*
  commentId: Overload:Dropbox.Api.Auth.Routes.AuthUserRoutes.EndTokenRevoke
  name: EndTokenRevoke
  nameWithType: AuthUserRoutes.EndTokenRevoke
  fullName: Dropbox.Api.Auth.Routes.AuthUserRoutes.EndTokenRevoke
