### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchError.Other
  commentId: T:Dropbox.Api.Team.FeaturesGetValuesBatchError.Other
  id: FeaturesGetValuesBatchError.Other
  parent: Dropbox.Api.Team
  children:
  - Dropbox.Api.Team.FeaturesGetValuesBatchError.Other.Instance
  langs:
  - csharp
  - vb
  name: FeaturesGetValuesBatchError.Other
  nameWithType: FeaturesGetValuesBatchError.Other
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchError.Other
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/FeaturesGetValuesBatchError.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: Other
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/FeaturesGetValuesBatchError.cs
    startLine: 225
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>The other object</p>\n"
  example: []
  syntax:
    content: 'public sealed class Other : FeaturesGetValuesBatchError'
    content.vb: >-
      Public NotInheritable Class Other
          Inherits FeaturesGetValuesBatchError
  inheritance:
  - System.Object
  - Dropbox.Api.Team.FeaturesGetValuesBatchError
  inheritedMembers:
  - Dropbox.Api.Team.FeaturesGetValuesBatchError.IsEmptyFeaturesList
  - Dropbox.Api.Team.FeaturesGetValuesBatchError.AsEmptyFeaturesList
  - Dropbox.Api.Team.FeaturesGetValuesBatchError.IsOther
  - Dropbox.Api.Team.FeaturesGetValuesBatchError.AsOther
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchError.Other.Instance
  commentId: F:Dropbox.Api.Team.FeaturesGetValuesBatchError.Other.Instance
  id: Instance
  parent: Dropbox.Api.Team.FeaturesGetValuesBatchError.Other
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: FeaturesGetValuesBatchError.Other.Instance
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchError.Other.Instance
  type: Field
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/FeaturesGetValuesBatchError.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: Instance
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/FeaturesGetValuesBatchError.cs
    startLine: 249
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>A singleton instance of Other</p>\n"
  example: []
  syntax:
    content: public static readonly FeaturesGetValuesBatchError.Other Instance
    return:
      type: Dropbox.Api.Team.FeaturesGetValuesBatchError.Other
    content.vb: Public Shared ReadOnly Instance As FeaturesGetValuesBatchError.Other
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: Dropbox.Api.Team
  commentId: N:Dropbox.Api.Team
  name: Dropbox.Api.Team
  nameWithType: Dropbox.Api.Team
  fullName: Dropbox.Api.Team
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchError
  commentId: T:Dropbox.Api.Team.FeaturesGetValuesBatchError
  parent: Dropbox.Api.Team
  name: FeaturesGetValuesBatchError
  nameWithType: FeaturesGetValuesBatchError
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchError
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchError.IsEmptyFeaturesList
  commentId: P:Dropbox.Api.Team.FeaturesGetValuesBatchError.IsEmptyFeaturesList
  parent: Dropbox.Api.Team.FeaturesGetValuesBatchError
  name: IsEmptyFeaturesList
  nameWithType: FeaturesGetValuesBatchError.IsEmptyFeaturesList
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchError.IsEmptyFeaturesList
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchError.AsEmptyFeaturesList
  commentId: P:Dropbox.Api.Team.FeaturesGetValuesBatchError.AsEmptyFeaturesList
  parent: Dropbox.Api.Team.FeaturesGetValuesBatchError
  name: AsEmptyFeaturesList
  nameWithType: FeaturesGetValuesBatchError.AsEmptyFeaturesList
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchError.AsEmptyFeaturesList
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchError.IsOther
  commentId: P:Dropbox.Api.Team.FeaturesGetValuesBatchError.IsOther
  parent: Dropbox.Api.Team.FeaturesGetValuesBatchError
  name: IsOther
  nameWithType: FeaturesGetValuesBatchError.IsOther
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchError.IsOther
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchError.AsOther
  commentId: P:Dropbox.Api.Team.FeaturesGetValuesBatchError.AsOther
  parent: Dropbox.Api.Team.FeaturesGetValuesBatchError
  name: AsOther
  nameWithType: FeaturesGetValuesBatchError.AsOther
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchError.AsOther
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchError.Other
  commentId: T:Dropbox.Api.Team.FeaturesGetValuesBatchError.Other
  parent: Dropbox.Api.Team
  name: FeaturesGetValuesBatchError.Other
  nameWithType: FeaturesGetValuesBatchError.Other
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchError.Other
