### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.DropboxClientConfig
  commentId: T:Dropbox.Api.DropboxClientConfig
  id: DropboxClientConfig
  parent: Dropbox.Api
  children:
  - Dropbox.Api.DropboxClientConfig.#ctor
  - Dropbox.Api.DropboxClientConfig.#ctor(System.String)
  - Dropbox.Api.DropboxClientConfig.#ctor(System.String,System.Int32)
  - Dropbox.Api.DropboxClientConfig.HttpClient
  - Dropbox.Api.DropboxClientConfig.LongPollHttpClient
  - Dropbox.Api.DropboxClientConfig.MaxRetriesOnError
  - Dropbox.Api.DropboxClientConfig.UserAgent
  langs:
  - csharp
  - vb
  name: DropboxClientConfig
  nameWithType: DropboxClientConfig
  fullName: Dropbox.Api.DropboxClientConfig
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/DropboxClientConfig.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: DropboxClientConfig
    path: dropbox-sdk-dotnet/Dropbox.Api/DropboxClientConfig.cs
    startLine: 13
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api
  summary: "\nThe class which contains all configurations for Dropbox client.\n"
  example: []
  syntax:
    content: public sealed class DropboxClientConfig
    content.vb: Public NotInheritable Class DropboxClientConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Dropbox.Api.DropboxClientConfig.#ctor
  commentId: M:Dropbox.Api.DropboxClientConfig.#ctor
  id: '#ctor'
  parent: Dropbox.Api.DropboxClientConfig
  langs:
  - csharp
  - vb
  name: DropboxClientConfig()
  nameWithType: DropboxClientConfig.DropboxClientConfig()
  fullName: Dropbox.Api.DropboxClientConfig.DropboxClientConfig()
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/DropboxClientConfig.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/DropboxClientConfig.cs
    startLine: 18
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api
  summary: "\nInitializes a new instance of the <xref href=\"Dropbox.Api.DropboxClientConfig\" data-throw-if-not-resolved=\"false\"></xref> class.\n"
  example: []
  syntax:
    content: public DropboxClientConfig()
    content.vb: Public Sub New
  overload: Dropbox.Api.DropboxClientConfig.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.DropboxClientConfig.#ctor(System.String)
  commentId: M:Dropbox.Api.DropboxClientConfig.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Dropbox.Api.DropboxClientConfig
  langs:
  - csharp
  - vb
  name: DropboxClientConfig(String)
  nameWithType: DropboxClientConfig.DropboxClientConfig(String)
  fullName: Dropbox.Api.DropboxClientConfig.DropboxClientConfig(System.String)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/DropboxClientConfig.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/DropboxClientConfig.cs
    startLine: 27
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api
  summary: "\nInitializes a new instance of the <xref href=\"Dropbox.Api.DropboxClientConfig\" data-throw-if-not-resolved=\"false\"></xref> class.\n"
  example: []
  syntax:
    content: public DropboxClientConfig(string userAgent)
    parameters:
    - id: userAgent
      type: System.String
      description: The user agent to use when making requests.
    content.vb: Public Sub New(userAgent As String)
  overload: Dropbox.Api.DropboxClientConfig.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.DropboxClientConfig.#ctor(System.String,System.Int32)
  commentId: M:Dropbox.Api.DropboxClientConfig.#ctor(System.String,System.Int32)
  id: '#ctor(System.String,System.Int32)'
  parent: Dropbox.Api.DropboxClientConfig
  langs:
  - csharp
  - vb
  name: DropboxClientConfig(String, Int32)
  nameWithType: DropboxClientConfig.DropboxClientConfig(String, Int32)
  fullName: Dropbox.Api.DropboxClientConfig.DropboxClientConfig(System.String, System.Int32)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/DropboxClientConfig.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/DropboxClientConfig.cs
    startLine: 37
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api
  summary: "\nInitializes a new instance of the <xref href=\"Dropbox.Api.DropboxClientConfig\" data-throw-if-not-resolved=\"false\"></xref> class.\n"
  example: []
  syntax:
    content: public DropboxClientConfig(string userAgent, int maxRetriesOnError)
    parameters:
    - id: userAgent
      type: System.String
      description: The user agent to use when making requests.
    - id: maxRetriesOnError
      type: System.Int32
      description: The max number retries on error.
    content.vb: Public Sub New(userAgent As String, maxRetriesOnError As Integer)
  overload: Dropbox.Api.DropboxClientConfig.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.DropboxClientConfig.MaxRetriesOnError
  commentId: P:Dropbox.Api.DropboxClientConfig.MaxRetriesOnError
  id: MaxRetriesOnError
  parent: Dropbox.Api.DropboxClientConfig
  langs:
  - csharp
  - vb
  name: MaxRetriesOnError
  nameWithType: DropboxClientConfig.MaxRetriesOnError
  fullName: Dropbox.Api.DropboxClientConfig.MaxRetriesOnError
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/DropboxClientConfig.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: MaxRetriesOnError
    path: dropbox-sdk-dotnet/Dropbox.Api/DropboxClientConfig.cs
    startLine: 46
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api
  summary: "\nGets or sets the max number retries on error. Default value is 4.\n"
  example: []
  syntax:
    content: public int MaxRetriesOnError { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MaxRetriesOnError As Integer
  overload: Dropbox.Api.DropboxClientConfig.MaxRetriesOnError*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Dropbox.Api.DropboxClientConfig.UserAgent
  commentId: P:Dropbox.Api.DropboxClientConfig.UserAgent
  id: UserAgent
  parent: Dropbox.Api.DropboxClientConfig
  langs:
  - csharp
  - vb
  name: UserAgent
  nameWithType: DropboxClientConfig.UserAgent
  fullName: Dropbox.Api.DropboxClientConfig.UserAgent
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/DropboxClientConfig.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: UserAgent
    path: dropbox-sdk-dotnet/Dropbox.Api/DropboxClientConfig.cs
    startLine: 56
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api
  summary: "\nGets or sets the user agent to use when making requests.\n"
  remarks: "\nThis value helps Dropbox to identify requests coming from your application.\nWe recommend that you use the format <code>&quot;AppName/Version&quot;</code>; if a value is supplied, the string\n<code>&quot;/OfficialDropboxDotNetV2SDK/__version__&quot;</code> is appended to the user agent.\n"
  example: []
  syntax:
    content: public string UserAgent { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property UserAgent As String
  overload: Dropbox.Api.DropboxClientConfig.UserAgent*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Dropbox.Api.DropboxClientConfig.HttpClient
  commentId: P:Dropbox.Api.DropboxClientConfig.HttpClient
  id: HttpClient
  parent: Dropbox.Api.DropboxClientConfig
  langs:
  - csharp
  - vb
  name: HttpClient
  nameWithType: DropboxClientConfig.HttpClient
  fullName: Dropbox.Api.DropboxClientConfig.HttpClient
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/DropboxClientConfig.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: HttpClient
    path: dropbox-sdk-dotnet/Dropbox.Api/DropboxClientConfig.cs
    startLine: 61
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api
  summary: "\nGets or sets the custom http client. If not set, a default http client will be created.\n"
  example: []
  syntax:
    content: public HttpClient HttpClient { get; set; }
    parameters: []
    return:
      type: HttpClient
    content.vb: Public Property HttpClient As HttpClient
  overload: Dropbox.Api.DropboxClientConfig.HttpClient*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Dropbox.Api.DropboxClientConfig.LongPollHttpClient
  commentId: P:Dropbox.Api.DropboxClientConfig.LongPollHttpClient
  id: LongPollHttpClient
  parent: Dropbox.Api.DropboxClientConfig
  langs:
  - csharp
  - vb
  name: LongPollHttpClient
  nameWithType: DropboxClientConfig.LongPollHttpClient
  fullName: Dropbox.Api.DropboxClientConfig.LongPollHttpClient
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/DropboxClientConfig.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: LongPollHttpClient
    path: dropbox-sdk-dotnet/Dropbox.Api/DropboxClientConfig.cs
    startLine: 67
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api
  summary: "\nGets or sets the custom http client for long poll request. If not set, a default\nhttp client with a longer timeout (480 seconds) will be created.\n"
  example: []
  syntax:
    content: public HttpClient LongPollHttpClient { get; set; }
    parameters: []
    return:
      type: HttpClient
    content.vb: Public Property LongPollHttpClient As HttpClient
  overload: Dropbox.Api.DropboxClientConfig.LongPollHttpClient*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Dropbox.Api
  commentId: N:Dropbox.Api
  name: Dropbox.Api
  nameWithType: Dropbox.Api
  fullName: Dropbox.Api
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Dropbox.Api.DropboxClientConfig
  commentId: T:Dropbox.Api.DropboxClientConfig
  parent: Dropbox.Api
  name: DropboxClientConfig
  nameWithType: DropboxClientConfig
  fullName: Dropbox.Api.DropboxClientConfig
- uid: Dropbox.Api.DropboxClientConfig.#ctor*
  commentId: Overload:Dropbox.Api.DropboxClientConfig.#ctor
  name: DropboxClientConfig
  nameWithType: DropboxClientConfig.DropboxClientConfig
  fullName: Dropbox.Api.DropboxClientConfig.DropboxClientConfig
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Dropbox.Api.DropboxClientConfig.MaxRetriesOnError*
  commentId: Overload:Dropbox.Api.DropboxClientConfig.MaxRetriesOnError
  name: MaxRetriesOnError
  nameWithType: DropboxClientConfig.MaxRetriesOnError
  fullName: Dropbox.Api.DropboxClientConfig.MaxRetriesOnError
- uid: Dropbox.Api.DropboxClientConfig.UserAgent*
  commentId: Overload:Dropbox.Api.DropboxClientConfig.UserAgent
  name: UserAgent
  nameWithType: DropboxClientConfig.UserAgent
  fullName: Dropbox.Api.DropboxClientConfig.UserAgent
- uid: Dropbox.Api.DropboxClientConfig.HttpClient*
  commentId: Overload:Dropbox.Api.DropboxClientConfig.HttpClient
  name: HttpClient
  nameWithType: DropboxClientConfig.HttpClient
  fullName: Dropbox.Api.DropboxClientConfig.HttpClient
- uid: HttpClient
  isExternal: true
  name: HttpClient
  nameWithType: HttpClient
  fullName: HttpClient
- uid: Dropbox.Api.DropboxClientConfig.LongPollHttpClient*
  commentId: Overload:Dropbox.Api.DropboxClientConfig.LongPollHttpClient
  name: LongPollHttpClient
  nameWithType: DropboxClientConfig.LongPollHttpClient
  fullName: Dropbox.Api.DropboxClientConfig.LongPollHttpClient
