### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Files.SyncSettingsError.Path
  commentId: T:Dropbox.Api.Files.SyncSettingsError.Path
  id: SyncSettingsError.Path
  parent: Dropbox.Api.Files
  children:
  - Dropbox.Api.Files.SyncSettingsError.Path.#ctor(Dropbox.Api.Files.LookupError)
  - Dropbox.Api.Files.SyncSettingsError.Path.Value
  langs:
  - csharp
  - vb
  name: SyncSettingsError.Path
  nameWithType: SyncSettingsError.Path
  fullName: Dropbox.Api.Files.SyncSettingsError.Path
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Files/SyncSettingsError.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: Path
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Files/SyncSettingsError.cs
    startLine: 214
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Files
  summary: "\n<p>The path object</p>\n"
  example: []
  syntax:
    content: 'public sealed class Path : SyncSettingsError'
    content.vb: >-
      Public NotInheritable Class Path
          Inherits SyncSettingsError
  inheritance:
  - System.Object
  - Dropbox.Api.Files.SyncSettingsError
  inheritedMembers:
  - Dropbox.Api.Files.SyncSettingsError.IsPath
  - Dropbox.Api.Files.SyncSettingsError.AsPath
  - Dropbox.Api.Files.SyncSettingsError.IsUnsupportedCombination
  - Dropbox.Api.Files.SyncSettingsError.AsUnsupportedCombination
  - Dropbox.Api.Files.SyncSettingsError.IsUnsupportedConfiguration
  - Dropbox.Api.Files.SyncSettingsError.AsUnsupportedConfiguration
  - Dropbox.Api.Files.SyncSettingsError.IsOther
  - Dropbox.Api.Files.SyncSettingsError.AsOther
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Dropbox.Api.Files.SyncSettingsError.Path.#ctor(Dropbox.Api.Files.LookupError)
  commentId: M:Dropbox.Api.Files.SyncSettingsError.Path.#ctor(Dropbox.Api.Files.LookupError)
  id: '#ctor(Dropbox.Api.Files.LookupError)'
  parent: Dropbox.Api.Files.SyncSettingsError.Path
  langs:
  - csharp
  - vb
  name: Path(LookupError)
  nameWithType: SyncSettingsError.Path.Path(LookupError)
  fullName: Dropbox.Api.Files.SyncSettingsError.Path.Path(Dropbox.Api.Files.LookupError)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Files/SyncSettingsError.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Files/SyncSettingsError.cs
    startLine: 232
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Files
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.Files.SyncSettingsError.Path\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  example: []
  syntax:
    content: public Path(LookupError value)
    parameters:
    - id: value
      type: Dropbox.Api.Files.LookupError
      description: The value
    content.vb: Public Sub New(value As LookupError)
  overload: Dropbox.Api.Files.SyncSettingsError.Path.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.Files.SyncSettingsError.Path.Value
  commentId: P:Dropbox.Api.Files.SyncSettingsError.Path.Value
  id: Value
  parent: Dropbox.Api.Files.SyncSettingsError.Path
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: SyncSettingsError.Path.Value
  fullName: Dropbox.Api.Files.SyncSettingsError.Path.Value
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Files/SyncSettingsError.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: Value
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Files/SyncSettingsError.cs
    startLine: 246
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Files
  summary: "\n<p>Gets the value of this instance.</p>\n"
  example: []
  syntax:
    content: public LookupError Value { get; }
    parameters: []
    return:
      type: Dropbox.Api.Files.LookupError
    content.vb: Public ReadOnly Property Value As LookupError
  overload: Dropbox.Api.Files.SyncSettingsError.Path.Value*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Dropbox.Api.Files
  commentId: N:Dropbox.Api.Files
  name: Dropbox.Api.Files
  nameWithType: Dropbox.Api.Files
  fullName: Dropbox.Api.Files
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.Files.SyncSettingsError
  commentId: T:Dropbox.Api.Files.SyncSettingsError
  parent: Dropbox.Api.Files
  name: SyncSettingsError
  nameWithType: SyncSettingsError
  fullName: Dropbox.Api.Files.SyncSettingsError
- uid: Dropbox.Api.Files.SyncSettingsError.IsPath
  commentId: P:Dropbox.Api.Files.SyncSettingsError.IsPath
  parent: Dropbox.Api.Files.SyncSettingsError
  name: IsPath
  nameWithType: SyncSettingsError.IsPath
  fullName: Dropbox.Api.Files.SyncSettingsError.IsPath
- uid: Dropbox.Api.Files.SyncSettingsError.AsPath
  commentId: P:Dropbox.Api.Files.SyncSettingsError.AsPath
  parent: Dropbox.Api.Files.SyncSettingsError
  name: AsPath
  nameWithType: SyncSettingsError.AsPath
  fullName: Dropbox.Api.Files.SyncSettingsError.AsPath
- uid: Dropbox.Api.Files.SyncSettingsError.IsUnsupportedCombination
  commentId: P:Dropbox.Api.Files.SyncSettingsError.IsUnsupportedCombination
  parent: Dropbox.Api.Files.SyncSettingsError
  name: IsUnsupportedCombination
  nameWithType: SyncSettingsError.IsUnsupportedCombination
  fullName: Dropbox.Api.Files.SyncSettingsError.IsUnsupportedCombination
- uid: Dropbox.Api.Files.SyncSettingsError.AsUnsupportedCombination
  commentId: P:Dropbox.Api.Files.SyncSettingsError.AsUnsupportedCombination
  parent: Dropbox.Api.Files.SyncSettingsError
  name: AsUnsupportedCombination
  nameWithType: SyncSettingsError.AsUnsupportedCombination
  fullName: Dropbox.Api.Files.SyncSettingsError.AsUnsupportedCombination
- uid: Dropbox.Api.Files.SyncSettingsError.IsUnsupportedConfiguration
  commentId: P:Dropbox.Api.Files.SyncSettingsError.IsUnsupportedConfiguration
  parent: Dropbox.Api.Files.SyncSettingsError
  name: IsUnsupportedConfiguration
  nameWithType: SyncSettingsError.IsUnsupportedConfiguration
  fullName: Dropbox.Api.Files.SyncSettingsError.IsUnsupportedConfiguration
- uid: Dropbox.Api.Files.SyncSettingsError.AsUnsupportedConfiguration
  commentId: P:Dropbox.Api.Files.SyncSettingsError.AsUnsupportedConfiguration
  parent: Dropbox.Api.Files.SyncSettingsError
  name: AsUnsupportedConfiguration
  nameWithType: SyncSettingsError.AsUnsupportedConfiguration
  fullName: Dropbox.Api.Files.SyncSettingsError.AsUnsupportedConfiguration
- uid: Dropbox.Api.Files.SyncSettingsError.IsOther
  commentId: P:Dropbox.Api.Files.SyncSettingsError.IsOther
  parent: Dropbox.Api.Files.SyncSettingsError
  name: IsOther
  nameWithType: SyncSettingsError.IsOther
  fullName: Dropbox.Api.Files.SyncSettingsError.IsOther
- uid: Dropbox.Api.Files.SyncSettingsError.AsOther
  commentId: P:Dropbox.Api.Files.SyncSettingsError.AsOther
  parent: Dropbox.Api.Files.SyncSettingsError
  name: AsOther
  nameWithType: SyncSettingsError.AsOther
  fullName: Dropbox.Api.Files.SyncSettingsError.AsOther
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Dropbox.Api.Files.SyncSettingsError.Path
  commentId: T:Dropbox.Api.Files.SyncSettingsError.Path
  parent: Dropbox.Api.Files
  name: SyncSettingsError.Path
  nameWithType: SyncSettingsError.Path
  fullName: Dropbox.Api.Files.SyncSettingsError.Path
- uid: Dropbox.Api.Files.SyncSettingsError.Path.#ctor*
  commentId: Overload:Dropbox.Api.Files.SyncSettingsError.Path.#ctor
  name: Path
  nameWithType: SyncSettingsError.Path.Path
  fullName: Dropbox.Api.Files.SyncSettingsError.Path.Path
- uid: Dropbox.Api.Files.LookupError
  commentId: T:Dropbox.Api.Files.LookupError
  parent: Dropbox.Api.Files
  name: LookupError
  nameWithType: LookupError
  fullName: Dropbox.Api.Files.LookupError
- uid: Dropbox.Api.Files.SyncSettingsError.Path.Value*
  commentId: Overload:Dropbox.Api.Files.SyncSettingsError.Path.Value
  name: Value
  nameWithType: SyncSettingsError.Path.Value
  fullName: Dropbox.Api.Files.SyncSettingsError.Path.Value
