### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchArg
  commentId: T:Dropbox.Api.Team.FeaturesGetValuesBatchArg
  id: FeaturesGetValuesBatchArg
  parent: Dropbox.Api.Team
  children:
  - Dropbox.Api.Team.FeaturesGetValuesBatchArg.#ctor(System.Collections.Generic.IEnumerable{Dropbox.Api.Team.Feature})
  - Dropbox.Api.Team.FeaturesGetValuesBatchArg.Features
  langs:
  - csharp
  - vb
  name: FeaturesGetValuesBatchArg
  nameWithType: FeaturesGetValuesBatchArg
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchArg
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/FeaturesGetValuesBatchArg.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: FeaturesGetValuesBatchArg
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/FeaturesGetValuesBatchArg.cs
    startLine: 15
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>The features get values batch arg object</p>\n"
  example: []
  syntax:
    content: public class FeaturesGetValuesBatchArg
    content.vb: Public Class FeaturesGetValuesBatchArg
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchArg.#ctor(System.Collections.Generic.IEnumerable{Dropbox.Api.Team.Feature})
  commentId: M:Dropbox.Api.Team.FeaturesGetValuesBatchArg.#ctor(System.Collections.Generic.IEnumerable{Dropbox.Api.Team.Feature})
  id: '#ctor(System.Collections.Generic.IEnumerable{Dropbox.Api.Team.Feature})'
  parent: Dropbox.Api.Team.FeaturesGetValuesBatchArg
  langs:
  - csharp
  - vb
  name: FeaturesGetValuesBatchArg(IEnumerable<Feature>)
  nameWithType: FeaturesGetValuesBatchArg.FeaturesGetValuesBatchArg(IEnumerable<Feature>)
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchArg.FeaturesGetValuesBatchArg(System.Collections.Generic.IEnumerable<Dropbox.Api.Team.Feature>)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/FeaturesGetValuesBatchArg.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/FeaturesGetValuesBatchArg.cs
    startLine: 35
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.Team.FeaturesGetValuesBatchArg\" data-throw-if-not-resolved=\"false\"></xref>\nclass.</p>\n"
  example: []
  syntax:
    content: public FeaturesGetValuesBatchArg(IEnumerable<Feature> features)
    parameters:
    - id: features
      type: System.Collections.Generic.IEnumerable{Dropbox.Api.Team.Feature}
      description: >-
        A list of features in <xref href="Dropbox.Api.Team.Feature" data-throw-if-not-resolved="false"></xref>. If the list is

        empty, this route will return <xref href="Dropbox.Api.Team.FeaturesGetValuesBatchError" data-throw-if-not-resolved="false"></xref>.
    content.vb: Public Sub New(features As IEnumerable(Of Feature))
  overload: Dropbox.Api.Team.FeaturesGetValuesBatchArg.#ctor*
  nameWithType.vb: FeaturesGetValuesBatchArg.FeaturesGetValuesBatchArg(IEnumerable(Of Feature))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Dropbox.Api.Team.FeaturesGetValuesBatchArg.FeaturesGetValuesBatchArg(System.Collections.Generic.IEnumerable(Of Dropbox.Api.Team.Feature))
  name.vb: FeaturesGetValuesBatchArg(IEnumerable(Of Feature))
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchArg.Features
  commentId: P:Dropbox.Api.Team.FeaturesGetValuesBatchArg.Features
  id: Features
  parent: Dropbox.Api.Team.FeaturesGetValuesBatchArg
  langs:
  - csharp
  - vb
  name: Features
  nameWithType: FeaturesGetValuesBatchArg.Features
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchArg.Features
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/FeaturesGetValuesBatchArg.cs
      branch: doc_fx_integration
      repo: https://github.com/dropbox/dropbox-sdk-dotnet.git
    id: Features
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/FeaturesGetValuesBatchArg.cs
    startLine: 62
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>A list of features in <xref href=\"Dropbox.Api.Team.Feature\" data-throw-if-not-resolved=\"false\"></xref>. If the list is empty, this\nroute will return <xref href=\"Dropbox.Api.Team.FeaturesGetValuesBatchError\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n"
  example: []
  syntax:
    content: public IList<Feature> Features { get; protected set; }
    parameters: []
    return:
      type: System.Collections.Generic.IList{Dropbox.Api.Team.Feature}
    content.vb: Public Property Features As IList(Of Feature)
  overload: Dropbox.Api.Team.FeaturesGetValuesBatchArg.Features*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
references:
- uid: Dropbox.Api.Team
  commentId: N:Dropbox.Api.Team
  name: Dropbox.Api.Team
  nameWithType: Dropbox.Api.Team
  fullName: Dropbox.Api.Team
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchArg
  commentId: T:Dropbox.Api.Team.FeaturesGetValuesBatchArg
  parent: Dropbox.Api.Team
  name: FeaturesGetValuesBatchArg
  nameWithType: FeaturesGetValuesBatchArg
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchArg
- uid: Dropbox.Api.Team.Feature
  commentId: T:Dropbox.Api.Team.Feature
  parent: Dropbox.Api.Team
  name: Feature
  nameWithType: Feature
  fullName: Dropbox.Api.Team.Feature
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchError
  commentId: T:Dropbox.Api.Team.FeaturesGetValuesBatchError
  parent: Dropbox.Api.Team
  name: FeaturesGetValuesBatchError
  nameWithType: FeaturesGetValuesBatchError
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchError
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchArg.#ctor*
  commentId: Overload:Dropbox.Api.Team.FeaturesGetValuesBatchArg.#ctor
  name: FeaturesGetValuesBatchArg
  nameWithType: FeaturesGetValuesBatchArg.FeaturesGetValuesBatchArg
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchArg.FeaturesGetValuesBatchArg
- uid: System.Collections.Generic.IEnumerable{Dropbox.Api.Team.Feature}
  commentId: T:System.Collections.Generic.IEnumerable{Dropbox.Api.Team.Feature}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  name: IEnumerable<Feature>
  nameWithType: IEnumerable<Feature>
  fullName: System.Collections.Generic.IEnumerable<Dropbox.Api.Team.Feature>
  nameWithType.vb: IEnumerable(Of Feature)
  fullName.vb: System.Collections.Generic.IEnumerable(Of Dropbox.Api.Team.Feature)
  name.vb: IEnumerable(Of Feature)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Dropbox.Api.Team.Feature
    name: Feature
    nameWithType: Feature
    fullName: Dropbox.Api.Team.Feature
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Dropbox.Api.Team.Feature
    name: Feature
    nameWithType: Feature
    fullName: Dropbox.Api.Team.Feature
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchArg.Features*
  commentId: Overload:Dropbox.Api.Team.FeaturesGetValuesBatchArg.Features
  name: Features
  nameWithType: FeaturesGetValuesBatchArg.Features
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchArg.Features
- uid: System.Collections.Generic.IList{Dropbox.Api.Team.Feature}
  commentId: T:System.Collections.Generic.IList{Dropbox.Api.Team.Feature}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<Feature>
  nameWithType: IList<Feature>
  fullName: System.Collections.Generic.IList<Dropbox.Api.Team.Feature>
  nameWithType.vb: IList(Of Feature)
  fullName.vb: System.Collections.Generic.IList(Of Dropbox.Api.Team.Feature)
  name.vb: IList(Of Feature)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Dropbox.Api.Team.Feature
    name: Feature
    nameWithType: Feature
    fullName: Dropbox.Api.Team.Feature
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Dropbox.Api.Team.Feature
    name: Feature
    nameWithType: Feature
    fullName: Dropbox.Api.Team.Feature
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  commentId: T:System.Collections.Generic.IList`1
  isExternal: true
  name: IList<T>
  nameWithType: IList<T>
  fullName: System.Collections.Generic.IList<T>
  nameWithType.vb: IList(Of T)
  fullName.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
