### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType
  commentId: T:Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType
  id: SharedLinkSettingsRemoveExpirationType
  parent: Dropbox.Api.TeamLog
  children:
  - Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.#ctor
  - Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.#ctor(System.String)
  - Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.Description
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsRemoveExpirationType
  nameWithType: SharedLinkSettingsRemoveExpirationType
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsRemoveExpirationType.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SharedLinkSettingsRemoveExpirationType
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsRemoveExpirationType.cs
    startLine: 15
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>The shared link settings remove expiration type object</p>\n"
  example: []
  syntax:
    content: 'public class SharedLinkSettingsRemoveExpirationType : object'
    content.vb: >-
      Public Class SharedLinkSettingsRemoveExpirationType
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.#ctor(System.String)
  commentId: M:Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsRemoveExpirationType(String)
  nameWithType: SharedLinkSettingsRemoveExpirationType.SharedLinkSettingsRemoveExpirationType(String)
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.SharedLinkSettingsRemoveExpirationType(System.String)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsRemoveExpirationType.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsRemoveExpirationType.cs
    startLine: 34
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  example: []
  syntax:
    content: public SharedLinkSettingsRemoveExpirationType(string description)
    parameters:
    - id: description
      type: System.String
      description: The description
    content.vb: Public Sub New(description As String)
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.#ctor
  commentId: M:Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.#ctor
  id: '#ctor'
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsRemoveExpirationType()
  nameWithType: SharedLinkSettingsRemoveExpirationType.SharedLinkSettingsRemoveExpirationType()
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.SharedLinkSettingsRemoveExpirationType()
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsRemoveExpirationType.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsRemoveExpirationType.cs
    startLine: 50
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  remarks: >-
    This is to construct an instance of the object when

    deserializing.
  example: []
  syntax:
    content: public SharedLinkSettingsRemoveExpirationType()
    content.vb: Public Sub New
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.Description
  commentId: P:Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.Description
  id: Description
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType
  langs:
  - csharp
  - vb
  name: Description
  nameWithType: SharedLinkSettingsRemoveExpirationType.Description
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.Description
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsRemoveExpirationType.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Description
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsRemoveExpirationType.cs
    startLine: 59
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Gets the description of the shared link settings remove expiration\ntype</p>\n"
  example: []
  syntax:
    content: public string Description { get; protected set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Description As String
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.Description*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
references:
- uid: Dropbox.Api.TeamLog
  commentId: N:Dropbox.Api.TeamLog
  name: Dropbox.Api.TeamLog
  nameWithType: Dropbox.Api.TeamLog
  fullName: Dropbox.Api.TeamLog
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType
  commentId: T:Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType
  parent: Dropbox.Api.TeamLog
  name: SharedLinkSettingsRemoveExpirationType
  nameWithType: SharedLinkSettingsRemoveExpirationType
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.#ctor*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.#ctor
  name: SharedLinkSettingsRemoveExpirationType
  nameWithType: SharedLinkSettingsRemoveExpirationType.SharedLinkSettingsRemoveExpirationType
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.SharedLinkSettingsRemoveExpirationType
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.Description*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.Description
  name: Description
  nameWithType: SharedLinkSettingsRemoveExpirationType.Description
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsRemoveExpirationType.Description
shouldSkipMarkup: true
