### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.SharedLinkAccessDenied
  commentId: T:Dropbox.Api.Sharing.ModifySharedLinkSettingsError.SharedLinkAccessDenied
  id: ModifySharedLinkSettingsError.SharedLinkAccessDenied
  parent: Dropbox.Api.Sharing
  children:
  - Dropbox.Api.Sharing.ModifySharedLinkSettingsError.SharedLinkAccessDenied.Instance
  langs:
  - csharp
  - vb
  name: ModifySharedLinkSettingsError.SharedLinkAccessDenied
  nameWithType: ModifySharedLinkSettingsError.SharedLinkAccessDenied
  fullName: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.SharedLinkAccessDenied
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/ModifySharedLinkSettingsError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SharedLinkAccessDenied
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/ModifySharedLinkSettingsError.cs
    startLine: 517
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>The caller is not allowed to access this shared link.</p>\n"
  example: []
  syntax:
    content: 'public sealed class SharedLinkAccessDenied : ModifySharedLinkSettingsError'
    content.vb: >-
      Public NotInheritable Class SharedLinkAccessDenied
          Inherits ModifySharedLinkSettingsError
  inheritance:
  - System.Object
  - Dropbox.Api.Sharing.ModifySharedLinkSettingsError
  inheritedMembers:
  - Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsSettingsError
  - Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsSettingsError
  - Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsEmailNotVerified
  - Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsEmailNotVerified
  - Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsSharedLinkNotFound
  - Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsSharedLinkNotFound
  - Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsSharedLinkAccessDenied
  - Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsSharedLinkAccessDenied
  - Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsUnsupportedLinkType
  - Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsUnsupportedLinkType
  - Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsOther
  - Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsOther
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.SharedLinkAccessDenied.Instance
  commentId: F:Dropbox.Api.Sharing.ModifySharedLinkSettingsError.SharedLinkAccessDenied.Instance
  id: Instance
  parent: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.SharedLinkAccessDenied
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: ModifySharedLinkSettingsError.SharedLinkAccessDenied.Instance
  fullName: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.SharedLinkAccessDenied.Instance
  type: Field
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/ModifySharedLinkSettingsError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Instance
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/ModifySharedLinkSettingsError.cs
    startLine: 542
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>A singleton instance of SharedLinkAccessDenied</p>\n"
  example: []
  syntax:
    content: public static readonly ModifySharedLinkSettingsError.SharedLinkAccessDenied Instance
    return:
      type: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.SharedLinkAccessDenied
    content.vb: Public Shared ReadOnly Instance As ModifySharedLinkSettingsError.SharedLinkAccessDenied
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: Dropbox.Api.Sharing
  commentId: N:Dropbox.Api.Sharing
  name: Dropbox.Api.Sharing
  nameWithType: Dropbox.Api.Sharing
  fullName: Dropbox.Api.Sharing
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.Sharing.ModifySharedLinkSettingsError
  commentId: T:Dropbox.Api.Sharing.ModifySharedLinkSettingsError
  parent: Dropbox.Api.Sharing
  name: ModifySharedLinkSettingsError
  nameWithType: ModifySharedLinkSettingsError
  fullName: Dropbox.Api.Sharing.ModifySharedLinkSettingsError
- uid: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsSettingsError
  commentId: P:Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsSettingsError
  parent: Dropbox.Api.Sharing.ModifySharedLinkSettingsError
  name: IsSettingsError
  nameWithType: ModifySharedLinkSettingsError.IsSettingsError
  fullName: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsSettingsError
- uid: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsSettingsError
  commentId: P:Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsSettingsError
  parent: Dropbox.Api.Sharing.ModifySharedLinkSettingsError
  name: AsSettingsError
  nameWithType: ModifySharedLinkSettingsError.AsSettingsError
  fullName: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsSettingsError
- uid: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsEmailNotVerified
  commentId: P:Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsEmailNotVerified
  parent: Dropbox.Api.Sharing.ModifySharedLinkSettingsError
  name: IsEmailNotVerified
  nameWithType: ModifySharedLinkSettingsError.IsEmailNotVerified
  fullName: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsEmailNotVerified
- uid: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsEmailNotVerified
  commentId: P:Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsEmailNotVerified
  parent: Dropbox.Api.Sharing.ModifySharedLinkSettingsError
  name: AsEmailNotVerified
  nameWithType: ModifySharedLinkSettingsError.AsEmailNotVerified
  fullName: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsEmailNotVerified
- uid: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsSharedLinkNotFound
  commentId: P:Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsSharedLinkNotFound
  parent: Dropbox.Api.Sharing.ModifySharedLinkSettingsError
  name: IsSharedLinkNotFound
  nameWithType: ModifySharedLinkSettingsError.IsSharedLinkNotFound
  fullName: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsSharedLinkNotFound
- uid: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsSharedLinkNotFound
  commentId: P:Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsSharedLinkNotFound
  parent: Dropbox.Api.Sharing.ModifySharedLinkSettingsError
  name: AsSharedLinkNotFound
  nameWithType: ModifySharedLinkSettingsError.AsSharedLinkNotFound
  fullName: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsSharedLinkNotFound
- uid: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsSharedLinkAccessDenied
  commentId: P:Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsSharedLinkAccessDenied
  parent: Dropbox.Api.Sharing.ModifySharedLinkSettingsError
  name: IsSharedLinkAccessDenied
  nameWithType: ModifySharedLinkSettingsError.IsSharedLinkAccessDenied
  fullName: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsSharedLinkAccessDenied
- uid: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsSharedLinkAccessDenied
  commentId: P:Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsSharedLinkAccessDenied
  parent: Dropbox.Api.Sharing.ModifySharedLinkSettingsError
  name: AsSharedLinkAccessDenied
  nameWithType: ModifySharedLinkSettingsError.AsSharedLinkAccessDenied
  fullName: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsSharedLinkAccessDenied
- uid: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsUnsupportedLinkType
  commentId: P:Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsUnsupportedLinkType
  parent: Dropbox.Api.Sharing.ModifySharedLinkSettingsError
  name: IsUnsupportedLinkType
  nameWithType: ModifySharedLinkSettingsError.IsUnsupportedLinkType
  fullName: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsUnsupportedLinkType
- uid: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsUnsupportedLinkType
  commentId: P:Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsUnsupportedLinkType
  parent: Dropbox.Api.Sharing.ModifySharedLinkSettingsError
  name: AsUnsupportedLinkType
  nameWithType: ModifySharedLinkSettingsError.AsUnsupportedLinkType
  fullName: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsUnsupportedLinkType
- uid: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsOther
  commentId: P:Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsOther
  parent: Dropbox.Api.Sharing.ModifySharedLinkSettingsError
  name: IsOther
  nameWithType: ModifySharedLinkSettingsError.IsOther
  fullName: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.IsOther
- uid: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsOther
  commentId: P:Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsOther
  parent: Dropbox.Api.Sharing.ModifySharedLinkSettingsError
  name: AsOther
  nameWithType: ModifySharedLinkSettingsError.AsOther
  fullName: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.AsOther
- uid: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.SharedLinkAccessDenied
  commentId: T:Dropbox.Api.Sharing.ModifySharedLinkSettingsError.SharedLinkAccessDenied
  parent: Dropbox.Api.Sharing
  name: ModifySharedLinkSettingsError.SharedLinkAccessDenied
  nameWithType: ModifySharedLinkSettingsError.SharedLinkAccessDenied
  fullName: Dropbox.Api.Sharing.ModifySharedLinkSettingsError.SharedLinkAccessDenied
shouldSkipMarkup: true
