### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails
  commentId: T:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails
  id: SharedLinkSettingsChangeAudienceDetails
  parent: Dropbox.Api.TeamLog
  children:
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.#ctor
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.#ctor(Dropbox.Api.Sharing.AccessLevel,Dropbox.Api.Sharing.LinkAudience,System.String,Dropbox.Api.Sharing.LinkAudience)
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.NewValue
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.PreviousValue
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedContentAccessLevel
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedContentLink
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsChangeAudienceDetails
  nameWithType: SharedLinkSettingsChangeAudienceDetails
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SharedLinkSettingsChangeAudienceDetails
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceDetails.cs
    startLine: 15
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Changed the audience of the shared link.</p>\n"
  example: []
  syntax:
    content: 'public class SharedLinkSettingsChangeAudienceDetails : object'
    content.vb: >-
      Public Class SharedLinkSettingsChangeAudienceDetails
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.#ctor(Dropbox.Api.Sharing.AccessLevel,Dropbox.Api.Sharing.LinkAudience,System.String,Dropbox.Api.Sharing.LinkAudience)
  commentId: M:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.#ctor(Dropbox.Api.Sharing.AccessLevel,Dropbox.Api.Sharing.LinkAudience,System.String,Dropbox.Api.Sharing.LinkAudience)
  id: '#ctor(Dropbox.Api.Sharing.AccessLevel,Dropbox.Api.Sharing.LinkAudience,System.String,Dropbox.Api.Sharing.LinkAudience)'
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsChangeAudienceDetails(AccessLevel, LinkAudience, String, LinkAudience)
  nameWithType: SharedLinkSettingsChangeAudienceDetails.SharedLinkSettingsChangeAudienceDetails(AccessLevel, LinkAudience, String, LinkAudience)
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedLinkSettingsChangeAudienceDetails(Dropbox.Api.Sharing.AccessLevel, Dropbox.Api.Sharing.LinkAudience, System.String, Dropbox.Api.Sharing.LinkAudience)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceDetails.cs
    startLine: 37
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  example: []
  syntax:
    content: public SharedLinkSettingsChangeAudienceDetails(AccessLevel sharedContentAccessLevel, LinkAudience newValue, string sharedContentLink = null, LinkAudience previousValue = null)
    parameters:
    - id: sharedContentAccessLevel
      type: Dropbox.Api.Sharing.AccessLevel
      description: Shared content access level.
    - id: newValue
      type: Dropbox.Api.Sharing.LinkAudience
      description: New link audience value.
    - id: sharedContentLink
      type: System.String
      description: Shared content link.
    - id: previousValue
      type: Dropbox.Api.Sharing.LinkAudience
      description: Previous link audience value.
    content.vb: Public Sub New(sharedContentAccessLevel As AccessLevel, newValue As LinkAudience, sharedContentLink As String = Nothing, previousValue As LinkAudience = Nothing)
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.#ctor
  commentId: M:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.#ctor
  id: '#ctor'
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsChangeAudienceDetails()
  nameWithType: SharedLinkSettingsChangeAudienceDetails.SharedLinkSettingsChangeAudienceDetails()
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedLinkSettingsChangeAudienceDetails()
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceDetails.cs
    startLine: 64
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  remarks: >-
    This is to construct an instance of the object when

    deserializing.
  example: []
  syntax:
    content: public SharedLinkSettingsChangeAudienceDetails()
    content.vb: Public Sub New
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedContentAccessLevel
  commentId: P:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedContentAccessLevel
  id: SharedContentAccessLevel
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails
  langs:
  - csharp
  - vb
  name: SharedContentAccessLevel
  nameWithType: SharedLinkSettingsChangeAudienceDetails.SharedContentAccessLevel
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedContentAccessLevel
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SharedContentAccessLevel
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceDetails.cs
    startLine: 72
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Shared content access level.</p>\n"
  example: []
  syntax:
    content: public AccessLevel SharedContentAccessLevel { get; protected set; }
    parameters: []
    return:
      type: Dropbox.Api.Sharing.AccessLevel
    content.vb: Public Property SharedContentAccessLevel As AccessLevel
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedContentAccessLevel*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.NewValue
  commentId: P:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.NewValue
  id: NewValue
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails
  langs:
  - csharp
  - vb
  name: NewValue
  nameWithType: SharedLinkSettingsChangeAudienceDetails.NewValue
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.NewValue
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: NewValue
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceDetails.cs
    startLine: 77
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>New link audience value.</p>\n"
  example: []
  syntax:
    content: public LinkAudience NewValue { get; protected set; }
    parameters: []
    return:
      type: Dropbox.Api.Sharing.LinkAudience
    content.vb: Public Property NewValue As LinkAudience
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.NewValue*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedContentLink
  commentId: P:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedContentLink
  id: SharedContentLink
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails
  langs:
  - csharp
  - vb
  name: SharedContentLink
  nameWithType: SharedLinkSettingsChangeAudienceDetails.SharedContentLink
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedContentLink
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SharedContentLink
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceDetails.cs
    startLine: 82
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Shared content link.</p>\n"
  example: []
  syntax:
    content: public string SharedContentLink { get; protected set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property SharedContentLink As String
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedContentLink*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.PreviousValue
  commentId: P:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.PreviousValue
  id: PreviousValue
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails
  langs:
  - csharp
  - vb
  name: PreviousValue
  nameWithType: SharedLinkSettingsChangeAudienceDetails.PreviousValue
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.PreviousValue
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: PreviousValue
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceDetails.cs
    startLine: 87
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Previous link audience value.</p>\n"
  example: []
  syntax:
    content: public LinkAudience PreviousValue { get; protected set; }
    parameters: []
    return:
      type: Dropbox.Api.Sharing.LinkAudience
    content.vb: Public Property PreviousValue As LinkAudience
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.PreviousValue*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
references:
- uid: Dropbox.Api.TeamLog
  commentId: N:Dropbox.Api.TeamLog
  name: Dropbox.Api.TeamLog
  nameWithType: Dropbox.Api.TeamLog
  fullName: Dropbox.Api.TeamLog
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails
  commentId: T:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails
  parent: Dropbox.Api.TeamLog
  name: SharedLinkSettingsChangeAudienceDetails
  nameWithType: SharedLinkSettingsChangeAudienceDetails
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.#ctor*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.#ctor
  name: SharedLinkSettingsChangeAudienceDetails
  nameWithType: SharedLinkSettingsChangeAudienceDetails.SharedLinkSettingsChangeAudienceDetails
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedLinkSettingsChangeAudienceDetails
- uid: Dropbox.Api.Sharing.AccessLevel
  commentId: T:Dropbox.Api.Sharing.AccessLevel
  parent: Dropbox.Api.Sharing
  name: AccessLevel
  nameWithType: AccessLevel
  fullName: Dropbox.Api.Sharing.AccessLevel
- uid: Dropbox.Api.Sharing.LinkAudience
  commentId: T:Dropbox.Api.Sharing.LinkAudience
  parent: Dropbox.Api.Sharing
  name: LinkAudience
  nameWithType: LinkAudience
  fullName: Dropbox.Api.Sharing.LinkAudience
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Dropbox.Api.Sharing
  commentId: N:Dropbox.Api.Sharing
  name: Dropbox.Api.Sharing
  nameWithType: Dropbox.Api.Sharing
  fullName: Dropbox.Api.Sharing
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedContentAccessLevel*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedContentAccessLevel
  name: SharedContentAccessLevel
  nameWithType: SharedLinkSettingsChangeAudienceDetails.SharedContentAccessLevel
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedContentAccessLevel
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.NewValue*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.NewValue
  name: NewValue
  nameWithType: SharedLinkSettingsChangeAudienceDetails.NewValue
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.NewValue
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedContentLink*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedContentLink
  name: SharedContentLink
  nameWithType: SharedLinkSettingsChangeAudienceDetails.SharedContentLink
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.SharedContentLink
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.PreviousValue*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.PreviousValue
  name: PreviousValue
  nameWithType: SharedLinkSettingsChangeAudienceDetails.PreviousValue
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceDetails.PreviousValue
shouldSkipMarkup: true
