### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError
  commentId: T:Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError
  id: TeamFolderCreateError.SyncSettingsError
  parent: Dropbox.Api.Team
  children:
  - Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError.#ctor(Dropbox.Api.Files.SyncSettingsError)
  - Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError.Value
  langs:
  - csharp
  - vb
  name: TeamFolderCreateError.SyncSettingsError
  nameWithType: TeamFolderCreateError.SyncSettingsError
  fullName: Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderCreateError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SyncSettingsError
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderCreateError.cs
    startLine: 456
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>An error occurred setting the sync settings.</p>\n"
  example: []
  syntax:
    content: 'public sealed class SyncSettingsError : TeamFolderCreateError'
    content.vb: >-
      Public NotInheritable Class SyncSettingsError
          Inherits TeamFolderCreateError
  inheritance:
  - System.Object
  - Dropbox.Api.Team.TeamFolderCreateError
  inheritedMembers:
  - Dropbox.Api.Team.TeamFolderCreateError.IsInvalidFolderName
  - Dropbox.Api.Team.TeamFolderCreateError.AsInvalidFolderName
  - Dropbox.Api.Team.TeamFolderCreateError.IsFolderNameAlreadyUsed
  - Dropbox.Api.Team.TeamFolderCreateError.AsFolderNameAlreadyUsed
  - Dropbox.Api.Team.TeamFolderCreateError.IsFolderNameReserved
  - Dropbox.Api.Team.TeamFolderCreateError.AsFolderNameReserved
  - Dropbox.Api.Team.TeamFolderCreateError.IsSyncSettingsError
  - Dropbox.Api.Team.TeamFolderCreateError.AsSyncSettingsError
  - Dropbox.Api.Team.TeamFolderCreateError.IsOther
  - Dropbox.Api.Team.TeamFolderCreateError.AsOther
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError.#ctor(Dropbox.Api.Files.SyncSettingsError)
  commentId: M:Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError.#ctor(Dropbox.Api.Files.SyncSettingsError)
  id: '#ctor(Dropbox.Api.Files.SyncSettingsError)'
  parent: Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError
  langs:
  - csharp
  - vb
  name: SyncSettingsError(SyncSettingsError)
  nameWithType: TeamFolderCreateError.SyncSettingsError.SyncSettingsError(SyncSettingsError)
  fullName: Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError.SyncSettingsError(Dropbox.Api.Files.SyncSettingsError)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderCreateError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderCreateError.cs
    startLine: 475
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError\" data-throw-if-not-resolved=\"false\"></xref>\nclass.</p>\n"
  example: []
  syntax:
    content: public SyncSettingsError(SyncSettingsError value)
    parameters:
    - id: value
      type: Dropbox.Api.Files.SyncSettingsError
      description: The value
    content.vb: Public Sub New(value As SyncSettingsError)
  overload: Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError.Value
  commentId: P:Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError.Value
  id: Value
  parent: Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: TeamFolderCreateError.SyncSettingsError.Value
  fullName: Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError.Value
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderCreateError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Value
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderCreateError.cs
    startLine: 490
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>Gets the value of this instance.</p>\n"
  example: []
  syntax:
    content: public SyncSettingsError Value { get; }
    parameters: []
    return:
      type: Dropbox.Api.Files.SyncSettingsError
    content.vb: Public ReadOnly Property Value As SyncSettingsError
  overload: Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError.Value*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Dropbox.Api.Team
  commentId: N:Dropbox.Api.Team
  name: Dropbox.Api.Team
  nameWithType: Dropbox.Api.Team
  fullName: Dropbox.Api.Team
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.Team.TeamFolderCreateError
  commentId: T:Dropbox.Api.Team.TeamFolderCreateError
  parent: Dropbox.Api.Team
  name: TeamFolderCreateError
  nameWithType: TeamFolderCreateError
  fullName: Dropbox.Api.Team.TeamFolderCreateError
- uid: Dropbox.Api.Team.TeamFolderCreateError.IsInvalidFolderName
  commentId: P:Dropbox.Api.Team.TeamFolderCreateError.IsInvalidFolderName
  parent: Dropbox.Api.Team.TeamFolderCreateError
  name: IsInvalidFolderName
  nameWithType: TeamFolderCreateError.IsInvalidFolderName
  fullName: Dropbox.Api.Team.TeamFolderCreateError.IsInvalidFolderName
- uid: Dropbox.Api.Team.TeamFolderCreateError.AsInvalidFolderName
  commentId: P:Dropbox.Api.Team.TeamFolderCreateError.AsInvalidFolderName
  parent: Dropbox.Api.Team.TeamFolderCreateError
  name: AsInvalidFolderName
  nameWithType: TeamFolderCreateError.AsInvalidFolderName
  fullName: Dropbox.Api.Team.TeamFolderCreateError.AsInvalidFolderName
- uid: Dropbox.Api.Team.TeamFolderCreateError.IsFolderNameAlreadyUsed
  commentId: P:Dropbox.Api.Team.TeamFolderCreateError.IsFolderNameAlreadyUsed
  parent: Dropbox.Api.Team.TeamFolderCreateError
  name: IsFolderNameAlreadyUsed
  nameWithType: TeamFolderCreateError.IsFolderNameAlreadyUsed
  fullName: Dropbox.Api.Team.TeamFolderCreateError.IsFolderNameAlreadyUsed
- uid: Dropbox.Api.Team.TeamFolderCreateError.AsFolderNameAlreadyUsed
  commentId: P:Dropbox.Api.Team.TeamFolderCreateError.AsFolderNameAlreadyUsed
  parent: Dropbox.Api.Team.TeamFolderCreateError
  name: AsFolderNameAlreadyUsed
  nameWithType: TeamFolderCreateError.AsFolderNameAlreadyUsed
  fullName: Dropbox.Api.Team.TeamFolderCreateError.AsFolderNameAlreadyUsed
- uid: Dropbox.Api.Team.TeamFolderCreateError.IsFolderNameReserved
  commentId: P:Dropbox.Api.Team.TeamFolderCreateError.IsFolderNameReserved
  parent: Dropbox.Api.Team.TeamFolderCreateError
  name: IsFolderNameReserved
  nameWithType: TeamFolderCreateError.IsFolderNameReserved
  fullName: Dropbox.Api.Team.TeamFolderCreateError.IsFolderNameReserved
- uid: Dropbox.Api.Team.TeamFolderCreateError.AsFolderNameReserved
  commentId: P:Dropbox.Api.Team.TeamFolderCreateError.AsFolderNameReserved
  parent: Dropbox.Api.Team.TeamFolderCreateError
  name: AsFolderNameReserved
  nameWithType: TeamFolderCreateError.AsFolderNameReserved
  fullName: Dropbox.Api.Team.TeamFolderCreateError.AsFolderNameReserved
- uid: Dropbox.Api.Team.TeamFolderCreateError.IsSyncSettingsError
  commentId: P:Dropbox.Api.Team.TeamFolderCreateError.IsSyncSettingsError
  parent: Dropbox.Api.Team.TeamFolderCreateError
  name: IsSyncSettingsError
  nameWithType: TeamFolderCreateError.IsSyncSettingsError
  fullName: Dropbox.Api.Team.TeamFolderCreateError.IsSyncSettingsError
- uid: Dropbox.Api.Team.TeamFolderCreateError.AsSyncSettingsError
  commentId: P:Dropbox.Api.Team.TeamFolderCreateError.AsSyncSettingsError
  parent: Dropbox.Api.Team.TeamFolderCreateError
  name: AsSyncSettingsError
  nameWithType: TeamFolderCreateError.AsSyncSettingsError
  fullName: Dropbox.Api.Team.TeamFolderCreateError.AsSyncSettingsError
- uid: Dropbox.Api.Team.TeamFolderCreateError.IsOther
  commentId: P:Dropbox.Api.Team.TeamFolderCreateError.IsOther
  parent: Dropbox.Api.Team.TeamFolderCreateError
  name: IsOther
  nameWithType: TeamFolderCreateError.IsOther
  fullName: Dropbox.Api.Team.TeamFolderCreateError.IsOther
- uid: Dropbox.Api.Team.TeamFolderCreateError.AsOther
  commentId: P:Dropbox.Api.Team.TeamFolderCreateError.AsOther
  parent: Dropbox.Api.Team.TeamFolderCreateError
  name: AsOther
  nameWithType: TeamFolderCreateError.AsOther
  fullName: Dropbox.Api.Team.TeamFolderCreateError.AsOther
- uid: Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError
  commentId: T:Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError
  parent: Dropbox.Api.Team
  name: TeamFolderCreateError.SyncSettingsError
  nameWithType: TeamFolderCreateError.SyncSettingsError
  fullName: Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError
- uid: Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError.#ctor*
  commentId: Overload:Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError.#ctor
  name: SyncSettingsError
  nameWithType: TeamFolderCreateError.SyncSettingsError.SyncSettingsError
  fullName: Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError.SyncSettingsError
- uid: Dropbox.Api.Files.SyncSettingsError
  commentId: T:Dropbox.Api.Files.SyncSettingsError
  parent: Dropbox.Api.Files
  name: SyncSettingsError
  nameWithType: SyncSettingsError
  fullName: Dropbox.Api.Files.SyncSettingsError
- uid: Dropbox.Api.Files
  commentId: N:Dropbox.Api.Files
  name: Dropbox.Api.Files
  nameWithType: Dropbox.Api.Files
  fullName: Dropbox.Api.Files
- uid: Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError.Value*
  commentId: Overload:Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError.Value
  name: Value
  nameWithType: TeamFolderCreateError.SyncSettingsError.Value
  fullName: Dropbox.Api.Team.TeamFolderCreateError.SyncSettingsError.Value
shouldSkipMarkup: true
