### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.FileProperties.Routes
  commentId: N:Dropbox.Api.FileProperties.Routes
  id: Dropbox.Api.FileProperties.Routes
  children:
  - Dropbox.Api.FileProperties.Routes.FilePropertiesTeamRoutes
  - Dropbox.Api.FileProperties.Routes.FilePropertiesUserRoutes
  langs:
  - csharp
  - vb
  name: Dropbox.Api.FileProperties.Routes
  nameWithType: Dropbox.Api.FileProperties.Routes
  fullName: Dropbox.Api.FileProperties.Routes
  type: Namespace
  assemblies:
  - Dropbox.Api
references:
- uid: Dropbox.Api.FileProperties.Routes.FilePropertiesTeamRoutes
  commentId: T:Dropbox.Api.FileProperties.Routes.FilePropertiesTeamRoutes
  parent: Dropbox.Api.FileProperties.Routes
  name: FilePropertiesTeamRoutes
  nameWithType: FilePropertiesTeamRoutes
  fullName: Dropbox.Api.FileProperties.Routes.FilePropertiesTeamRoutes
- uid: Dropbox.Api.FileProperties.Routes.FilePropertiesUserRoutes
  commentId: T:Dropbox.Api.FileProperties.Routes.FilePropertiesUserRoutes
  parent: Dropbox.Api.FileProperties.Routes
  name: FilePropertiesUserRoutes
  nameWithType: FilePropertiesUserRoutes
  fullName: Dropbox.Api.FileProperties.Routes.FilePropertiesUserRoutes
- uid: Dropbox.Api.FileProperties.Routes
  commentId: N:Dropbox.Api.FileProperties.Routes
  name: Dropbox.Api.FileProperties.Routes
  nameWithType: Dropbox.Api.FileProperties.Routes
  fullName: Dropbox.Api.FileProperties.Routes
shouldSkipMarkup: true
