### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration
  commentId: T:Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration
  id: AdminAlertingAlertConfiguration
  parent: Dropbox.Api.TeamLog
  children:
  - Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.#ctor
  - Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.#ctor(Dropbox.Api.TeamLog.AdminAlertingAlertStatePolicy,Dropbox.Api.TeamLog.AdminAlertingAlertSensitivity,Dropbox.Api.TeamLog.RecipientsConfiguration)
  - Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.AlertState
  - Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.RecipientsSettings
  - Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.SensitivityLevel
  langs:
  - csharp
  - vb
  name: AdminAlertingAlertConfiguration
  nameWithType: AdminAlertingAlertConfiguration
  fullName: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/AdminAlertingAlertConfiguration.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: AdminAlertingAlertConfiguration
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/AdminAlertingAlertConfiguration.cs
    startLine: 16
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Alert configurations</p>\n"
  example: []
  syntax:
    content: 'public class AdminAlertingAlertConfiguration : object'
    content.vb: >-
      Public Class AdminAlertingAlertConfiguration
          Inherits Object
  seealso:
  - linkId: Dropbox.Api.TeamLog.AdminAlertingChangedAlertConfigDetails
    commentId: T:Dropbox.Api.TeamLog.AdminAlertingChangedAlertConfigDetails
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.#ctor(Dropbox.Api.TeamLog.AdminAlertingAlertStatePolicy,Dropbox.Api.TeamLog.AdminAlertingAlertSensitivity,Dropbox.Api.TeamLog.RecipientsConfiguration)
  commentId: M:Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.#ctor(Dropbox.Api.TeamLog.AdminAlertingAlertStatePolicy,Dropbox.Api.TeamLog.AdminAlertingAlertSensitivity,Dropbox.Api.TeamLog.RecipientsConfiguration)
  id: '#ctor(Dropbox.Api.TeamLog.AdminAlertingAlertStatePolicy,Dropbox.Api.TeamLog.AdminAlertingAlertSensitivity,Dropbox.Api.TeamLog.RecipientsConfiguration)'
  parent: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration
  langs:
  - csharp
  - vb
  name: AdminAlertingAlertConfiguration(AdminAlertingAlertStatePolicy, AdminAlertingAlertSensitivity, RecipientsConfiguration)
  nameWithType: AdminAlertingAlertConfiguration.AdminAlertingAlertConfiguration(AdminAlertingAlertStatePolicy, AdminAlertingAlertSensitivity, RecipientsConfiguration)
  fullName: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.AdminAlertingAlertConfiguration(Dropbox.Api.TeamLog.AdminAlertingAlertStatePolicy, Dropbox.Api.TeamLog.AdminAlertingAlertSensitivity, Dropbox.Api.TeamLog.RecipientsConfiguration)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/AdminAlertingAlertConfiguration.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/AdminAlertingAlertConfiguration.cs
    startLine: 37
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  example: []
  syntax:
    content: public AdminAlertingAlertConfiguration(AdminAlertingAlertStatePolicy alertState = null, AdminAlertingAlertSensitivity sensitivityLevel = null, RecipientsConfiguration recipientsSettings = null)
    parameters:
    - id: alertState
      type: Dropbox.Api.TeamLog.AdminAlertingAlertStatePolicy
      description: Alert state.
    - id: sensitivityLevel
      type: Dropbox.Api.TeamLog.AdminAlertingAlertSensitivity
      description: Sensitivity level.
    - id: recipientsSettings
      type: Dropbox.Api.TeamLog.RecipientsConfiguration
      description: Recipient settings.
    content.vb: Public Sub New(alertState As AdminAlertingAlertStatePolicy = Nothing, sensitivityLevel As AdminAlertingAlertSensitivity = Nothing, recipientsSettings As RecipientsConfiguration = Nothing)
  overload: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.#ctor
  commentId: M:Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.#ctor
  id: '#ctor'
  parent: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration
  langs:
  - csharp
  - vb
  name: AdminAlertingAlertConfiguration()
  nameWithType: AdminAlertingAlertConfiguration.AdminAlertingAlertConfiguration()
  fullName: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.AdminAlertingAlertConfiguration()
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/AdminAlertingAlertConfiguration.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/AdminAlertingAlertConfiguration.cs
    startLine: 52
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  remarks: >-
    This is to construct an instance of the object when

    deserializing.
  example: []
  syntax:
    content: public AdminAlertingAlertConfiguration()
    content.vb: Public Sub New
  overload: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.AlertState
  commentId: P:Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.AlertState
  id: AlertState
  parent: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration
  langs:
  - csharp
  - vb
  name: AlertState
  nameWithType: AdminAlertingAlertConfiguration.AlertState
  fullName: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.AlertState
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/AdminAlertingAlertConfiguration.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: AlertState
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/AdminAlertingAlertConfiguration.cs
    startLine: 60
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Alert state.</p>\n"
  example: []
  syntax:
    content: public AdminAlertingAlertStatePolicy AlertState { get; protected set; }
    parameters: []
    return:
      type: Dropbox.Api.TeamLog.AdminAlertingAlertStatePolicy
    content.vb: Public Property AlertState As AdminAlertingAlertStatePolicy
  overload: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.AlertState*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.SensitivityLevel
  commentId: P:Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.SensitivityLevel
  id: SensitivityLevel
  parent: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration
  langs:
  - csharp
  - vb
  name: SensitivityLevel
  nameWithType: AdminAlertingAlertConfiguration.SensitivityLevel
  fullName: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.SensitivityLevel
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/AdminAlertingAlertConfiguration.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SensitivityLevel
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/AdminAlertingAlertConfiguration.cs
    startLine: 65
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Sensitivity level.</p>\n"
  example: []
  syntax:
    content: public AdminAlertingAlertSensitivity SensitivityLevel { get; protected set; }
    parameters: []
    return:
      type: Dropbox.Api.TeamLog.AdminAlertingAlertSensitivity
    content.vb: Public Property SensitivityLevel As AdminAlertingAlertSensitivity
  overload: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.SensitivityLevel*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.RecipientsSettings
  commentId: P:Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.RecipientsSettings
  id: RecipientsSettings
  parent: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration
  langs:
  - csharp
  - vb
  name: RecipientsSettings
  nameWithType: AdminAlertingAlertConfiguration.RecipientsSettings
  fullName: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.RecipientsSettings
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/AdminAlertingAlertConfiguration.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: RecipientsSettings
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/AdminAlertingAlertConfiguration.cs
    startLine: 70
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Recipient settings.</p>\n"
  example: []
  syntax:
    content: public RecipientsConfiguration RecipientsSettings { get; protected set; }
    parameters: []
    return:
      type: Dropbox.Api.TeamLog.RecipientsConfiguration
    content.vb: Public Property RecipientsSettings As RecipientsConfiguration
  overload: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.RecipientsSettings*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
references:
- uid: Dropbox.Api.TeamLog.AdminAlertingChangedAlertConfigDetails
  commentId: T:Dropbox.Api.TeamLog.AdminAlertingChangedAlertConfigDetails
  parent: Dropbox.Api.TeamLog
  name: AdminAlertingChangedAlertConfigDetails
  nameWithType: AdminAlertingChangedAlertConfigDetails
  fullName: Dropbox.Api.TeamLog.AdminAlertingChangedAlertConfigDetails
- uid: Dropbox.Api.TeamLog
  commentId: N:Dropbox.Api.TeamLog
  name: Dropbox.Api.TeamLog
  nameWithType: Dropbox.Api.TeamLog
  fullName: Dropbox.Api.TeamLog
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration
  commentId: T:Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration
  parent: Dropbox.Api.TeamLog
  name: AdminAlertingAlertConfiguration
  nameWithType: AdminAlertingAlertConfiguration
  fullName: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration
- uid: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.#ctor*
  commentId: Overload:Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.#ctor
  name: AdminAlertingAlertConfiguration
  nameWithType: AdminAlertingAlertConfiguration.AdminAlertingAlertConfiguration
  fullName: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.AdminAlertingAlertConfiguration
- uid: Dropbox.Api.TeamLog.AdminAlertingAlertStatePolicy
  commentId: T:Dropbox.Api.TeamLog.AdminAlertingAlertStatePolicy
  parent: Dropbox.Api.TeamLog
  name: AdminAlertingAlertStatePolicy
  nameWithType: AdminAlertingAlertStatePolicy
  fullName: Dropbox.Api.TeamLog.AdminAlertingAlertStatePolicy
- uid: Dropbox.Api.TeamLog.AdminAlertingAlertSensitivity
  commentId: T:Dropbox.Api.TeamLog.AdminAlertingAlertSensitivity
  parent: Dropbox.Api.TeamLog
  name: AdminAlertingAlertSensitivity
  nameWithType: AdminAlertingAlertSensitivity
  fullName: Dropbox.Api.TeamLog.AdminAlertingAlertSensitivity
- uid: Dropbox.Api.TeamLog.RecipientsConfiguration
  commentId: T:Dropbox.Api.TeamLog.RecipientsConfiguration
  parent: Dropbox.Api.TeamLog
  name: RecipientsConfiguration
  nameWithType: RecipientsConfiguration
  fullName: Dropbox.Api.TeamLog.RecipientsConfiguration
- uid: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.AlertState*
  commentId: Overload:Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.AlertState
  name: AlertState
  nameWithType: AdminAlertingAlertConfiguration.AlertState
  fullName: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.AlertState
- uid: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.SensitivityLevel*
  commentId: Overload:Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.SensitivityLevel
  name: SensitivityLevel
  nameWithType: AdminAlertingAlertConfiguration.SensitivityLevel
  fullName: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.SensitivityLevel
- uid: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.RecipientsSettings*
  commentId: Overload:Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.RecipientsSettings
  name: RecipientsSettings
  nameWithType: AdminAlertingAlertConfiguration.RecipientsSettings
  fullName: Dropbox.Api.TeamLog.AdminAlertingAlertConfiguration.RecipientsSettings
shouldSkipMarkup: true
