### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Contacts.Routes
  commentId: N:Dropbox.Api.Contacts.Routes
  id: Dropbox.Api.Contacts.Routes
  children:
  - Dropbox.Api.Contacts.Routes.ContactsUserRoutes
  langs:
  - csharp
  - vb
  name: Dropbox.Api.Contacts.Routes
  nameWithType: Dropbox.Api.Contacts.Routes
  fullName: Dropbox.Api.Contacts.Routes
  type: Namespace
  assemblies:
  - Dropbox.Api
references:
- uid: Dropbox.Api.Contacts.Routes.ContactsUserRoutes
  commentId: T:Dropbox.Api.Contacts.Routes.ContactsUserRoutes
  parent: Dropbox.Api.Contacts.Routes
  name: ContactsUserRoutes
  nameWithType: ContactsUserRoutes
  fullName: Dropbox.Api.Contacts.Routes.ContactsUserRoutes
- uid: Dropbox.Api.Contacts.Routes
  commentId: N:Dropbox.Api.Contacts.Routes
  name: Dropbox.Api.Contacts.Routes
  nameWithType: Dropbox.Api.Contacts.Routes
  fullName: Dropbox.Api.Contacts.Routes
shouldSkipMarkup: true
