### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
  commentId: T:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
  id: CreateSharedLinkWithSettingsArg
  parent: Dropbox.Api.Sharing
  children:
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.#ctor
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.#ctor(System.String,Dropbox.Api.Sharing.SharedLinkSettings)
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Path
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Settings
  langs:
  - csharp
  - vb
  name: CreateSharedLinkWithSettingsArg
  nameWithType: CreateSharedLinkWithSettingsArg
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsArg.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: CreateSharedLinkWithSettingsArg
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsArg.cs
    startLine: 15
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>The create shared link with settings arg object</p>\n"
  example: []
  syntax:
    content: 'public class CreateSharedLinkWithSettingsArg : object'
    content.vb: >-
      Public Class CreateSharedLinkWithSettingsArg
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.#ctor(System.String,Dropbox.Api.Sharing.SharedLinkSettings)
  commentId: M:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.#ctor(System.String,Dropbox.Api.Sharing.SharedLinkSettings)
  id: '#ctor(System.String,Dropbox.Api.Sharing.SharedLinkSettings)'
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
  langs:
  - csharp
  - vb
  name: CreateSharedLinkWithSettingsArg(String, SharedLinkSettings)
  nameWithType: CreateSharedLinkWithSettingsArg.CreateSharedLinkWithSettingsArg(String, SharedLinkSettings)
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.CreateSharedLinkWithSettingsArg(System.String, Dropbox.Api.Sharing.SharedLinkSettings)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsArg.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsArg.cs
    startLine: 36
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  example: []
  syntax:
    content: public CreateSharedLinkWithSettingsArg(string path, SharedLinkSettings settings = null)
    parameters:
    - id: path
      type: System.String
      description: The path to be shared by the shared link.
    - id: settings
      type: Dropbox.Api.Sharing.SharedLinkSettings
      description: >-
        The requested settings for the newly created shared

        link.
    content.vb: Public Sub New(path As String, settings As SharedLinkSettings = Nothing)
  overload: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.#ctor
  commentId: M:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.#ctor
  id: '#ctor'
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
  langs:
  - csharp
  - vb
  name: CreateSharedLinkWithSettingsArg()
  nameWithType: CreateSharedLinkWithSettingsArg.CreateSharedLinkWithSettingsArg()
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.CreateSharedLinkWithSettingsArg()
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsArg.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsArg.cs
    startLine: 58
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  remarks: >-
    This is to construct an instance of the object when

    deserializing.
  example: []
  syntax:
    content: public CreateSharedLinkWithSettingsArg()
    content.vb: Public Sub New
  overload: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Path
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Path
  id: Path
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
  langs:
  - csharp
  - vb
  name: Path
  nameWithType: CreateSharedLinkWithSettingsArg.Path
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Path
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsArg.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Path
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsArg.cs
    startLine: 66
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>The path to be shared by the shared link.</p>\n"
  example: []
  syntax:
    content: public string Path { get; protected set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Path As String
  overload: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Path*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Settings
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Settings
  id: Settings
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
  langs:
  - csharp
  - vb
  name: Settings
  nameWithType: CreateSharedLinkWithSettingsArg.Settings
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Settings
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsArg.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Settings
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsArg.cs
    startLine: 71
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>The requested settings for the newly created shared link.</p>\n"
  example: []
  syntax:
    content: public SharedLinkSettings Settings { get; protected set; }
    parameters: []
    return:
      type: Dropbox.Api.Sharing.SharedLinkSettings
    content.vb: Public Property Settings As SharedLinkSettings
  overload: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Settings*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
references:
- uid: Dropbox.Api.Sharing
  commentId: N:Dropbox.Api.Sharing
  name: Dropbox.Api.Sharing
  nameWithType: Dropbox.Api.Sharing
  fullName: Dropbox.Api.Sharing
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
  commentId: T:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
  parent: Dropbox.Api.Sharing
  name: CreateSharedLinkWithSettingsArg
  nameWithType: CreateSharedLinkWithSettingsArg
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.#ctor*
  commentId: Overload:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.#ctor
  name: CreateSharedLinkWithSettingsArg
  nameWithType: CreateSharedLinkWithSettingsArg.CreateSharedLinkWithSettingsArg
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.CreateSharedLinkWithSettingsArg
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Dropbox.Api.Sharing.SharedLinkSettings
  commentId: T:Dropbox.Api.Sharing.SharedLinkSettings
  parent: Dropbox.Api.Sharing
  name: SharedLinkSettings
  nameWithType: SharedLinkSettings
  fullName: Dropbox.Api.Sharing.SharedLinkSettings
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Path*
  commentId: Overload:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Path
  name: Path
  nameWithType: CreateSharedLinkWithSettingsArg.Path
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Path
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Settings*
  commentId: Overload:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Settings
  name: Settings
  nameWithType: CreateSharedLinkWithSettingsArg.Settings
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsArg.Settings
shouldSkipMarkup: true
