### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType
  commentId: T:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType
  id: SharedLinkSettingsChangeAudienceType
  parent: Dropbox.Api.TeamLog
  children:
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.#ctor
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.#ctor(System.String)
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.Description
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsChangeAudienceType
  nameWithType: SharedLinkSettingsChangeAudienceType
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceType.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SharedLinkSettingsChangeAudienceType
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceType.cs
    startLine: 15
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>The shared link settings change audience type object</p>\n"
  example: []
  syntax:
    content: 'public class SharedLinkSettingsChangeAudienceType : object'
    content.vb: >-
      Public Class SharedLinkSettingsChangeAudienceType
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.#ctor(System.String)
  commentId: M:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsChangeAudienceType(String)
  nameWithType: SharedLinkSettingsChangeAudienceType.SharedLinkSettingsChangeAudienceType(String)
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.SharedLinkSettingsChangeAudienceType(System.String)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceType.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceType.cs
    startLine: 34
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  example: []
  syntax:
    content: public SharedLinkSettingsChangeAudienceType(string description)
    parameters:
    - id: description
      type: System.String
      description: The description
    content.vb: Public Sub New(description As String)
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.#ctor
  commentId: M:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.#ctor
  id: '#ctor'
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsChangeAudienceType()
  nameWithType: SharedLinkSettingsChangeAudienceType.SharedLinkSettingsChangeAudienceType()
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.SharedLinkSettingsChangeAudienceType()
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceType.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceType.cs
    startLine: 50
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  remarks: >-
    This is to construct an instance of the object when

    deserializing.
  example: []
  syntax:
    content: public SharedLinkSettingsChangeAudienceType()
    content.vb: Public Sub New
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.Description
  commentId: P:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.Description
  id: Description
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType
  langs:
  - csharp
  - vb
  name: Description
  nameWithType: SharedLinkSettingsChangeAudienceType.Description
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.Description
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceType.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Description
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeAudienceType.cs
    startLine: 58
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Gets the description of the shared link settings change audience type</p>\n"
  example: []
  syntax:
    content: public string Description { get; protected set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Description As String
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.Description*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
references:
- uid: Dropbox.Api.TeamLog
  commentId: N:Dropbox.Api.TeamLog
  name: Dropbox.Api.TeamLog
  nameWithType: Dropbox.Api.TeamLog
  fullName: Dropbox.Api.TeamLog
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType
  commentId: T:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType
  parent: Dropbox.Api.TeamLog
  name: SharedLinkSettingsChangeAudienceType
  nameWithType: SharedLinkSettingsChangeAudienceType
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.#ctor*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.#ctor
  name: SharedLinkSettingsChangeAudienceType
  nameWithType: SharedLinkSettingsChangeAudienceType.SharedLinkSettingsChangeAudienceType
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.SharedLinkSettingsChangeAudienceType
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.Description*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.Description
  name: Description
  nameWithType: SharedLinkSettingsChangeAudienceType.Description
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeAudienceType.Description
shouldSkipMarkup: true
