### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails
  commentId: T:Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails
  id: SharedLinkSettingsChangePasswordDetails
  parent: Dropbox.Api.TeamLog
  children:
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.#ctor
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.#ctor(Dropbox.Api.Sharing.AccessLevel,System.String)
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedContentAccessLevel
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedContentLink
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsChangePasswordDetails
  nameWithType: SharedLinkSettingsChangePasswordDetails
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangePasswordDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SharedLinkSettingsChangePasswordDetails
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangePasswordDetails.cs
    startLine: 15
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Changed the password of the shared link.</p>\n"
  example: []
  syntax:
    content: 'public class SharedLinkSettingsChangePasswordDetails : object'
    content.vb: >-
      Public Class SharedLinkSettingsChangePasswordDetails
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.#ctor(Dropbox.Api.Sharing.AccessLevel,System.String)
  commentId: M:Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.#ctor(Dropbox.Api.Sharing.AccessLevel,System.String)
  id: '#ctor(Dropbox.Api.Sharing.AccessLevel,System.String)'
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsChangePasswordDetails(AccessLevel, String)
  nameWithType: SharedLinkSettingsChangePasswordDetails.SharedLinkSettingsChangePasswordDetails(AccessLevel, String)
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedLinkSettingsChangePasswordDetails(Dropbox.Api.Sharing.AccessLevel, System.String)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangePasswordDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangePasswordDetails.cs
    startLine: 35
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  example: []
  syntax:
    content: public SharedLinkSettingsChangePasswordDetails(AccessLevel sharedContentAccessLevel, string sharedContentLink = null)
    parameters:
    - id: sharedContentAccessLevel
      type: Dropbox.Api.Sharing.AccessLevel
      description: Shared content access level.
    - id: sharedContentLink
      type: System.String
      description: Shared content link.
    content.vb: Public Sub New(sharedContentAccessLevel As AccessLevel, sharedContentLink As String = Nothing)
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.#ctor
  commentId: M:Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.#ctor
  id: '#ctor'
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsChangePasswordDetails()
  nameWithType: SharedLinkSettingsChangePasswordDetails.SharedLinkSettingsChangePasswordDetails()
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedLinkSettingsChangePasswordDetails()
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangePasswordDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangePasswordDetails.cs
    startLine: 53
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  remarks: >-
    This is to construct an instance of the object when

    deserializing.
  example: []
  syntax:
    content: public SharedLinkSettingsChangePasswordDetails()
    content.vb: Public Sub New
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedContentAccessLevel
  commentId: P:Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedContentAccessLevel
  id: SharedContentAccessLevel
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails
  langs:
  - csharp
  - vb
  name: SharedContentAccessLevel
  nameWithType: SharedLinkSettingsChangePasswordDetails.SharedContentAccessLevel
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedContentAccessLevel
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangePasswordDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SharedContentAccessLevel
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangePasswordDetails.cs
    startLine: 61
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Shared content access level.</p>\n"
  example: []
  syntax:
    content: public AccessLevel SharedContentAccessLevel { get; protected set; }
    parameters: []
    return:
      type: Dropbox.Api.Sharing.AccessLevel
    content.vb: Public Property SharedContentAccessLevel As AccessLevel
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedContentAccessLevel*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedContentLink
  commentId: P:Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedContentLink
  id: SharedContentLink
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails
  langs:
  - csharp
  - vb
  name: SharedContentLink
  nameWithType: SharedLinkSettingsChangePasswordDetails.SharedContentLink
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedContentLink
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangePasswordDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SharedContentLink
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangePasswordDetails.cs
    startLine: 66
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Shared content link.</p>\n"
  example: []
  syntax:
    content: public string SharedContentLink { get; protected set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property SharedContentLink As String
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedContentLink*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
references:
- uid: Dropbox.Api.TeamLog
  commentId: N:Dropbox.Api.TeamLog
  name: Dropbox.Api.TeamLog
  nameWithType: Dropbox.Api.TeamLog
  fullName: Dropbox.Api.TeamLog
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails
  commentId: T:Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails
  parent: Dropbox.Api.TeamLog
  name: SharedLinkSettingsChangePasswordDetails
  nameWithType: SharedLinkSettingsChangePasswordDetails
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.#ctor*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.#ctor
  name: SharedLinkSettingsChangePasswordDetails
  nameWithType: SharedLinkSettingsChangePasswordDetails.SharedLinkSettingsChangePasswordDetails
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedLinkSettingsChangePasswordDetails
- uid: Dropbox.Api.Sharing.AccessLevel
  commentId: T:Dropbox.Api.Sharing.AccessLevel
  parent: Dropbox.Api.Sharing
  name: AccessLevel
  nameWithType: AccessLevel
  fullName: Dropbox.Api.Sharing.AccessLevel
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Dropbox.Api.Sharing
  commentId: N:Dropbox.Api.Sharing
  name: Dropbox.Api.Sharing
  nameWithType: Dropbox.Api.Sharing
  fullName: Dropbox.Api.Sharing
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedContentAccessLevel*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedContentAccessLevel
  name: SharedContentAccessLevel
  nameWithType: SharedLinkSettingsChangePasswordDetails.SharedContentAccessLevel
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedContentAccessLevel
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedContentLink*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedContentLink
  name: SharedContentLink
  nameWithType: SharedLinkSettingsChangePasswordDetails.SharedContentLink
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordDetails.SharedContentLink
shouldSkipMarkup: true
