### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.NotAuthorized
  commentId: T:Dropbox.Api.Sharing.SharedLinkSettingsError.NotAuthorized
  id: SharedLinkSettingsError.NotAuthorized
  parent: Dropbox.Api.Sharing
  children:
  - Dropbox.Api.Sharing.SharedLinkSettingsError.NotAuthorized.Instance
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsError.NotAuthorized
  nameWithType: SharedLinkSettingsError.NotAuthorized
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.NotAuthorized
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/SharedLinkSettingsError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: NotAuthorized
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/SharedLinkSettingsError.cs
    startLine: 233
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>User is not allowed to modify the settings of this link. Note that basic\nusers can only set <xref href=\"Dropbox.Api.Sharing.RequestedVisibility.Public\" data-throw-if-not-resolved=\"false\"></xref> as\nthe <xref href=\"Dropbox.Api.Sharing.SharedLinkSettings.RequestedVisibility\" data-throw-if-not-resolved=\"false\"></xref> and\ncannot set <xref href=\"Dropbox.Api.Sharing.SharedLinkSettings.Expires\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n"
  example: []
  syntax:
    content: 'public sealed class NotAuthorized : SharedLinkSettingsError'
    content.vb: >-
      Public NotInheritable Class NotAuthorized
          Inherits SharedLinkSettingsError
  inheritance:
  - System.Object
  - Dropbox.Api.Sharing.SharedLinkSettingsError
  inheritedMembers:
  - Dropbox.Api.Sharing.SharedLinkSettingsError.IsInvalidSettings
  - Dropbox.Api.Sharing.SharedLinkSettingsError.AsInvalidSettings
  - Dropbox.Api.Sharing.SharedLinkSettingsError.IsNotAuthorized
  - Dropbox.Api.Sharing.SharedLinkSettingsError.AsNotAuthorized
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.NotAuthorized.Instance
  commentId: F:Dropbox.Api.Sharing.SharedLinkSettingsError.NotAuthorized.Instance
  id: Instance
  parent: Dropbox.Api.Sharing.SharedLinkSettingsError.NotAuthorized
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: SharedLinkSettingsError.NotAuthorized.Instance
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.NotAuthorized.Instance
  type: Field
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/SharedLinkSettingsError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Instance
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/SharedLinkSettingsError.cs
    startLine: 258
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>A singleton instance of NotAuthorized</p>\n"
  example: []
  syntax:
    content: public static readonly SharedLinkSettingsError.NotAuthorized Instance
    return:
      type: Dropbox.Api.Sharing.SharedLinkSettingsError.NotAuthorized
    content.vb: Public Shared ReadOnly Instance As SharedLinkSettingsError.NotAuthorized
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: Dropbox.Api.Sharing.RequestedVisibility.Public
  commentId: T:Dropbox.Api.Sharing.RequestedVisibility.Public
  parent: Dropbox.Api.Sharing
  name: RequestedVisibility.Public
  nameWithType: RequestedVisibility.Public
  fullName: Dropbox.Api.Sharing.RequestedVisibility.Public
- uid: Dropbox.Api.Sharing.SharedLinkSettings.RequestedVisibility
  commentId: P:Dropbox.Api.Sharing.SharedLinkSettings.RequestedVisibility
  isExternal: true
- uid: Dropbox.Api.Sharing.SharedLinkSettings.Expires
  commentId: P:Dropbox.Api.Sharing.SharedLinkSettings.Expires
  isExternal: true
- uid: Dropbox.Api.Sharing
  commentId: N:Dropbox.Api.Sharing
  name: Dropbox.Api.Sharing
  nameWithType: Dropbox.Api.Sharing
  fullName: Dropbox.Api.Sharing
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError
  commentId: T:Dropbox.Api.Sharing.SharedLinkSettingsError
  parent: Dropbox.Api.Sharing
  name: SharedLinkSettingsError
  nameWithType: SharedLinkSettingsError
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.IsInvalidSettings
  commentId: P:Dropbox.Api.Sharing.SharedLinkSettingsError.IsInvalidSettings
  parent: Dropbox.Api.Sharing.SharedLinkSettingsError
  name: IsInvalidSettings
  nameWithType: SharedLinkSettingsError.IsInvalidSettings
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.IsInvalidSettings
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.AsInvalidSettings
  commentId: P:Dropbox.Api.Sharing.SharedLinkSettingsError.AsInvalidSettings
  parent: Dropbox.Api.Sharing.SharedLinkSettingsError
  name: AsInvalidSettings
  nameWithType: SharedLinkSettingsError.AsInvalidSettings
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.AsInvalidSettings
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.IsNotAuthorized
  commentId: P:Dropbox.Api.Sharing.SharedLinkSettingsError.IsNotAuthorized
  parent: Dropbox.Api.Sharing.SharedLinkSettingsError
  name: IsNotAuthorized
  nameWithType: SharedLinkSettingsError.IsNotAuthorized
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.IsNotAuthorized
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.AsNotAuthorized
  commentId: P:Dropbox.Api.Sharing.SharedLinkSettingsError.AsNotAuthorized
  parent: Dropbox.Api.Sharing.SharedLinkSettingsError
  name: AsNotAuthorized
  nameWithType: SharedLinkSettingsError.AsNotAuthorized
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.AsNotAuthorized
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.NotAuthorized
  commentId: T:Dropbox.Api.Sharing.SharedLinkSettingsError.NotAuthorized
  parent: Dropbox.Api.Sharing
  name: SharedLinkSettingsError.NotAuthorized
  nameWithType: SharedLinkSettingsError.NotAuthorized
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.NotAuthorized
shouldSkipMarkup: true
