### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg
  commentId: T:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg
  id: TeamFolderUpdateSyncSettingsArg
  parent: Dropbox.Api.Team
  children:
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.#ctor
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.#ctor(System.String,Dropbox.Api.Files.SyncSettingArg,System.Collections.Generic.IEnumerable{Dropbox.Api.Files.ContentSyncSettingArg})
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.ContentSyncSettings
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.SyncSetting
  langs:
  - csharp
  - vb
  name: TeamFolderUpdateSyncSettingsArg
  nameWithType: TeamFolderUpdateSyncSettingsArg
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsArg.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: TeamFolderUpdateSyncSettingsArg
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsArg.cs
    startLine: 16
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>The team folder update sync settings arg object</p>\n"
  example: []
  syntax:
    content: 'public class TeamFolderUpdateSyncSettingsArg : TeamFolderIdArg'
    content.vb: >-
      Public Class TeamFolderUpdateSyncSettingsArg
          Inherits TeamFolderIdArg
  inheritance:
  - System.Object
  - Dropbox.Api.Team.TeamFolderIdArg
  inheritedMembers:
  - Dropbox.Api.Team.TeamFolderIdArg.TeamFolderId
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.#ctor(System.String,Dropbox.Api.Files.SyncSettingArg,System.Collections.Generic.IEnumerable{Dropbox.Api.Files.ContentSyncSettingArg})
  commentId: M:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.#ctor(System.String,Dropbox.Api.Files.SyncSettingArg,System.Collections.Generic.IEnumerable{Dropbox.Api.Files.ContentSyncSettingArg})
  id: '#ctor(System.String,Dropbox.Api.Files.SyncSettingArg,System.Collections.Generic.IEnumerable{Dropbox.Api.Files.ContentSyncSettingArg})'
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg
  langs:
  - csharp
  - vb
  name: TeamFolderUpdateSyncSettingsArg(String, SyncSettingArg, System.Collections.Generic.IEnumerable<ContentSyncSettingArg>)
  nameWithType: TeamFolderUpdateSyncSettingsArg.TeamFolderUpdateSyncSettingsArg(String, SyncSettingArg, System.Collections.Generic.IEnumerable<ContentSyncSettingArg>)
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.TeamFolderUpdateSyncSettingsArg(System.String, Dropbox.Api.Files.SyncSettingArg, System.Collections.Generic.IEnumerable<Dropbox.Api.Files.ContentSyncSettingArg>)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsArg.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsArg.cs
    startLine: 39
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  example: []
  syntax:
    content: public TeamFolderUpdateSyncSettingsArg(string teamFolderId, SyncSettingArg syncSetting = null, System.Collections.Generic.IEnumerable<ContentSyncSettingArg> contentSyncSettings = null)
    parameters:
    - id: teamFolderId
      type: System.String
      description: The ID of the team folder.
    - id: syncSetting
      type: Dropbox.Api.Files.SyncSettingArg
      description: >-
        Sync setting to apply to the team folder itself. Only

        meaningful if the team folder is not a shared team root.
    - id: contentSyncSettings
      type: System.Collections.Generic.IEnumerable{Dropbox.Api.Files.ContentSyncSettingArg}
      description: >-
        Sync settings to apply to contents of this team

        folder.
    content.vb: Public Sub New(teamFolderId As String, syncSetting As SyncSettingArg = Nothing, contentSyncSettings As System.Collections.Generic.IEnumerable(Of ContentSyncSettingArg) = Nothing)
  overload: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.#ctor*
  nameWithType.vb: TeamFolderUpdateSyncSettingsArg.TeamFolderUpdateSyncSettingsArg(String, SyncSettingArg, System.Collections.Generic.IEnumerable(Of ContentSyncSettingArg))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.TeamFolderUpdateSyncSettingsArg(System.String, Dropbox.Api.Files.SyncSettingArg, System.Collections.Generic.IEnumerable(Of Dropbox.Api.Files.ContentSyncSettingArg))
  name.vb: TeamFolderUpdateSyncSettingsArg(String, SyncSettingArg, System.Collections.Generic.IEnumerable(Of ContentSyncSettingArg))
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.#ctor
  commentId: M:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.#ctor
  id: '#ctor'
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg
  langs:
  - csharp
  - vb
  name: TeamFolderUpdateSyncSettingsArg()
  nameWithType: TeamFolderUpdateSyncSettingsArg.TeamFolderUpdateSyncSettingsArg()
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.TeamFolderUpdateSyncSettingsArg()
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsArg.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsArg.cs
    startLine: 56
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  remarks: >-
    This is to construct an instance of the object when

    deserializing.
  example: []
  syntax:
    content: public TeamFolderUpdateSyncSettingsArg()
    content.vb: Public Sub New
  overload: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.SyncSetting
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.SyncSetting
  id: SyncSetting
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg
  langs:
  - csharp
  - vb
  name: SyncSetting
  nameWithType: TeamFolderUpdateSyncSettingsArg.SyncSetting
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.SyncSetting
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsArg.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SyncSetting
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsArg.cs
    startLine: 65
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>Sync setting to apply to the team folder itself. Only meaningful if the team\nfolder is not a shared team root.</p>\n"
  example: []
  syntax:
    content: public SyncSettingArg SyncSetting { get; protected set; }
    parameters: []
    return:
      type: Dropbox.Api.Files.SyncSettingArg
    content.vb: Public Property SyncSetting As SyncSettingArg
  overload: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.SyncSetting*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.ContentSyncSettings
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.ContentSyncSettings
  id: ContentSyncSettings
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg
  langs:
  - csharp
  - vb
  name: ContentSyncSettings
  nameWithType: TeamFolderUpdateSyncSettingsArg.ContentSyncSettings
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.ContentSyncSettings
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsArg.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: ContentSyncSettings
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsArg.cs
    startLine: 70
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>Sync settings to apply to contents of this team folder.</p>\n"
  example: []
  syntax:
    content: public System.Collections.Generic.IList<ContentSyncSettingArg> ContentSyncSettings { get; protected set; }
    parameters: []
    return:
      type: System.Collections.Generic.IList{Dropbox.Api.Files.ContentSyncSettingArg}
    content.vb: Public Property ContentSyncSettings As System.Collections.Generic.IList(Of ContentSyncSettingArg)
  overload: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.ContentSyncSettings*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
references:
- uid: Dropbox.Api.Team
  commentId: N:Dropbox.Api.Team
  name: Dropbox.Api.Team
  nameWithType: Dropbox.Api.Team
  fullName: Dropbox.Api.Team
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.Team.TeamFolderIdArg
  commentId: T:Dropbox.Api.Team.TeamFolderIdArg
  parent: Dropbox.Api.Team
  name: TeamFolderIdArg
  nameWithType: TeamFolderIdArg
  fullName: Dropbox.Api.Team.TeamFolderIdArg
- uid: Dropbox.Api.Team.TeamFolderIdArg.TeamFolderId
  commentId: P:Dropbox.Api.Team.TeamFolderIdArg.TeamFolderId
  parent: Dropbox.Api.Team.TeamFolderIdArg
  name: TeamFolderId
  nameWithType: TeamFolderIdArg.TeamFolderId
  fullName: Dropbox.Api.Team.TeamFolderIdArg.TeamFolderId
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg
  commentId: T:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg
  parent: Dropbox.Api.Team
  name: TeamFolderUpdateSyncSettingsArg
  nameWithType: TeamFolderUpdateSyncSettingsArg
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.#ctor*
  commentId: Overload:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.#ctor
  name: TeamFolderUpdateSyncSettingsArg
  nameWithType: TeamFolderUpdateSyncSettingsArg.TeamFolderUpdateSyncSettingsArg
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.TeamFolderUpdateSyncSettingsArg
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Dropbox.Api.Files.SyncSettingArg
  commentId: T:Dropbox.Api.Files.SyncSettingArg
  parent: Dropbox.Api.Files
  name: SyncSettingArg
  nameWithType: SyncSettingArg
  fullName: Dropbox.Api.Files.SyncSettingArg
- uid: System.Collections.Generic.IEnumerable{Dropbox.Api.Files.ContentSyncSettingArg}
  commentId: '!:System.Collections.Generic.IEnumerable{Dropbox.Api.Files.ContentSyncSettingArg}'
  definition: System.Collections.Generic.IEnumerable`1
  name: System.Collections.Generic.IEnumerable<ContentSyncSettingArg>
  nameWithType: System.Collections.Generic.IEnumerable<ContentSyncSettingArg>
  fullName: System.Collections.Generic.IEnumerable<Dropbox.Api.Files.ContentSyncSettingArg>
  nameWithType.vb: System.Collections.Generic.IEnumerable(Of ContentSyncSettingArg)
  fullName.vb: System.Collections.Generic.IEnumerable(Of Dropbox.Api.Files.ContentSyncSettingArg)
  name.vb: System.Collections.Generic.IEnumerable(Of ContentSyncSettingArg)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: System.Collections.Generic.IEnumerable
    nameWithType: System.Collections.Generic.IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Dropbox.Api.Files.ContentSyncSettingArg
    name: ContentSyncSettingArg
    nameWithType: ContentSyncSettingArg
    fullName: Dropbox.Api.Files.ContentSyncSettingArg
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: System.Collections.Generic.IEnumerable
    nameWithType: System.Collections.Generic.IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Dropbox.Api.Files.ContentSyncSettingArg
    name: ContentSyncSettingArg
    nameWithType: ContentSyncSettingArg
    fullName: Dropbox.Api.Files.ContentSyncSettingArg
  - name: )
    nameWithType: )
    fullName: )
- uid: Dropbox.Api.Files
  commentId: N:Dropbox.Api.Files
  name: Dropbox.Api.Files
  nameWithType: Dropbox.Api.Files
  fullName: Dropbox.Api.Files
- uid: System.Collections.Generic.IEnumerable`1
  isExternal: true
  name: System.Collections.Generic.IEnumerable<>
  nameWithType: System.Collections.Generic.IEnumerable<>
  fullName: System.Collections.Generic.IEnumerable<>
  nameWithType.vb: System.Collections.Generic.IEnumerable(Of )
  fullName.vb: System.Collections.Generic.IEnumerable(Of )
  name.vb: System.Collections.Generic.IEnumerable(Of )
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: System.Collections.Generic.IEnumerable
    nameWithType: System.Collections.Generic.IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: System.Collections.Generic.IEnumerable
    nameWithType: System.Collections.Generic.IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.SyncSetting*
  commentId: Overload:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.SyncSetting
  name: SyncSetting
  nameWithType: TeamFolderUpdateSyncSettingsArg.SyncSetting
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.SyncSetting
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.ContentSyncSettings*
  commentId: Overload:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.ContentSyncSettings
  name: ContentSyncSettings
  nameWithType: TeamFolderUpdateSyncSettingsArg.ContentSyncSettings
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsArg.ContentSyncSettings
- uid: System.Collections.Generic.IList{Dropbox.Api.Files.ContentSyncSettingArg}
  commentId: '!:System.Collections.Generic.IList{Dropbox.Api.Files.ContentSyncSettingArg}'
  definition: System.Collections.Generic.IList`1
  name: System.Collections.Generic.IList<ContentSyncSettingArg>
  nameWithType: System.Collections.Generic.IList<ContentSyncSettingArg>
  fullName: System.Collections.Generic.IList<Dropbox.Api.Files.ContentSyncSettingArg>
  nameWithType.vb: System.Collections.Generic.IList(Of ContentSyncSettingArg)
  fullName.vb: System.Collections.Generic.IList(Of Dropbox.Api.Files.ContentSyncSettingArg)
  name.vb: System.Collections.Generic.IList(Of ContentSyncSettingArg)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: System.Collections.Generic.IList
    nameWithType: System.Collections.Generic.IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Dropbox.Api.Files.ContentSyncSettingArg
    name: ContentSyncSettingArg
    nameWithType: ContentSyncSettingArg
    fullName: Dropbox.Api.Files.ContentSyncSettingArg
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: System.Collections.Generic.IList
    nameWithType: System.Collections.Generic.IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Dropbox.Api.Files.ContentSyncSettingArg
    name: ContentSyncSettingArg
    nameWithType: ContentSyncSettingArg
    fullName: Dropbox.Api.Files.ContentSyncSettingArg
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  isExternal: true
  name: System.Collections.Generic.IList<>
  nameWithType: System.Collections.Generic.IList<>
  fullName: System.Collections.Generic.IList<>
  nameWithType.vb: System.Collections.Generic.IList(Of )
  fullName.vb: System.Collections.Generic.IList(Of )
  name.vb: System.Collections.Generic.IList(Of )
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: System.Collections.Generic.IList
    nameWithType: System.Collections.Generic.IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: System.Collections.Generic.IList
    nameWithType: System.Collections.Generic.IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
shouldSkipMarkup: true
