### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings
  commentId: T:Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings
  id: SharedLinkSettingsError.InvalidSettings
  parent: Dropbox.Api.Sharing
  children:
  - Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings.Instance
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsError.InvalidSettings
  nameWithType: SharedLinkSettingsError.InvalidSettings
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/SharedLinkSettingsError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: InvalidSettings
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/SharedLinkSettingsError.cs
    startLine: 160
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>The given settings are invalid (for example, all attributes of the <xref href=\"Dropbox.Api.Sharing.SharedLinkSettings\" data-throw-if-not-resolved=\"false\"></xref> are empty, the requested visibility is <xref href=\"Dropbox.Api.Sharing.RequestedVisibility.Password\" data-throw-if-not-resolved=\"false\"></xref> but the <xref href=\"Dropbox.Api.Sharing.SharedLinkSettings.LinkPassword\" data-throw-if-not-resolved=\"false\"></xref> is missing, <xref href=\"Dropbox.Api.Sharing.SharedLinkSettings.Expires\" data-throw-if-not-resolved=\"false\"></xref> is set to the past,\netc.).</p>\n"
  example: []
  syntax:
    content: 'public sealed class InvalidSettings : SharedLinkSettingsError'
    content.vb: >-
      Public NotInheritable Class InvalidSettings
          Inherits SharedLinkSettingsError
  inheritance:
  - System.Object
  - Dropbox.Api.Sharing.SharedLinkSettingsError
  inheritedMembers:
  - Dropbox.Api.Sharing.SharedLinkSettingsError.IsInvalidSettings
  - Dropbox.Api.Sharing.SharedLinkSettingsError.AsInvalidSettings
  - Dropbox.Api.Sharing.SharedLinkSettingsError.IsNotAuthorized
  - Dropbox.Api.Sharing.SharedLinkSettingsError.AsNotAuthorized
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings.Instance
  commentId: F:Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings.Instance
  id: Instance
  parent: Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: SharedLinkSettingsError.InvalidSettings.Instance
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings.Instance
  type: Field
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/SharedLinkSettingsError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Instance
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/SharedLinkSettingsError.cs
    startLine: 185
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>A singleton instance of InvalidSettings</p>\n"
  example: []
  syntax:
    content: public static readonly SharedLinkSettingsError.InvalidSettings Instance
    return:
      type: Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings
    content.vb: Public Shared ReadOnly Instance As SharedLinkSettingsError.InvalidSettings
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: Dropbox.Api.Sharing.SharedLinkSettings
  commentId: T:Dropbox.Api.Sharing.SharedLinkSettings
  parent: Dropbox.Api.Sharing
  name: SharedLinkSettings
  nameWithType: SharedLinkSettings
  fullName: Dropbox.Api.Sharing.SharedLinkSettings
- uid: Dropbox.Api.Sharing.RequestedVisibility.Password
  commentId: T:Dropbox.Api.Sharing.RequestedVisibility.Password
  parent: Dropbox.Api.Sharing
  name: RequestedVisibility.Password
  nameWithType: RequestedVisibility.Password
  fullName: Dropbox.Api.Sharing.RequestedVisibility.Password
- uid: Dropbox.Api.Sharing.SharedLinkSettings.LinkPassword
  commentId: P:Dropbox.Api.Sharing.SharedLinkSettings.LinkPassword
  isExternal: true
- uid: Dropbox.Api.Sharing.SharedLinkSettings.Expires
  commentId: P:Dropbox.Api.Sharing.SharedLinkSettings.Expires
  isExternal: true
- uid: Dropbox.Api.Sharing
  commentId: N:Dropbox.Api.Sharing
  name: Dropbox.Api.Sharing
  nameWithType: Dropbox.Api.Sharing
  fullName: Dropbox.Api.Sharing
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError
  commentId: T:Dropbox.Api.Sharing.SharedLinkSettingsError
  parent: Dropbox.Api.Sharing
  name: SharedLinkSettingsError
  nameWithType: SharedLinkSettingsError
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.IsInvalidSettings
  commentId: P:Dropbox.Api.Sharing.SharedLinkSettingsError.IsInvalidSettings
  parent: Dropbox.Api.Sharing.SharedLinkSettingsError
  name: IsInvalidSettings
  nameWithType: SharedLinkSettingsError.IsInvalidSettings
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.IsInvalidSettings
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.AsInvalidSettings
  commentId: P:Dropbox.Api.Sharing.SharedLinkSettingsError.AsInvalidSettings
  parent: Dropbox.Api.Sharing.SharedLinkSettingsError
  name: AsInvalidSettings
  nameWithType: SharedLinkSettingsError.AsInvalidSettings
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.AsInvalidSettings
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.IsNotAuthorized
  commentId: P:Dropbox.Api.Sharing.SharedLinkSettingsError.IsNotAuthorized
  parent: Dropbox.Api.Sharing.SharedLinkSettingsError
  name: IsNotAuthorized
  nameWithType: SharedLinkSettingsError.IsNotAuthorized
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.IsNotAuthorized
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.AsNotAuthorized
  commentId: P:Dropbox.Api.Sharing.SharedLinkSettingsError.AsNotAuthorized
  parent: Dropbox.Api.Sharing.SharedLinkSettingsError
  name: AsNotAuthorized
  nameWithType: SharedLinkSettingsError.AsNotAuthorized
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.AsNotAuthorized
- uid: Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings
  commentId: T:Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings
  parent: Dropbox.Api.Sharing
  name: SharedLinkSettingsError.InvalidSettings
  nameWithType: SharedLinkSettingsError.InvalidSettings
  fullName: Dropbox.Api.Sharing.SharedLinkSettingsError.InvalidSettings
shouldSkipMarkup: true
