### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails
  commentId: T:Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails
  id: SharedLinkSettingsChangeExpirationDetails
  parent: Dropbox.Api.TeamLog
  children:
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.#ctor
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.#ctor(Dropbox.Api.Sharing.AccessLevel,System.String,System.Nullable{System.DateTime},System.Nullable{System.DateTime})
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.NewValue
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.PreviousValue
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedContentAccessLevel
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedContentLink
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsChangeExpirationDetails
  nameWithType: SharedLinkSettingsChangeExpirationDetails
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeExpirationDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SharedLinkSettingsChangeExpirationDetails
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeExpirationDetails.cs
    startLine: 15
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Changed the expiration date of the shared link.</p>\n"
  example: []
  syntax:
    content: 'public class SharedLinkSettingsChangeExpirationDetails : object'
    content.vb: >-
      Public Class SharedLinkSettingsChangeExpirationDetails
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.#ctor(Dropbox.Api.Sharing.AccessLevel,System.String,System.Nullable{System.DateTime},System.Nullable{System.DateTime})
  commentId: M:Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.#ctor(Dropbox.Api.Sharing.AccessLevel,System.String,System.Nullable{System.DateTime},System.Nullable{System.DateTime})
  id: '#ctor(Dropbox.Api.Sharing.AccessLevel,System.String,System.Nullable{System.DateTime},System.Nullable{System.DateTime})'
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsChangeExpirationDetails(AccessLevel, String, Nullable<System.DateTime>, Nullable<System.DateTime>)
  nameWithType: SharedLinkSettingsChangeExpirationDetails.SharedLinkSettingsChangeExpirationDetails(AccessLevel, String, Nullable<System.DateTime>, Nullable<System.DateTime>)
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedLinkSettingsChangeExpirationDetails(Dropbox.Api.Sharing.AccessLevel, System.String, System.Nullable<System.DateTime>, System.Nullable<System.DateTime>)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeExpirationDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeExpirationDetails.cs
    startLine: 39
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  example: []
  syntax:
    content: public SharedLinkSettingsChangeExpirationDetails(AccessLevel sharedContentAccessLevel, string sharedContentLink = null, System.DateTime? newValue = null, System.DateTime? previousValue = null)
    parameters:
    - id: sharedContentAccessLevel
      type: Dropbox.Api.Sharing.AccessLevel
      description: Shared content access level.
    - id: sharedContentLink
      type: System.String
      description: Shared content link.
    - id: newValue
      type: System.Nullable{System.DateTime}
      description: >-
        New shared content link expiration date. Might be missing

        due to historical data gap.
    - id: previousValue
      type: System.Nullable{System.DateTime}
      description: >-
        Previous shared content link expiration date. Might be

        missing due to historical data gap.
    content.vb: Public Sub New(sharedContentAccessLevel As AccessLevel, sharedContentLink As String = Nothing, newValue As System.DateTime? = Nothing, previousValue As System.DateTime? = Nothing)
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.#ctor*
  nameWithType.vb: SharedLinkSettingsChangeExpirationDetails.SharedLinkSettingsChangeExpirationDetails(AccessLevel, String, Nullable(Of System.DateTime), Nullable(Of System.DateTime))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedLinkSettingsChangeExpirationDetails(Dropbox.Api.Sharing.AccessLevel, System.String, System.Nullable(Of System.DateTime), System.Nullable(Of System.DateTime))
  name.vb: SharedLinkSettingsChangeExpirationDetails(AccessLevel, String, Nullable(Of System.DateTime), Nullable(Of System.DateTime))
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.#ctor
  commentId: M:Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.#ctor
  id: '#ctor'
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsChangeExpirationDetails()
  nameWithType: SharedLinkSettingsChangeExpirationDetails.SharedLinkSettingsChangeExpirationDetails()
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedLinkSettingsChangeExpirationDetails()
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeExpirationDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeExpirationDetails.cs
    startLine: 61
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  remarks: >-
    This is to construct an instance of the object when

    deserializing.
  example: []
  syntax:
    content: public SharedLinkSettingsChangeExpirationDetails()
    content.vb: Public Sub New
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedContentAccessLevel
  commentId: P:Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedContentAccessLevel
  id: SharedContentAccessLevel
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails
  langs:
  - csharp
  - vb
  name: SharedContentAccessLevel
  nameWithType: SharedLinkSettingsChangeExpirationDetails.SharedContentAccessLevel
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedContentAccessLevel
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeExpirationDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SharedContentAccessLevel
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeExpirationDetails.cs
    startLine: 69
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Shared content access level.</p>\n"
  example: []
  syntax:
    content: public AccessLevel SharedContentAccessLevel { get; protected set; }
    parameters: []
    return:
      type: Dropbox.Api.Sharing.AccessLevel
    content.vb: Public Property SharedContentAccessLevel As AccessLevel
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedContentAccessLevel*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedContentLink
  commentId: P:Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedContentLink
  id: SharedContentLink
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails
  langs:
  - csharp
  - vb
  name: SharedContentLink
  nameWithType: SharedLinkSettingsChangeExpirationDetails.SharedContentLink
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedContentLink
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeExpirationDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SharedContentLink
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeExpirationDetails.cs
    startLine: 74
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Shared content link.</p>\n"
  example: []
  syntax:
    content: public string SharedContentLink { get; protected set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property SharedContentLink As String
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedContentLink*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.NewValue
  commentId: P:Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.NewValue
  id: NewValue
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails
  langs:
  - csharp
  - vb
  name: NewValue
  nameWithType: SharedLinkSettingsChangeExpirationDetails.NewValue
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.NewValue
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeExpirationDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: NewValue
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeExpirationDetails.cs
    startLine: 80
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>New shared content link expiration date. Might be missing due to historical\ndata gap.</p>\n"
  example: []
  syntax:
    content: public System.DateTime? NewValue { get; protected set; }
    parameters: []
    return:
      type: System.Nullable{System.DateTime}
    content.vb: Public Property NewValue As System.DateTime?
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.NewValue*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.PreviousValue
  commentId: P:Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.PreviousValue
  id: PreviousValue
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails
  langs:
  - csharp
  - vb
  name: PreviousValue
  nameWithType: SharedLinkSettingsChangeExpirationDetails.PreviousValue
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.PreviousValue
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeExpirationDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: PreviousValue
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangeExpirationDetails.cs
    startLine: 86
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Previous shared content link expiration date. Might be missing due to\nhistorical data gap.</p>\n"
  example: []
  syntax:
    content: public System.DateTime? PreviousValue { get; protected set; }
    parameters: []
    return:
      type: System.Nullable{System.DateTime}
    content.vb: Public Property PreviousValue As System.DateTime?
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.PreviousValue*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
references:
- uid: Dropbox.Api.TeamLog
  commentId: N:Dropbox.Api.TeamLog
  name: Dropbox.Api.TeamLog
  nameWithType: Dropbox.Api.TeamLog
  fullName: Dropbox.Api.TeamLog
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails
  commentId: T:Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails
  parent: Dropbox.Api.TeamLog
  name: SharedLinkSettingsChangeExpirationDetails
  nameWithType: SharedLinkSettingsChangeExpirationDetails
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.#ctor*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.#ctor
  name: SharedLinkSettingsChangeExpirationDetails
  nameWithType: SharedLinkSettingsChangeExpirationDetails.SharedLinkSettingsChangeExpirationDetails
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedLinkSettingsChangeExpirationDetails
- uid: Dropbox.Api.Sharing.AccessLevel
  commentId: T:Dropbox.Api.Sharing.AccessLevel
  parent: Dropbox.Api.Sharing
  name: AccessLevel
  nameWithType: AccessLevel
  fullName: Dropbox.Api.Sharing.AccessLevel
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Nullable{System.DateTime}
  commentId: '!:System.Nullable{System.DateTime}'
  definition: System.Nullable`1
  name: Nullable<System.DateTime>
  nameWithType: Nullable<System.DateTime>
  fullName: System.Nullable<System.DateTime>
  nameWithType.vb: Nullable(Of System.DateTime)
  fullName.vb: System.Nullable(Of System.DateTime)
  name.vb: Nullable(Of System.DateTime)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.DateTime
    name: System.DateTime
    nameWithType: System.DateTime
    fullName: System.DateTime
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.DateTime
    name: System.DateTime
    nameWithType: System.DateTime
    fullName: System.DateTime
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Dropbox.Api.Sharing
  commentId: N:Dropbox.Api.Sharing
  name: Dropbox.Api.Sharing
  nameWithType: Dropbox.Api.Sharing
  fullName: Dropbox.Api.Sharing
- uid: System.Nullable`1
  isExternal: true
  name: Nullable<>
  nameWithType: Nullable<>
  fullName: System.Nullable<>
  nameWithType.vb: Nullable(Of )
  fullName.vb: System.Nullable(Of )
  name.vb: Nullable(Of )
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedContentAccessLevel*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedContentAccessLevel
  name: SharedContentAccessLevel
  nameWithType: SharedLinkSettingsChangeExpirationDetails.SharedContentAccessLevel
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedContentAccessLevel
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedContentLink*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedContentLink
  name: SharedContentLink
  nameWithType: SharedLinkSettingsChangeExpirationDetails.SharedContentLink
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.SharedContentLink
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.NewValue*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.NewValue
  name: NewValue
  nameWithType: SharedLinkSettingsChangeExpirationDetails.NewValue
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.NewValue
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.PreviousValue*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.PreviousValue
  name: PreviousValue
  nameWithType: SharedLinkSettingsChangeExpirationDetails.PreviousValue
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangeExpirationDetails.PreviousValue
shouldSkipMarkup: true
