### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Users.Routes
  commentId: N:Dropbox.Api.Users.Routes
  id: Dropbox.Api.Users.Routes
  children:
  - Dropbox.Api.Users.Routes.UsersUserRoutes
  langs:
  - csharp
  - vb
  name: Dropbox.Api.Users.Routes
  nameWithType: Dropbox.Api.Users.Routes
  fullName: Dropbox.Api.Users.Routes
  type: Namespace
  assemblies:
  - Dropbox.Api
references:
- uid: Dropbox.Api.Users.Routes.UsersUserRoutes
  commentId: T:Dropbox.Api.Users.Routes.UsersUserRoutes
  parent: Dropbox.Api.Users.Routes
  name: UsersUserRoutes
  nameWithType: UsersUserRoutes
  fullName: Dropbox.Api.Users.Routes.UsersUserRoutes
- uid: Dropbox.Api.Users.Routes
  commentId: N:Dropbox.Api.Users.Routes
  name: Dropbox.Api.Users.Routes
  nameWithType: Dropbox.Api.Users.Routes
  fullName: Dropbox.Api.Users.Routes
shouldSkipMarkup: true
