### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType
  commentId: T:Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType
  id: TeamSelectiveSyncSettingsChangedType
  parent: Dropbox.Api.TeamLog
  children:
  - Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.#ctor
  - Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.#ctor(System.String)
  - Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.Description
  langs:
  - csharp
  - vb
  name: TeamSelectiveSyncSettingsChangedType
  nameWithType: TeamSelectiveSyncSettingsChangedType
  fullName: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TeamSelectiveSyncSettingsChangedType.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: TeamSelectiveSyncSettingsChangedType
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TeamSelectiveSyncSettingsChangedType.cs
    startLine: 15
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>The team selective sync settings changed type object</p>\n"
  example: []
  syntax:
    content: 'public class TeamSelectiveSyncSettingsChangedType : object'
    content.vb: >-
      Public Class TeamSelectiveSyncSettingsChangedType
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.#ctor(System.String)
  commentId: M:Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType
  langs:
  - csharp
  - vb
  name: TeamSelectiveSyncSettingsChangedType(String)
  nameWithType: TeamSelectiveSyncSettingsChangedType.TeamSelectiveSyncSettingsChangedType(String)
  fullName: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.TeamSelectiveSyncSettingsChangedType(System.String)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TeamSelectiveSyncSettingsChangedType.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TeamSelectiveSyncSettingsChangedType.cs
    startLine: 34
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  example: []
  syntax:
    content: public TeamSelectiveSyncSettingsChangedType(string description)
    parameters:
    - id: description
      type: System.String
      description: The description
    content.vb: Public Sub New(description As String)
  overload: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.#ctor
  commentId: M:Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.#ctor
  id: '#ctor'
  parent: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType
  langs:
  - csharp
  - vb
  name: TeamSelectiveSyncSettingsChangedType()
  nameWithType: TeamSelectiveSyncSettingsChangedType.TeamSelectiveSyncSettingsChangedType()
  fullName: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.TeamSelectiveSyncSettingsChangedType()
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TeamSelectiveSyncSettingsChangedType.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TeamSelectiveSyncSettingsChangedType.cs
    startLine: 50
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  remarks: >-
    This is to construct an instance of the object when

    deserializing.
  example: []
  syntax:
    content: public TeamSelectiveSyncSettingsChangedType()
    content.vb: Public Sub New
  overload: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.Description
  commentId: P:Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.Description
  id: Description
  parent: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType
  langs:
  - csharp
  - vb
  name: Description
  nameWithType: TeamSelectiveSyncSettingsChangedType.Description
  fullName: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.Description
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TeamSelectiveSyncSettingsChangedType.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Description
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/TeamSelectiveSyncSettingsChangedType.cs
    startLine: 58
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Gets the description of the team selective sync settings changed type</p>\n"
  example: []
  syntax:
    content: public string Description { get; protected set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Description As String
  overload: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.Description*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
references:
- uid: Dropbox.Api.TeamLog
  commentId: N:Dropbox.Api.TeamLog
  name: Dropbox.Api.TeamLog
  nameWithType: Dropbox.Api.TeamLog
  fullName: Dropbox.Api.TeamLog
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType
  commentId: T:Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType
  parent: Dropbox.Api.TeamLog
  name: TeamSelectiveSyncSettingsChangedType
  nameWithType: TeamSelectiveSyncSettingsChangedType
  fullName: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType
- uid: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.#ctor*
  commentId: Overload:Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.#ctor
  name: TeamSelectiveSyncSettingsChangedType
  nameWithType: TeamSelectiveSyncSettingsChangedType.TeamSelectiveSyncSettingsChangedType
  fullName: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.TeamSelectiveSyncSettingsChangedType
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.Description*
  commentId: Overload:Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.Description
  name: Description
  nameWithType: TeamSelectiveSyncSettingsChangedType.Description
  fullName: Dropbox.Api.TeamLog.TeamSelectiveSyncSettingsChangedType.Description
shouldSkipMarkup: true
