### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType
  commentId: T:Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType
  id: SharedLinkSettingsChangePasswordType
  parent: Dropbox.Api.TeamLog
  children:
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.#ctor
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.#ctor(System.String)
  - Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.Description
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsChangePasswordType
  nameWithType: SharedLinkSettingsChangePasswordType
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangePasswordType.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SharedLinkSettingsChangePasswordType
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangePasswordType.cs
    startLine: 15
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>The shared link settings change password type object</p>\n"
  example: []
  syntax:
    content: 'public class SharedLinkSettingsChangePasswordType : object'
    content.vb: >-
      Public Class SharedLinkSettingsChangePasswordType
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.#ctor(System.String)
  commentId: M:Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsChangePasswordType(String)
  nameWithType: SharedLinkSettingsChangePasswordType.SharedLinkSettingsChangePasswordType(String)
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.SharedLinkSettingsChangePasswordType(System.String)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangePasswordType.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangePasswordType.cs
    startLine: 34
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  example: []
  syntax:
    content: public SharedLinkSettingsChangePasswordType(string description)
    parameters:
    - id: description
      type: System.String
      description: The description
    content.vb: Public Sub New(description As String)
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.#ctor
  commentId: M:Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.#ctor
  id: '#ctor'
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsChangePasswordType()
  nameWithType: SharedLinkSettingsChangePasswordType.SharedLinkSettingsChangePasswordType()
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.SharedLinkSettingsChangePasswordType()
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangePasswordType.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangePasswordType.cs
    startLine: 50
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  remarks: >-
    This is to construct an instance of the object when

    deserializing.
  example: []
  syntax:
    content: public SharedLinkSettingsChangePasswordType()
    content.vb: Public Sub New
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.Description
  commentId: P:Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.Description
  id: Description
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType
  langs:
  - csharp
  - vb
  name: Description
  nameWithType: SharedLinkSettingsChangePasswordType.Description
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.Description
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangePasswordType.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Description
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsChangePasswordType.cs
    startLine: 58
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Gets the description of the shared link settings change password type</p>\n"
  example: []
  syntax:
    content: public string Description { get; protected set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Description As String
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.Description*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
references:
- uid: Dropbox.Api.TeamLog
  commentId: N:Dropbox.Api.TeamLog
  name: Dropbox.Api.TeamLog
  nameWithType: Dropbox.Api.TeamLog
  fullName: Dropbox.Api.TeamLog
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType
  commentId: T:Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType
  parent: Dropbox.Api.TeamLog
  name: SharedLinkSettingsChangePasswordType
  nameWithType: SharedLinkSettingsChangePasswordType
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.#ctor*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.#ctor
  name: SharedLinkSettingsChangePasswordType
  nameWithType: SharedLinkSettingsChangePasswordType.SharedLinkSettingsChangePasswordType
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.SharedLinkSettingsChangePasswordType
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.Description*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.Description
  name: Description
  nameWithType: SharedLinkSettingsChangePasswordType.Description
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsChangePasswordType.Description
shouldSkipMarkup: true
