### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError
  commentId: T:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError
  id: TeamFolderUpdateSyncSettingsError.StatusError
  parent: Dropbox.Api.Team
  children:
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError.#ctor(Dropbox.Api.Team.TeamFolderInvalidStatusError)
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError.Value
  langs:
  - csharp
  - vb
  name: TeamFolderUpdateSyncSettingsError.StatusError
  nameWithType: TeamFolderUpdateSyncSettingsError.StatusError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: StatusError
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsError.cs
    startLine: 443
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>The status error object</p>\n"
  example: []
  syntax:
    content: 'public sealed class StatusError : TeamFolderUpdateSyncSettingsError'
    content.vb: >-
      Public NotInheritable Class StatusError
          Inherits TeamFolderUpdateSyncSettingsError
  inheritance:
  - System.Object
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  inheritedMembers:
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsSyncSettingsError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsSyncSettingsError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsAccessError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsAccessError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsStatusError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsStatusError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsTeamSharedDropboxError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsTeamSharedDropboxError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsOther
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsOther
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError.#ctor(Dropbox.Api.Team.TeamFolderInvalidStatusError)
  commentId: M:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError.#ctor(Dropbox.Api.Team.TeamFolderInvalidStatusError)
  id: '#ctor(Dropbox.Api.Team.TeamFolderInvalidStatusError)'
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError
  langs:
  - csharp
  - vb
  name: StatusError(TeamFolderInvalidStatusError)
  nameWithType: TeamFolderUpdateSyncSettingsError.StatusError.StatusError(TeamFolderInvalidStatusError)
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError.StatusError(Dropbox.Api.Team.TeamFolderInvalidStatusError)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsError.cs
    startLine: 462
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError\" data-throw-if-not-resolved=\"false\"></xref>\nclass.</p>\n"
  example: []
  syntax:
    content: public StatusError(TeamFolderInvalidStatusError value)
    parameters:
    - id: value
      type: Dropbox.Api.Team.TeamFolderInvalidStatusError
      description: The value
    content.vb: Public Sub New(value As TeamFolderInvalidStatusError)
  overload: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError.Value
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError.Value
  id: Value
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: TeamFolderUpdateSyncSettingsError.StatusError.Value
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError.Value
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Value
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsError.cs
    startLine: 477
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>Gets the value of this instance.</p>\n"
  example: []
  syntax:
    content: public TeamFolderInvalidStatusError Value { get; }
    parameters: []
    return:
      type: Dropbox.Api.Team.TeamFolderInvalidStatusError
    content.vb: Public ReadOnly Property Value As TeamFolderInvalidStatusError
  overload: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError.Value*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Dropbox.Api.Team
  commentId: N:Dropbox.Api.Team
  name: Dropbox.Api.Team
  nameWithType: Dropbox.Api.Team
  fullName: Dropbox.Api.Team
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  commentId: T:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  parent: Dropbox.Api.Team
  name: TeamFolderUpdateSyncSettingsError
  nameWithType: TeamFolderUpdateSyncSettingsError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsSyncSettingsError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsSyncSettingsError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: IsSyncSettingsError
  nameWithType: TeamFolderUpdateSyncSettingsError.IsSyncSettingsError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsSyncSettingsError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsSyncSettingsError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsSyncSettingsError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: AsSyncSettingsError
  nameWithType: TeamFolderUpdateSyncSettingsError.AsSyncSettingsError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsSyncSettingsError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsAccessError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsAccessError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: IsAccessError
  nameWithType: TeamFolderUpdateSyncSettingsError.IsAccessError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsAccessError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsAccessError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsAccessError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: AsAccessError
  nameWithType: TeamFolderUpdateSyncSettingsError.AsAccessError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsAccessError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsStatusError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsStatusError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: IsStatusError
  nameWithType: TeamFolderUpdateSyncSettingsError.IsStatusError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsStatusError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsStatusError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsStatusError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: AsStatusError
  nameWithType: TeamFolderUpdateSyncSettingsError.AsStatusError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsStatusError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsTeamSharedDropboxError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsTeamSharedDropboxError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: IsTeamSharedDropboxError
  nameWithType: TeamFolderUpdateSyncSettingsError.IsTeamSharedDropboxError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsTeamSharedDropboxError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsTeamSharedDropboxError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsTeamSharedDropboxError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: AsTeamSharedDropboxError
  nameWithType: TeamFolderUpdateSyncSettingsError.AsTeamSharedDropboxError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsTeamSharedDropboxError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsOther
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsOther
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: IsOther
  nameWithType: TeamFolderUpdateSyncSettingsError.IsOther
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsOther
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsOther
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsOther
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: AsOther
  nameWithType: TeamFolderUpdateSyncSettingsError.AsOther
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsOther
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError
  commentId: T:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError
  parent: Dropbox.Api.Team
  name: TeamFolderUpdateSyncSettingsError.StatusError
  nameWithType: TeamFolderUpdateSyncSettingsError.StatusError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError.#ctor*
  commentId: Overload:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError.#ctor
  name: StatusError
  nameWithType: TeamFolderUpdateSyncSettingsError.StatusError.StatusError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError.StatusError
- uid: Dropbox.Api.Team.TeamFolderInvalidStatusError
  commentId: T:Dropbox.Api.Team.TeamFolderInvalidStatusError
  parent: Dropbox.Api.Team
  name: TeamFolderInvalidStatusError
  nameWithType: TeamFolderInvalidStatusError
  fullName: Dropbox.Api.Team.TeamFolderInvalidStatusError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError.Value*
  commentId: Overload:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError.Value
  name: Value
  nameWithType: TeamFolderUpdateSyncSettingsError.StatusError.Value
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.StatusError.Value
shouldSkipMarkup: true
