### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchError.EmptyFeaturesList
  commentId: T:Dropbox.Api.Team.FeaturesGetValuesBatchError.EmptyFeaturesList
  id: FeaturesGetValuesBatchError.EmptyFeaturesList
  parent: Dropbox.Api.Team
  children:
  - Dropbox.Api.Team.FeaturesGetValuesBatchError.EmptyFeaturesList.Instance
  langs:
  - csharp
  - vb
  name: FeaturesGetValuesBatchError.EmptyFeaturesList
  nameWithType: FeaturesGetValuesBatchError.EmptyFeaturesList
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchError.EmptyFeaturesList
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/FeaturesGetValuesBatchError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: EmptyFeaturesList
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/FeaturesGetValuesBatchError.cs
    startLine: 154
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>At least one <xref href=\"Dropbox.Api.Team.Feature\" data-throw-if-not-resolved=\"false\"></xref> must be included in the <xref href=\"Dropbox.Api.Team.FeaturesGetValuesBatchArg\" data-throw-if-not-resolved=\"false\"></xref>.features list.</p>\n"
  example: []
  syntax:
    content: 'public sealed class EmptyFeaturesList : FeaturesGetValuesBatchError'
    content.vb: >-
      Public NotInheritable Class EmptyFeaturesList
          Inherits FeaturesGetValuesBatchError
  inheritance:
  - System.Object
  - Dropbox.Api.Team.FeaturesGetValuesBatchError
  inheritedMembers:
  - Dropbox.Api.Team.FeaturesGetValuesBatchError.IsEmptyFeaturesList
  - Dropbox.Api.Team.FeaturesGetValuesBatchError.AsEmptyFeaturesList
  - Dropbox.Api.Team.FeaturesGetValuesBatchError.IsOther
  - Dropbox.Api.Team.FeaturesGetValuesBatchError.AsOther
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchError.EmptyFeaturesList.Instance
  commentId: F:Dropbox.Api.Team.FeaturesGetValuesBatchError.EmptyFeaturesList.Instance
  id: Instance
  parent: Dropbox.Api.Team.FeaturesGetValuesBatchError.EmptyFeaturesList
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: FeaturesGetValuesBatchError.EmptyFeaturesList.Instance
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchError.EmptyFeaturesList.Instance
  type: Field
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/FeaturesGetValuesBatchError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Instance
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/FeaturesGetValuesBatchError.cs
    startLine: 179
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>A singleton instance of EmptyFeaturesList</p>\n"
  example: []
  syntax:
    content: public static readonly FeaturesGetValuesBatchError.EmptyFeaturesList Instance
    return:
      type: Dropbox.Api.Team.FeaturesGetValuesBatchError.EmptyFeaturesList
    content.vb: Public Shared ReadOnly Instance As FeaturesGetValuesBatchError.EmptyFeaturesList
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: Dropbox.Api.Team.Feature
  commentId: T:Dropbox.Api.Team.Feature
  parent: Dropbox.Api.Team
  name: Feature
  nameWithType: Feature
  fullName: Dropbox.Api.Team.Feature
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchArg
  commentId: T:Dropbox.Api.Team.FeaturesGetValuesBatchArg
  parent: Dropbox.Api.Team
  name: FeaturesGetValuesBatchArg
  nameWithType: FeaturesGetValuesBatchArg
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchArg
- uid: Dropbox.Api.Team
  commentId: N:Dropbox.Api.Team
  name: Dropbox.Api.Team
  nameWithType: Dropbox.Api.Team
  fullName: Dropbox.Api.Team
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchError
  commentId: T:Dropbox.Api.Team.FeaturesGetValuesBatchError
  parent: Dropbox.Api.Team
  name: FeaturesGetValuesBatchError
  nameWithType: FeaturesGetValuesBatchError
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchError
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchError.IsEmptyFeaturesList
  commentId: P:Dropbox.Api.Team.FeaturesGetValuesBatchError.IsEmptyFeaturesList
  parent: Dropbox.Api.Team.FeaturesGetValuesBatchError
  name: IsEmptyFeaturesList
  nameWithType: FeaturesGetValuesBatchError.IsEmptyFeaturesList
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchError.IsEmptyFeaturesList
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchError.AsEmptyFeaturesList
  commentId: P:Dropbox.Api.Team.FeaturesGetValuesBatchError.AsEmptyFeaturesList
  parent: Dropbox.Api.Team.FeaturesGetValuesBatchError
  name: AsEmptyFeaturesList
  nameWithType: FeaturesGetValuesBatchError.AsEmptyFeaturesList
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchError.AsEmptyFeaturesList
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchError.IsOther
  commentId: P:Dropbox.Api.Team.FeaturesGetValuesBatchError.IsOther
  parent: Dropbox.Api.Team.FeaturesGetValuesBatchError
  name: IsOther
  nameWithType: FeaturesGetValuesBatchError.IsOther
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchError.IsOther
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchError.AsOther
  commentId: P:Dropbox.Api.Team.FeaturesGetValuesBatchError.AsOther
  parent: Dropbox.Api.Team.FeaturesGetValuesBatchError
  name: AsOther
  nameWithType: FeaturesGetValuesBatchError.AsOther
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchError.AsOther
- uid: Dropbox.Api.Team.FeaturesGetValuesBatchError.EmptyFeaturesList
  commentId: T:Dropbox.Api.Team.FeaturesGetValuesBatchError.EmptyFeaturesList
  parent: Dropbox.Api.Team
  name: FeaturesGetValuesBatchError.EmptyFeaturesList
  nameWithType: FeaturesGetValuesBatchError.EmptyFeaturesList
  fullName: Dropbox.Api.Team.FeaturesGetValuesBatchError.EmptyFeaturesList
shouldSkipMarkup: true
