### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path
  commentId: T:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path
  id: CreateSharedLinkWithSettingsError.Path
  parent: Dropbox.Api.Sharing
  children:
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path.#ctor(Dropbox.Api.Files.LookupError)
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path.Value
  langs:
  - csharp
  - vb
  name: CreateSharedLinkWithSettingsError.Path
  nameWithType: CreateSharedLinkWithSettingsError.Path
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Path
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsError.cs
    startLine: 246
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>The path object</p>\n"
  example: []
  syntax:
    content: 'public sealed class Path : CreateSharedLinkWithSettingsError'
    content.vb: >-
      Public NotInheritable Class Path
          Inherits CreateSharedLinkWithSettingsError
  inheritance:
  - System.Object
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  inheritedMembers:
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsPath
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsPath
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsEmailNotVerified
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsEmailNotVerified
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSharedLinkAlreadyExists
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSharedLinkAlreadyExists
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSettingsError
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSettingsError
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsAccessDenied
  - Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsAccessDenied
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path.#ctor(Dropbox.Api.Files.LookupError)
  commentId: M:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path.#ctor(Dropbox.Api.Files.LookupError)
  id: '#ctor(Dropbox.Api.Files.LookupError)'
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path
  langs:
  - csharp
  - vb
  name: Path(LookupError)
  nameWithType: CreateSharedLinkWithSettingsError.Path.Path(LookupError)
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path.Path(Dropbox.Api.Files.LookupError)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsError.cs
    startLine: 264
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  example: []
  syntax:
    content: public Path(LookupError value)
    parameters:
    - id: value
      type: Dropbox.Api.Files.LookupError
      description: The value
    content.vb: Public Sub New(value As LookupError)
  overload: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path.Value
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path.Value
  id: Value
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: CreateSharedLinkWithSettingsError.Path.Value
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path.Value
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Value
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/CreateSharedLinkWithSettingsError.cs
    startLine: 278
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>Gets the value of this instance.</p>\n"
  example: []
  syntax:
    content: public LookupError Value { get; }
    parameters: []
    return:
      type: Dropbox.Api.Files.LookupError
    content.vb: Public ReadOnly Property Value As LookupError
  overload: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path.Value*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Dropbox.Api.Sharing
  commentId: N:Dropbox.Api.Sharing
  name: Dropbox.Api.Sharing
  nameWithType: Dropbox.Api.Sharing
  fullName: Dropbox.Api.Sharing
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  commentId: T:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  parent: Dropbox.Api.Sharing
  name: CreateSharedLinkWithSettingsError
  nameWithType: CreateSharedLinkWithSettingsError
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsPath
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsPath
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: IsPath
  nameWithType: CreateSharedLinkWithSettingsError.IsPath
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsPath
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsPath
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsPath
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: AsPath
  nameWithType: CreateSharedLinkWithSettingsError.AsPath
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsPath
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsEmailNotVerified
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsEmailNotVerified
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: IsEmailNotVerified
  nameWithType: CreateSharedLinkWithSettingsError.IsEmailNotVerified
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsEmailNotVerified
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsEmailNotVerified
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsEmailNotVerified
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: AsEmailNotVerified
  nameWithType: CreateSharedLinkWithSettingsError.AsEmailNotVerified
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsEmailNotVerified
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSharedLinkAlreadyExists
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSharedLinkAlreadyExists
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: IsSharedLinkAlreadyExists
  nameWithType: CreateSharedLinkWithSettingsError.IsSharedLinkAlreadyExists
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSharedLinkAlreadyExists
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSharedLinkAlreadyExists
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSharedLinkAlreadyExists
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: AsSharedLinkAlreadyExists
  nameWithType: CreateSharedLinkWithSettingsError.AsSharedLinkAlreadyExists
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSharedLinkAlreadyExists
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSettingsError
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSettingsError
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: IsSettingsError
  nameWithType: CreateSharedLinkWithSettingsError.IsSettingsError
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsSettingsError
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSettingsError
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSettingsError
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: AsSettingsError
  nameWithType: CreateSharedLinkWithSettingsError.AsSettingsError
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsSettingsError
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsAccessDenied
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsAccessDenied
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: IsAccessDenied
  nameWithType: CreateSharedLinkWithSettingsError.IsAccessDenied
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.IsAccessDenied
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsAccessDenied
  commentId: P:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsAccessDenied
  parent: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError
  name: AsAccessDenied
  nameWithType: CreateSharedLinkWithSettingsError.AsAccessDenied
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.AsAccessDenied
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path
  commentId: T:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path
  parent: Dropbox.Api.Sharing
  name: CreateSharedLinkWithSettingsError.Path
  nameWithType: CreateSharedLinkWithSettingsError.Path
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path.#ctor*
  commentId: Overload:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path.#ctor
  name: Path
  nameWithType: CreateSharedLinkWithSettingsError.Path.Path
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path.Path
- uid: Dropbox.Api.Files.LookupError
  commentId: T:Dropbox.Api.Files.LookupError
  parent: Dropbox.Api.Files
  name: LookupError
  nameWithType: LookupError
  fullName: Dropbox.Api.Files.LookupError
- uid: Dropbox.Api.Files
  commentId: N:Dropbox.Api.Files
  name: Dropbox.Api.Files
  nameWithType: Dropbox.Api.Files
  fullName: Dropbox.Api.Files
- uid: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path.Value*
  commentId: Overload:Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path.Value
  name: Value
  nameWithType: CreateSharedLinkWithSettingsError.Path.Value
  fullName: Dropbox.Api.Sharing.CreateSharedLinkWithSettingsError.Path.Value
shouldSkipMarkup: true
