### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.TeamLog.Routes
  commentId: N:Dropbox.Api.TeamLog.Routes
  id: Dropbox.Api.TeamLog.Routes
  children:
  - Dropbox.Api.TeamLog.Routes.TeamLogTeamRoutes
  langs:
  - csharp
  - vb
  name: Dropbox.Api.TeamLog.Routes
  nameWithType: Dropbox.Api.TeamLog.Routes
  fullName: Dropbox.Api.TeamLog.Routes
  type: Namespace
  assemblies:
  - Dropbox.Api
references:
- uid: Dropbox.Api.TeamLog.Routes.TeamLogTeamRoutes
  commentId: T:Dropbox.Api.TeamLog.Routes.TeamLogTeamRoutes
  parent: Dropbox.Api.TeamLog.Routes
  name: TeamLogTeamRoutes
  nameWithType: TeamLogTeamRoutes
  fullName: Dropbox.Api.TeamLog.Routes.TeamLogTeamRoutes
- uid: Dropbox.Api.TeamLog.Routes
  commentId: N:Dropbox.Api.TeamLog.Routes
  name: Dropbox.Api.TeamLog.Routes
  nameWithType: Dropbox.Api.TeamLog.Routes
  fullName: Dropbox.Api.TeamLog.Routes
shouldSkipMarkup: true
