### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError
  commentId: T:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError
  id: TeamFolderUpdateSyncSettingsError.SyncSettingsError
  parent: Dropbox.Api.Team
  children:
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError.#ctor(Dropbox.Api.Files.SyncSettingsError)
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError.Value
  langs:
  - csharp
  - vb
  name: TeamFolderUpdateSyncSettingsError.SyncSettingsError
  nameWithType: TeamFolderUpdateSyncSettingsError.SyncSettingsError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SyncSettingsError
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsError.cs
    startLine: 246
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>An error occurred setting the sync settings.</p>\n"
  example: []
  syntax:
    content: 'public sealed class SyncSettingsError : TeamFolderUpdateSyncSettingsError'
    content.vb: >-
      Public NotInheritable Class SyncSettingsError
          Inherits TeamFolderUpdateSyncSettingsError
  inheritance:
  - System.Object
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  inheritedMembers:
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsSyncSettingsError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsSyncSettingsError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsAccessError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsAccessError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsStatusError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsStatusError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsTeamSharedDropboxError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsTeamSharedDropboxError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsOther
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsOther
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError.#ctor(Dropbox.Api.Files.SyncSettingsError)
  commentId: M:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError.#ctor(Dropbox.Api.Files.SyncSettingsError)
  id: '#ctor(Dropbox.Api.Files.SyncSettingsError)'
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError
  langs:
  - csharp
  - vb
  name: SyncSettingsError(SyncSettingsError)
  nameWithType: TeamFolderUpdateSyncSettingsError.SyncSettingsError.SyncSettingsError(SyncSettingsError)
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError.SyncSettingsError(Dropbox.Api.Files.SyncSettingsError)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsError.cs
    startLine: 265
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError\" data-throw-if-not-resolved=\"false\"></xref>\nclass.</p>\n"
  example: []
  syntax:
    content: public SyncSettingsError(SyncSettingsError value)
    parameters:
    - id: value
      type: Dropbox.Api.Files.SyncSettingsError
      description: The value
    content.vb: Public Sub New(value As SyncSettingsError)
  overload: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError.Value
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError.Value
  id: Value
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: TeamFolderUpdateSyncSettingsError.SyncSettingsError.Value
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError.Value
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Value
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsError.cs
    startLine: 280
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>Gets the value of this instance.</p>\n"
  example: []
  syntax:
    content: public SyncSettingsError Value { get; }
    parameters: []
    return:
      type: Dropbox.Api.Files.SyncSettingsError
    content.vb: Public ReadOnly Property Value As SyncSettingsError
  overload: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError.Value*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Dropbox.Api.Team
  commentId: N:Dropbox.Api.Team
  name: Dropbox.Api.Team
  nameWithType: Dropbox.Api.Team
  fullName: Dropbox.Api.Team
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  commentId: T:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  parent: Dropbox.Api.Team
  name: TeamFolderUpdateSyncSettingsError
  nameWithType: TeamFolderUpdateSyncSettingsError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsSyncSettingsError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsSyncSettingsError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: IsSyncSettingsError
  nameWithType: TeamFolderUpdateSyncSettingsError.IsSyncSettingsError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsSyncSettingsError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsSyncSettingsError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsSyncSettingsError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: AsSyncSettingsError
  nameWithType: TeamFolderUpdateSyncSettingsError.AsSyncSettingsError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsSyncSettingsError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsAccessError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsAccessError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: IsAccessError
  nameWithType: TeamFolderUpdateSyncSettingsError.IsAccessError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsAccessError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsAccessError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsAccessError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: AsAccessError
  nameWithType: TeamFolderUpdateSyncSettingsError.AsAccessError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsAccessError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsStatusError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsStatusError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: IsStatusError
  nameWithType: TeamFolderUpdateSyncSettingsError.IsStatusError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsStatusError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsStatusError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsStatusError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: AsStatusError
  nameWithType: TeamFolderUpdateSyncSettingsError.AsStatusError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsStatusError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsTeamSharedDropboxError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsTeamSharedDropboxError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: IsTeamSharedDropboxError
  nameWithType: TeamFolderUpdateSyncSettingsError.IsTeamSharedDropboxError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsTeamSharedDropboxError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsTeamSharedDropboxError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsTeamSharedDropboxError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: AsTeamSharedDropboxError
  nameWithType: TeamFolderUpdateSyncSettingsError.AsTeamSharedDropboxError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsTeamSharedDropboxError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsOther
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsOther
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: IsOther
  nameWithType: TeamFolderUpdateSyncSettingsError.IsOther
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsOther
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsOther
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsOther
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: AsOther
  nameWithType: TeamFolderUpdateSyncSettingsError.AsOther
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsOther
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError
  commentId: T:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError
  parent: Dropbox.Api.Team
  name: TeamFolderUpdateSyncSettingsError.SyncSettingsError
  nameWithType: TeamFolderUpdateSyncSettingsError.SyncSettingsError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError.#ctor*
  commentId: Overload:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError.#ctor
  name: SyncSettingsError
  nameWithType: TeamFolderUpdateSyncSettingsError.SyncSettingsError.SyncSettingsError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError.SyncSettingsError
- uid: Dropbox.Api.Files.SyncSettingsError
  commentId: T:Dropbox.Api.Files.SyncSettingsError
  parent: Dropbox.Api.Files
  name: SyncSettingsError
  nameWithType: SyncSettingsError
  fullName: Dropbox.Api.Files.SyncSettingsError
- uid: Dropbox.Api.Files
  commentId: N:Dropbox.Api.Files
  name: Dropbox.Api.Files
  nameWithType: Dropbox.Api.Files
  fullName: Dropbox.Api.Files
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError.Value*
  commentId: Overload:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError.Value
  name: Value
  nameWithType: TeamFolderUpdateSyncSettingsError.SyncSettingsError.Value
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.SyncSettingsError.Value
shouldSkipMarkup: true
