### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails
  commentId: T:Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails
  id: SharedLinkSettingsAllowDownloadDisabledDetails
  parent: Dropbox.Api.TeamLog
  children:
  - Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.#ctor
  - Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.#ctor(Dropbox.Api.Sharing.AccessLevel,System.String)
  - Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentAccessLevel
  - Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentLink
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsAllowDownloadDisabledDetails
  nameWithType: SharedLinkSettingsAllowDownloadDisabledDetails
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsAllowDownloadDisabledDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SharedLinkSettingsAllowDownloadDisabledDetails
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsAllowDownloadDisabledDetails.cs
    startLine: 15
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Disabled downloads.</p>\n"
  example: []
  syntax:
    content: 'public class SharedLinkSettingsAllowDownloadDisabledDetails : object'
    content.vb: >-
      Public Class SharedLinkSettingsAllowDownloadDisabledDetails
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.#ctor(Dropbox.Api.Sharing.AccessLevel,System.String)
  commentId: M:Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.#ctor(Dropbox.Api.Sharing.AccessLevel,System.String)
  id: '#ctor(Dropbox.Api.Sharing.AccessLevel,System.String)'
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsAllowDownloadDisabledDetails(AccessLevel, String)
  nameWithType: SharedLinkSettingsAllowDownloadDisabledDetails.SharedLinkSettingsAllowDownloadDisabledDetails(AccessLevel, String)
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedLinkSettingsAllowDownloadDisabledDetails(Dropbox.Api.Sharing.AccessLevel, System.String)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsAllowDownloadDisabledDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsAllowDownloadDisabledDetails.cs
    startLine: 35
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  example: []
  syntax:
    content: public SharedLinkSettingsAllowDownloadDisabledDetails(AccessLevel sharedContentAccessLevel, string sharedContentLink = null)
    parameters:
    - id: sharedContentAccessLevel
      type: Dropbox.Api.Sharing.AccessLevel
      description: Shared content access level.
    - id: sharedContentLink
      type: System.String
      description: Shared content link.
    content.vb: Public Sub New(sharedContentAccessLevel As AccessLevel, sharedContentLink As String = Nothing)
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.#ctor
  commentId: M:Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.#ctor
  id: '#ctor'
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails
  langs:
  - csharp
  - vb
  name: SharedLinkSettingsAllowDownloadDisabledDetails()
  nameWithType: SharedLinkSettingsAllowDownloadDisabledDetails.SharedLinkSettingsAllowDownloadDisabledDetails()
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedLinkSettingsAllowDownloadDisabledDetails()
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsAllowDownloadDisabledDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsAllowDownloadDisabledDetails.cs
    startLine: 53
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  remarks: >-
    This is to construct an instance of the object when

    deserializing.
  example: []
  syntax:
    content: public SharedLinkSettingsAllowDownloadDisabledDetails()
    content.vb: Public Sub New
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentAccessLevel
  commentId: P:Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentAccessLevel
  id: SharedContentAccessLevel
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails
  langs:
  - csharp
  - vb
  name: SharedContentAccessLevel
  nameWithType: SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentAccessLevel
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentAccessLevel
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsAllowDownloadDisabledDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SharedContentAccessLevel
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsAllowDownloadDisabledDetails.cs
    startLine: 61
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Shared content access level.</p>\n"
  example: []
  syntax:
    content: public AccessLevel SharedContentAccessLevel { get; protected set; }
    parameters: []
    return:
      type: Dropbox.Api.Sharing.AccessLevel
    content.vb: Public Property SharedContentAccessLevel As AccessLevel
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentAccessLevel*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentLink
  commentId: P:Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentLink
  id: SharedContentLink
  parent: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails
  langs:
  - csharp
  - vb
  name: SharedContentLink
  nameWithType: SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentLink
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentLink
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsAllowDownloadDisabledDetails.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: SharedContentLink
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/TeamLog/SharedLinkSettingsAllowDownloadDisabledDetails.cs
    startLine: 66
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.TeamLog
  summary: "\n<p>Shared content link.</p>\n"
  example: []
  syntax:
    content: public string SharedContentLink { get; protected set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property SharedContentLink As String
  overload: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentLink*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
references:
- uid: Dropbox.Api.TeamLog
  commentId: N:Dropbox.Api.TeamLog
  name: Dropbox.Api.TeamLog
  nameWithType: Dropbox.Api.TeamLog
  fullName: Dropbox.Api.TeamLog
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails
  commentId: T:Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails
  parent: Dropbox.Api.TeamLog
  name: SharedLinkSettingsAllowDownloadDisabledDetails
  nameWithType: SharedLinkSettingsAllowDownloadDisabledDetails
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.#ctor*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.#ctor
  name: SharedLinkSettingsAllowDownloadDisabledDetails
  nameWithType: SharedLinkSettingsAllowDownloadDisabledDetails.SharedLinkSettingsAllowDownloadDisabledDetails
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedLinkSettingsAllowDownloadDisabledDetails
- uid: Dropbox.Api.Sharing.AccessLevel
  commentId: T:Dropbox.Api.Sharing.AccessLevel
  parent: Dropbox.Api.Sharing
  name: AccessLevel
  nameWithType: AccessLevel
  fullName: Dropbox.Api.Sharing.AccessLevel
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Dropbox.Api.Sharing
  commentId: N:Dropbox.Api.Sharing
  name: Dropbox.Api.Sharing
  nameWithType: Dropbox.Api.Sharing
  fullName: Dropbox.Api.Sharing
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentAccessLevel*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentAccessLevel
  name: SharedContentAccessLevel
  nameWithType: SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentAccessLevel
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentAccessLevel
- uid: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentLink*
  commentId: Overload:Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentLink
  name: SharedContentLink
  nameWithType: SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentLink
  fullName: Dropbox.Api.TeamLog.SharedLinkSettingsAllowDownloadDisabledDetails.SharedContentLink
shouldSkipMarkup: true
