### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Account.Routes
  commentId: N:Dropbox.Api.Account.Routes
  id: Dropbox.Api.Account.Routes
  children:
  - Dropbox.Api.Account.Routes.AccountUserRoutes
  langs:
  - csharp
  - vb
  name: Dropbox.Api.Account.Routes
  nameWithType: Dropbox.Api.Account.Routes
  fullName: Dropbox.Api.Account.Routes
  type: Namespace
  assemblies:
  - Dropbox.Api
references:
- uid: Dropbox.Api.Account.Routes.AccountUserRoutes
  commentId: T:Dropbox.Api.Account.Routes.AccountUserRoutes
  parent: Dropbox.Api.Account.Routes
  name: AccountUserRoutes
  nameWithType: AccountUserRoutes
  fullName: Dropbox.Api.Account.Routes.AccountUserRoutes
- uid: Dropbox.Api.Account.Routes
  commentId: N:Dropbox.Api.Account.Routes
  name: Dropbox.Api.Account.Routes
  nameWithType: Dropbox.Api.Account.Routes
  fullName: Dropbox.Api.Account.Routes
shouldSkipMarkup: true
