### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Sharing.LinkSettings
  commentId: T:Dropbox.Api.Sharing.LinkSettings
  id: LinkSettings
  parent: Dropbox.Api.Sharing
  children:
  - Dropbox.Api.Sharing.LinkSettings.#ctor
  - Dropbox.Api.Sharing.LinkSettings.#ctor(Dropbox.Api.Sharing.AccessLevel,Dropbox.Api.Sharing.LinkAudience,Dropbox.Api.Sharing.LinkExpiry,Dropbox.Api.Sharing.LinkPassword)
  - Dropbox.Api.Sharing.LinkSettings.AccessLevel
  - Dropbox.Api.Sharing.LinkSettings.Audience
  - Dropbox.Api.Sharing.LinkSettings.Expiry
  - Dropbox.Api.Sharing.LinkSettings.Password
  langs:
  - csharp
  - vb
  name: LinkSettings
  nameWithType: LinkSettings
  fullName: Dropbox.Api.Sharing.LinkSettings
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/LinkSettings.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: LinkSettings
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/LinkSettings.cs
    startLine: 15
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>Settings that apply to a link.</p>\n"
  example: []
  syntax:
    content: 'public class LinkSettings : object'
    content.vb: >-
      Public Class LinkSettings
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Dropbox.Api.Sharing.LinkSettings.#ctor(Dropbox.Api.Sharing.AccessLevel,Dropbox.Api.Sharing.LinkAudience,Dropbox.Api.Sharing.LinkExpiry,Dropbox.Api.Sharing.LinkPassword)
  commentId: M:Dropbox.Api.Sharing.LinkSettings.#ctor(Dropbox.Api.Sharing.AccessLevel,Dropbox.Api.Sharing.LinkAudience,Dropbox.Api.Sharing.LinkExpiry,Dropbox.Api.Sharing.LinkPassword)
  id: '#ctor(Dropbox.Api.Sharing.AccessLevel,Dropbox.Api.Sharing.LinkAudience,Dropbox.Api.Sharing.LinkExpiry,Dropbox.Api.Sharing.LinkPassword)'
  parent: Dropbox.Api.Sharing.LinkSettings
  langs:
  - csharp
  - vb
  name: LinkSettings(AccessLevel, LinkAudience, LinkExpiry, LinkPassword)
  nameWithType: LinkSettings.LinkSettings(AccessLevel, LinkAudience, LinkExpiry, LinkPassword)
  fullName: Dropbox.Api.Sharing.LinkSettings.LinkSettings(Dropbox.Api.Sharing.AccessLevel, Dropbox.Api.Sharing.LinkAudience, Dropbox.Api.Sharing.LinkExpiry, Dropbox.Api.Sharing.LinkPassword)
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/LinkSettings.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/LinkSettings.cs
    startLine: 37
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.Sharing.LinkSettings\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  example: []
  syntax:
    content: public LinkSettings(AccessLevel accessLevel = null, LinkAudience audience = null, LinkExpiry expiry = null, LinkPassword password = null)
    parameters:
    - id: accessLevel
      type: Dropbox.Api.Sharing.AccessLevel
      description: >-
        The access level on the link for this file. Currently, it

        only accepts &apos;viewer&apos; and &apos;viewer_no_comment&apos;.
    - id: audience
      type: Dropbox.Api.Sharing.LinkAudience
      description: The type of audience on the link for this file.
    - id: expiry
      type: Dropbox.Api.Sharing.LinkExpiry
      description: An expiry timestamp to set on a link.
    - id: password
      type: Dropbox.Api.Sharing.LinkPassword
      description: The password for the link.
    content.vb: Public Sub New(accessLevel As AccessLevel = Nothing, audience As LinkAudience = Nothing, expiry As LinkExpiry = Nothing, password As LinkPassword = Nothing)
  overload: Dropbox.Api.Sharing.LinkSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.Sharing.LinkSettings.#ctor
  commentId: M:Dropbox.Api.Sharing.LinkSettings.#ctor
  id: '#ctor'
  parent: Dropbox.Api.Sharing.LinkSettings
  langs:
  - csharp
  - vb
  name: LinkSettings()
  nameWithType: LinkSettings.LinkSettings()
  fullName: Dropbox.Api.Sharing.LinkSettings.LinkSettings()
  type: Constructor
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/LinkSettings.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: .ctor
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/LinkSettings.cs
    startLine: 53
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>Initializes a new instance of the <xref href=\"Dropbox.Api.Sharing.LinkSettings\" data-throw-if-not-resolved=\"false\"></xref> class.</p>\n"
  remarks: >-
    This is to construct an instance of the object when

    deserializing.
  example: []
  syntax:
    content: public LinkSettings()
    content.vb: Public Sub New
  overload: Dropbox.Api.Sharing.LinkSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Dropbox.Api.Sharing.LinkSettings.AccessLevel
  commentId: P:Dropbox.Api.Sharing.LinkSettings.AccessLevel
  id: AccessLevel
  parent: Dropbox.Api.Sharing.LinkSettings
  langs:
  - csharp
  - vb
  name: AccessLevel
  nameWithType: LinkSettings.AccessLevel
  fullName: Dropbox.Api.Sharing.LinkSettings.AccessLevel
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/LinkSettings.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: AccessLevel
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/LinkSettings.cs
    startLine: 62
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>The access level on the link for this file. Currently, it only accepts\n&apos;viewer&apos; and &apos;viewer_no_comment&apos;.</p>\n"
  example: []
  syntax:
    content: public AccessLevel AccessLevel { get; protected set; }
    parameters: []
    return:
      type: Dropbox.Api.Sharing.AccessLevel
    content.vb: Public Property AccessLevel As AccessLevel
  overload: Dropbox.Api.Sharing.LinkSettings.AccessLevel*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Dropbox.Api.Sharing.LinkSettings.Audience
  commentId: P:Dropbox.Api.Sharing.LinkSettings.Audience
  id: Audience
  parent: Dropbox.Api.Sharing.LinkSettings
  langs:
  - csharp
  - vb
  name: Audience
  nameWithType: LinkSettings.Audience
  fullName: Dropbox.Api.Sharing.LinkSettings.Audience
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/LinkSettings.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Audience
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/LinkSettings.cs
    startLine: 67
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>The type of audience on the link for this file.</p>\n"
  example: []
  syntax:
    content: public LinkAudience Audience { get; protected set; }
    parameters: []
    return:
      type: Dropbox.Api.Sharing.LinkAudience
    content.vb: Public Property Audience As LinkAudience
  overload: Dropbox.Api.Sharing.LinkSettings.Audience*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Dropbox.Api.Sharing.LinkSettings.Expiry
  commentId: P:Dropbox.Api.Sharing.LinkSettings.Expiry
  id: Expiry
  parent: Dropbox.Api.Sharing.LinkSettings
  langs:
  - csharp
  - vb
  name: Expiry
  nameWithType: LinkSettings.Expiry
  fullName: Dropbox.Api.Sharing.LinkSettings.Expiry
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/LinkSettings.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Expiry
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/LinkSettings.cs
    startLine: 72
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>An expiry timestamp to set on a link.</p>\n"
  example: []
  syntax:
    content: public LinkExpiry Expiry { get; protected set; }
    parameters: []
    return:
      type: Dropbox.Api.Sharing.LinkExpiry
    content.vb: Public Property Expiry As LinkExpiry
  overload: Dropbox.Api.Sharing.LinkSettings.Expiry*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: Dropbox.Api.Sharing.LinkSettings.Password
  commentId: P:Dropbox.Api.Sharing.LinkSettings.Password
  id: Password
  parent: Dropbox.Api.Sharing.LinkSettings
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: LinkSettings.Password
  fullName: Dropbox.Api.Sharing.LinkSettings.Password
  type: Property
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/LinkSettings.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Password
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Sharing/LinkSettings.cs
    startLine: 77
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Sharing
  summary: "\n<p>The password for the link.</p>\n"
  example: []
  syntax:
    content: public LinkPassword Password { get; protected set; }
    parameters: []
    return:
      type: Dropbox.Api.Sharing.LinkPassword
    content.vb: Public Property Password As LinkPassword
  overload: Dropbox.Api.Sharing.LinkSettings.Password*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
references:
- uid: Dropbox.Api.Sharing
  commentId: N:Dropbox.Api.Sharing
  name: Dropbox.Api.Sharing
  nameWithType: Dropbox.Api.Sharing
  fullName: Dropbox.Api.Sharing
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.Sharing.LinkSettings
  commentId: T:Dropbox.Api.Sharing.LinkSettings
  parent: Dropbox.Api.Sharing
  name: LinkSettings
  nameWithType: LinkSettings
  fullName: Dropbox.Api.Sharing.LinkSettings
- uid: Dropbox.Api.Sharing.LinkSettings.#ctor*
  commentId: Overload:Dropbox.Api.Sharing.LinkSettings.#ctor
  name: LinkSettings
  nameWithType: LinkSettings.LinkSettings
  fullName: Dropbox.Api.Sharing.LinkSettings.LinkSettings
- uid: Dropbox.Api.Sharing.AccessLevel
  commentId: T:Dropbox.Api.Sharing.AccessLevel
  parent: Dropbox.Api.Sharing
  name: AccessLevel
  nameWithType: AccessLevel
  fullName: Dropbox.Api.Sharing.AccessLevel
- uid: Dropbox.Api.Sharing.LinkAudience
  commentId: T:Dropbox.Api.Sharing.LinkAudience
  parent: Dropbox.Api.Sharing
  name: LinkAudience
  nameWithType: LinkAudience
  fullName: Dropbox.Api.Sharing.LinkAudience
- uid: Dropbox.Api.Sharing.LinkExpiry
  commentId: T:Dropbox.Api.Sharing.LinkExpiry
  parent: Dropbox.Api.Sharing
  name: LinkExpiry
  nameWithType: LinkExpiry
  fullName: Dropbox.Api.Sharing.LinkExpiry
- uid: Dropbox.Api.Sharing.LinkPassword
  commentId: T:Dropbox.Api.Sharing.LinkPassword
  parent: Dropbox.Api.Sharing
  name: LinkPassword
  nameWithType: LinkPassword
  fullName: Dropbox.Api.Sharing.LinkPassword
- uid: Dropbox.Api.Sharing.LinkSettings.AccessLevel*
  commentId: Overload:Dropbox.Api.Sharing.LinkSettings.AccessLevel
  name: AccessLevel
  nameWithType: LinkSettings.AccessLevel
  fullName: Dropbox.Api.Sharing.LinkSettings.AccessLevel
- uid: Dropbox.Api.Sharing.LinkSettings.Audience*
  commentId: Overload:Dropbox.Api.Sharing.LinkSettings.Audience
  name: Audience
  nameWithType: LinkSettings.Audience
  fullName: Dropbox.Api.Sharing.LinkSettings.Audience
- uid: Dropbox.Api.Sharing.LinkSettings.Expiry*
  commentId: Overload:Dropbox.Api.Sharing.LinkSettings.Expiry
  name: Expiry
  nameWithType: LinkSettings.Expiry
  fullName: Dropbox.Api.Sharing.LinkSettings.Expiry
- uid: Dropbox.Api.Sharing.LinkSettings.Password*
  commentId: Overload:Dropbox.Api.Sharing.LinkSettings.Password
  name: Password
  nameWithType: LinkSettings.Password
  fullName: Dropbox.Api.Sharing.LinkSettings.Password
shouldSkipMarkup: true
