### YamlMime:ManagedReference
items:
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.Other
  commentId: T:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.Other
  id: TeamFolderUpdateSyncSettingsError.Other
  parent: Dropbox.Api.Team
  children:
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.Other.Instance
  langs:
  - csharp
  - vb
  name: TeamFolderUpdateSyncSettingsError.Other
  nameWithType: TeamFolderUpdateSyncSettingsError.Other
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.Other
  type: Class
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Other
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsError.cs
    startLine: 640
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>The other object</p>\n"
  example: []
  syntax:
    content: 'public sealed class Other : TeamFolderUpdateSyncSettingsError'
    content.vb: >-
      Public NotInheritable Class Other
          Inherits TeamFolderUpdateSyncSettingsError
  inheritance:
  - System.Object
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  inheritedMembers:
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsSyncSettingsError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsSyncSettingsError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsAccessError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsAccessError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsStatusError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsStatusError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsTeamSharedDropboxError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsTeamSharedDropboxError
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsOther
  - Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsOther
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.Other.Instance
  commentId: F:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.Other.Instance
  id: Instance
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.Other
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: TeamFolderUpdateSyncSettingsError.Other.Instance
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.Other.Instance
  type: Field
  source:
    remote:
      path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsError.cs
      branch: doc_fx_test
      repo: https://github.com/dropbox/dropbox-sdk-dotnet
    id: Instance
    path: dropbox-sdk-dotnet/Dropbox.Api/Generated/Team/TeamFolderUpdateSyncSettingsError.cs
    startLine: 664
  assemblies:
  - Dropbox.Api
  namespace: Dropbox.Api.Team
  summary: "\n<p>A singleton instance of Other</p>\n"
  example: []
  syntax:
    content: public static readonly TeamFolderUpdateSyncSettingsError.Other Instance
    return:
      type: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.Other
    content.vb: Public Shared ReadOnly Instance As TeamFolderUpdateSyncSettingsError.Other
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: Dropbox.Api.Team
  commentId: N:Dropbox.Api.Team
  name: Dropbox.Api.Team
  nameWithType: Dropbox.Api.Team
  fullName: Dropbox.Api.Team
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  commentId: T:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  parent: Dropbox.Api.Team
  name: TeamFolderUpdateSyncSettingsError
  nameWithType: TeamFolderUpdateSyncSettingsError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsSyncSettingsError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsSyncSettingsError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: IsSyncSettingsError
  nameWithType: TeamFolderUpdateSyncSettingsError.IsSyncSettingsError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsSyncSettingsError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsSyncSettingsError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsSyncSettingsError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: AsSyncSettingsError
  nameWithType: TeamFolderUpdateSyncSettingsError.AsSyncSettingsError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsSyncSettingsError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsAccessError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsAccessError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: IsAccessError
  nameWithType: TeamFolderUpdateSyncSettingsError.IsAccessError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsAccessError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsAccessError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsAccessError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: AsAccessError
  nameWithType: TeamFolderUpdateSyncSettingsError.AsAccessError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsAccessError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsStatusError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsStatusError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: IsStatusError
  nameWithType: TeamFolderUpdateSyncSettingsError.IsStatusError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsStatusError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsStatusError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsStatusError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: AsStatusError
  nameWithType: TeamFolderUpdateSyncSettingsError.AsStatusError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsStatusError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsTeamSharedDropboxError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsTeamSharedDropboxError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: IsTeamSharedDropboxError
  nameWithType: TeamFolderUpdateSyncSettingsError.IsTeamSharedDropboxError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsTeamSharedDropboxError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsTeamSharedDropboxError
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsTeamSharedDropboxError
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: AsTeamSharedDropboxError
  nameWithType: TeamFolderUpdateSyncSettingsError.AsTeamSharedDropboxError
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsTeamSharedDropboxError
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsOther
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsOther
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: IsOther
  nameWithType: TeamFolderUpdateSyncSettingsError.IsOther
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.IsOther
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsOther
  commentId: P:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsOther
  parent: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError
  name: AsOther
  nameWithType: TeamFolderUpdateSyncSettingsError.AsOther
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.AsOther
- uid: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.Other
  commentId: T:Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.Other
  parent: Dropbox.Api.Team
  name: TeamFolderUpdateSyncSettingsError.Other
  nameWithType: TeamFolderUpdateSyncSettingsError.Other
  fullName: Dropbox.Api.Team.TeamFolderUpdateSyncSettingsError.Other
shouldSkipMarkup: true
