name: Update Documentation

on:
  pull_request:
  workflow_dispatch:

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup existing site
        uses: actions/checkout@v2.3.4
        with:
          ref: gh-pages-holder
          path: gh-pages
      - name: validate folder
        run: ls gh-pages
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies
        run: dotnet restore dropbox-sdk-dotnet/Dropbox.Api
      - name: Copy for index
        run: cp README.md gh-pages/index.md
      - name: Install Mono Dependencies
        run: sudo apt-get install mono-runtime mono-devel msbuild
      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation YAML
        with:
          args: ./gh-pages/docfx.json
      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation HTML
        with:
          args: ./gh-pages/docfx-html.json
        timeout-minutes: 120
      - name: Push Documentation
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_PAGES_PUBLISH_TOKEN }}
          BRANCH: gh-pages-holder # The branch the action should deploy to.
          FOLDER: gh-pages # The folder the action should deploy.